### ISSUE TITLE
termuppport.zsh error

### ISSUE THREAD

**Issue by myob-hankun** [ohmyzsh/ohmyzsh#12444] opened 2024-05-23 03:28 UTC
### Describe the bug

After I upgrade the iterm, I get an error from termuppport.zsh when I open a new iterm window.
```
iconv: iconv_open(, -t): Invalid argument
Error converting string from  to UTF-8
```

### Steps to reproduce

1. Install iterm and ob-my-zsh to latest
2. open an iterm windowthe 

### Expected behavior

No errors

### OS / Linux distribution

MacOs M3 

### Zsh version

5.9

### Terminal emulator

iTerm2

### If using WSL on Windows, which version of WSL

None

### Additional context

iterm2: 3.5

**Comment by carlosala** [comment] 2024-05-23 07:53
Duplicate of #11645 
See https://github.com/ohmyzsh/ohmyzsh/issues/11645#issuecomment-1884685602

**Closed by carlosala** 2024-05-23 07:53 UTC
