### ISSUE TITLE
Virtualenvwrapper bug with PROMPT (PS1) display corrupted

### ISSUE THREAD

**Issue by matejsp** [ohmyzsh/ohmyzsh#12715] opened 2024-10-02 11:26 UTC
### Describe the bug

I am inside activated venv (with prompt pointing to the venv. And when I open new tab (cmd T) and running any directory changing command the PROMPT is garbled.

### Steps to reproduce

1. Enable plugin git, virtualenvwrapper
2. open terminal ... go into python venv
3. open new tab ... see that the same path is preserved
4. run cd ..

Prompt is garbled

### Expected behavior

I would expect PROMPT to stay the same as before.

### Screenshots and recordings

![image](https://github.com/user-attachments/assets/1058068f-2b3e-4a31-8f8a-b2fabe3e8d65)
opening new tab is putting me into the same directory (note venv is not enabled)

![image](https://github.com/user-attachments/assets/0ff7b22e-b4bf-4447-b867-1f23425e6f88)

Running any command that changes directiory I get prompt corrupted:
![image](https://github.com/user-attachments/assets/a87eb29d-7690-433c-b939-f368fdc20f8a)

### OS / Linux distribution

MacOSX 14.7

### Zsh version

5.9

### Terminal emulator

Terminal.app

### If using WSL on Windows, which version of WSL

None

**Comment by carlosala** [comment] 2024-10-08 19:48
Hi! This is a known issue, and it is expected. The way python venv work this shit out is very bad.
It is a duplicate of #12599, see https://github.com/ohmyzsh/ohmyzsh/issues/12599#issuecomment-2287935144

**Closed by carlosala** 2024-10-08 19:48 UTC

**Comment by matejsp** [comment] 2024-10-09 06:20
I have made a workaround to set _OLD_VIRTUAL_PS1 in .zshrc and it kinda works:

I saw that setups the old _OLD_VIRTUAL_PS1 that is lost when opening new tab (if already inside venv):
https://github.com/python/cpython/blob/3.13/Lib/venv/scripts/common/activate#L21-L25

appended line .zshrc 
```
_OLD_VIRTUAL_PS1=$'%(?:%{\C-[[01;32m%}%1{➜%} :%{\C-[[01;31m%}%1{➜%} ) %{\C-[[36m%}%c%{\C-[[00m%} $(git_prompt_info)'
```

The source of the issue it seems deactivate is called before calling activate reverting to corrupted PS1 ...

Perhaps virtualenvwrapper plugin could handle this logic somehow.

**Comment by carlosala** [comment] 2024-10-09 06:30
The problem is that old virtual does not pass to the new tab/shell/whatever.

I'm reluctant to add this kind of logic since some themes are dynamic and they set PROMPT themselves. There are many corner cases.
