### ISSUE TITLE
`omz plugin disable` breaks .zshrc file when disabling common substring

### ISSUE THREAD

**Issue by alexrosenfeld10** [ohmyzsh/ohmyzsh#12400] opened 2024-05-07 18:34 UTC
### Describe the bug

`omz plugin disable git` will break a zshrc file with plugins that look like this:

```shell
plugins=(
    git
    git-open
    autoupdate
    zsh-syntax-highlighting
    zsh-autosuggestions
    autojump
    brew
    docker
    fzf
    rust
    thefuck
    zsh-interactive-cd
    zsh-bat
    asdf
)
```

### Steps to reproduce

1. Set up OhMyZsh
2. Set up plugins, for example:
```shell
plugins=(git autoupdate git-open zsh-syntax-highlighting zsh-autosuggestions autojump brew docker fzf rust thefuck zsh-interactive-cd zsh-bat asdf)
```

or 

```shell
plugins=(
    git
    autoupdate
    git-open
    zsh-syntax-highlighting
    zsh-autosuggestions
    autojump
    brew
    docker
    fzf
    rust
    thefuck
    zsh-interactive-cd
    zsh-bat
    asdf
)
```

3. run `omz plugin disable git` 

### Expected behavior

The `git` plugin gets removed, and the `git-open` plugin isn't impacted.  This isn't quite what happens though, the actual result is:

```shell
plugins=(
    autoupdate
-open
    zsh-syntax-highlighting
    zsh-autosuggestions
    autojump
    brew
    docker
    fzf
    rust
    thefuck
    zsh-interactive-cd
    zsh-bat
    asdf
)
```

Note - the same behavior happens when `plugins` is one line:

```shell
# this:
plugins=(git autoupdate git-open zsh-syntax-highlighting zsh-autosuggestions autojump brew docker fzf rust thefuck zsh-interactive-cd zsh-bat asdf)

# gets turned into:
plugins=(autoupdate-open zsh-syntax-highlighting zsh-autosuggestions autojump brew docker fzf rust thefuck zsh-interactive-cd zsh-bat asdf)
```

### OS / Linux distribution

macOS

### Zsh version

5.9

### Oh My Zsh version

master (668ca3a)

### Terminal emulator

iTerm2

### If using WSL on Windows, which version of WSL

None

**Comment by mcornella** [comment] 2024-05-07 18:49
Oops that's my bad, thanks for the submission! I'll take a look shortly.

**Comment by mcornella** [comment] 2024-05-07 19:01
Can you test in your macOS whether #12401 fixes this correctly? I'm not too sure about AWK regex support in there. You can test it out with `omz pr test 12401`.

**Comment by alexrosenfeld10** [comment] 2024-05-08 01:15
@mcornella thanks for the quick reply. Here's the result of the test:

## take one, all in one line

`~/.zshrc` file plugins section before:
```shell
plugins=(git autoupdate git-open zsh-syntax-highlighting zsh-autosuggestions autojump brew docker fzf rust thefuck zsh-interactive-cd zsh-bat asdf)
```

result:
```shell
❯ omz pr test 12401
❯ code ~/.zshrc
❯ omz plugin disable git
/Users/alexrosenfeld/.zshrc:81: parse error near `)'
omz::plugin::disable: broken syntax in '~/.zshrc'. Rolling back changes...
```

`~/.zshrc` file plugins section after, unchanged.


## take two, with newlines instead

`~/.zshrc` file plugins section before:
```shell
plugins=(
  git
  autoupdate
  git-open
  zsh-syntax-highlighting
  zsh-autosuggestions
  autojump
  brew
  docker
  fzf
  rust
  thefuck
  zsh-interactive-cd
  zsh-bat
  asdf
)
```

command result:
```shell
❯ omz pr test 12401
❯ code ~/.zshrc
❯ omz plugin disable git
omz::plugin::disable: plugins disabled: git.
```

`~/.zshrc` file plugins section after, result looks good:
```shell
plugins=(
  autoupdate
  git-open
  zsh-syntax-highlighting
  zsh-autosuggestions
  autojump
  brew
  docker
  fzf
  rust
  thefuck
  zsh-interactive-cd
  zsh-bat
  asdf
)
```

## take three, bonus round, new error case discovered

starting state, same as take two (plugins separated by newlines):

```shell
plugins=(
  git
  autoupdate
  git-open
  zsh-syntax-highlighting
  zsh-autosuggestions
  autojump
  brew
  docker
  fzf
  rust
  thefuck
  zsh-interactive-cd
  zsh-bat
  asdf
)
```

shell commands:

```shell
❯ omz plugin disable git
omz::plugin::disable: plugins disabled: git.
❯ omz plugin enable git
omz::plugin::enable: plugins enabled: git.
❯ omz plugin disable git
/Users/alexrosenfeld/.zshrc:127: parse error near `\n'
omz::plugin::disable: broken syntax in '~/.zshrc'. Rolling back changes...
```

state after the first disable + first enable:
```shell
plugins=(
  autoupdate
  git-open
  zsh-syntax-highlighting
  zsh-autosuggestions
  autojump
  brew
  docker
  fzf
  rust
  thefuck
  zsh-interactive-cd
  zsh-bat
  asdf
 git)
```

**Comment by alexrosenfeld10** [comment] 2024-05-08 01:18
also, sidenote - trying to go back to master, running into another bug (I think, might just be user error? not sure).. let me know if you want me to open a separate issue):

```shell
❯ omz pr clean
ohmyzsh/pull-12401 141a154 fix(cli): fix disabling plugins by accident in `omz plugin disable`

omz::pr::clean: do you want remove these Pull Request branches? [Y/n] Y
omz::pr::clean: removing all Oh My Zsh Pull Request branches...
error: branch '* ohmyzsh/pull-12401' not found
```

**Comment by mcornella** [comment] 2024-05-08 18:52
OK that should be all the edge cases fixed now. I introduced a test suite which will be refactored into its own thing in the future. Sorry for the back and forth, I was in a rush this morning to get this out.

The tests already done here are working correctly.

**Closed** 2024-05-08 20:20 UTC
Labels: Bug, Area: core

**Comment by alexrosenfeld10** [comment] 2024-05-08 20:26
@mcornella thanks for fixing. I think there are still some issues here though:

`~/.zshrc`:

```shell
plugins=(
  git
  git-open
  autoupdate
  zsh-syntax-highlighting
  zsh-autosuggestions
  autojump
  brew
  docker
  fzf
  rust
  thefuck
  zsh-interactive-cd
  zsh-bat
  asdf
)
```

result:
```shell
❯ omz plugin disable git
omz::plugin::disable: plugin 'git' is not enabled.
```

**Comment by alexrosenfeld10** [comment] 2024-05-08 20:27
same behavior for
```shell
plugins=(git git-open autoupdate zsh-syntax-highlighting zsh-autosuggestions autojump brew docker fzf rust thefuck zsh-interactive-cd zsh-bat asdf)
```

**Comment by mcornella** [comment] 2024-05-08 20:29
The function only disables a plugin if it's in the `$plugins` array within the session. That's by design. If you make changes to it, you should `omz reload` beforehand.

**Comment by alexrosenfeld10** [comment] 2024-05-08 20:37
ah, got it, ok. thanks!!
