### ISSUE TITLE
After WD update exclamation mark feature is broken 

### ISSUE THREAD

**Issue by alekc** [ohmyzsh/ohmyzsh#12489] opened 2024-06-10 12:33 UTC
### Describe the bug

Found this on several of my systems, after recent updates (within the last month?), it looks like I can no longer execute previous commands by the using the `!` + number in history. 

### Steps to reproduce

Recall the history 
```shell
$ history
...
 1059  date
 1060  history
 1061  omz
 1062  omz version
 1063  omz update
```
run previous command by using it's number
```
~ on 🐳 v24.0.7 (rancher-desktop) using ☁️ SUBHigherEnvs002
➜ !1059

~ on 🐳 v24.0.7 (rancher-desktop) using ☁️ SUBHigherEnvs002
```
nothing happens (while it should have printed out the `date` command ready to be submitted. 

### Expected behavior

typing `!+command number` fetches previous command

### OS / Linux distribution

MacOS 14/Ubuntu 22.04

### Zsh version

5.9 (master)

### Terminal emulator

ITerm, no emulator on linux

### If using WSL on Windows, which version of WSL

None

### Additional context

After further investigation, it looks like this commit https://github.com/ohmyzsh/ohmyzsh/commit/f6b3fc84d192274f245a7322c3994767c5e68691 has broken the feature

**Comment by mcornella** [comment] 2024-06-11 14:58
That commit shouldn't be related to causing this issue. I can't reproduce this, could you:

- Post the output of `setopt`
- Try to reproduce the issue with a minimal `.zshrc` file (you can use our Docker image: `docker run -it ohmyzsh/zsh:5.9` and incrementally add the lines that cause this issue)
- If that's not enough or you can't reproduce this, we may ask for your startup files to debug.

Thanks!

**Comment by alekc** [comment] 2024-06-11 17:29
Interesting... I've been able to reproduce it via docker  `docker run -it --rm ohmyzsh/zsh:5.9`

Once in the container 

```
cd /root/.oh-my-zsh
git pull 
cd

echo "plugins"
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

cat <<EOF > ~/.zshrc
export ZSH="\$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"
plugins=(
  git
  aws
  docker
  wd
  zsh-syntax-highlighting
)
COMPLETION_WAITING_DOTS="true"
export HOMEBREW_NO_AUTO_UPDATE=1
alias k=kubectl
export PATH="~/bin:\$PATH"
source \$ZSH/oh-my-zsh.sh
EOF

source ~/.zshrc
```
now testing 
```
date
➜  ~ date
Tue Jun 11 17:11:43 UTC 2024
➜  ~ history
...
   11  cat .zshrc
   12  date
➜  ~ !!
➜  ~ !12
➜  ~
```

lets try to rollback to https://github.com/ohmyzsh/ohmyzsh/tree/04b66b230857fb9bc28af5e7590b09ff79f888fa
```
cd /root/.oh-my-zsh
git checkout 04b66b230857fb9bc28af5e7590b09ff79f888fa
source ~/.zshrc
➜  .oh-my-zsh git:(04b66b23) !12
➜  .oh-my-zsh git:(04b66b23) date
```
now  the next commit https://github.com/ohmyzsh/ohmyzsh/tree/f6b3fc84d192274f245a7322c3994767c5e68691
```
cd /root/.oh-my-zsh
git checkout f6b3fc84d192274f245a7322c3994767c5e68691
source ~/.zshrc
➜  .oh-my-zsh git:(f6b3fc84) !12
➜  .oh-my-zsh git:(f6b3fc84)
```
and its broken

If I change the .zshrc and remove the wd plugin
```
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"
plugins=(
  git
  aws
  docker
  #wd
  zsh-syntax-highlighting
)
COMPLETION_WAITING_DOTS="true"
export HOMEBREW_NO_AUTO_UPDATE=1
alias k=kubectl
export PATH="~/bin:$PATH"
source $ZSH/oh-my-zsh.sh
```
and reload zsh, it will work again
```
➜  ~ source .zshrc
➜  ~ !12
➜  ~ date
Tue Jun 11 17:29:08 UTC 2024
```

**Comment by mcornella** [comment] 2024-06-11 20:19
Damn that's what I call a perfect ticket, I'm about to cry of joy. This should be enough to find the culprit, I'll update you tomorrow. Thanks!!

**Comment by mcornella** [comment] 2024-06-12 08:53
OK so this looks to be a bug in the `wd_restore_buffer` introduced in [[1]], which destroys the `$BUFFER` when `$saved_buffer` is empty. This causes the issue on `line-init` at which point zsh should have left in the command line the command fetched from history (i.e. `$BUFFER` should contain the last run command if `!!` was run).

I've opened https://github.com/mfaerevaag/wd/issues/126 to solve this. Feel free to subscribe to that issue for updates. When a new version is released we'll update the plugin here as well.

Many thanks!

[1]: https://github.com/mfaerevaag/wd/commit/b31e62a4db4d23d55e8d67adcc02919a7b011df4#diff-cbb1f6b907ca538ea66785e74d0881baedaa613c42409ae9da860ce8f8e58deb

**Comment by alekc** [comment] 2024-06-12 09:02
thanks for the update.

**Comment by p1r473** [comment] 2024-06-12 16:13
Whoops! Fixed in https://github.com/mfaerevaag/wd/pull/127

**Closed** 2024-06-16 06:44 UTC
Labels: Bug, Area: plugin
