### ISSUE TITLE
Activate completion features without adding any aliases

### ISSUE THREAD

**Issue by tremby** [ohmyzsh/ohmyzsh#9621] opened 2021-01-26 21:18 UTC
**Is your feature request related to a particular plugin or theme? If so, specify it.**
Sort of. Right now specifically the npm plugin, but it applies to others too.

**Is your feature request related to a problem? Please describe.**
Often I want the completion that a plugin provides but I never want any of the aliases. I have no interest in learning them, and if my shell is littered with aliases it massively increases the possibility that when I make a typo in a short command something totally unexpected happens.

**Describe the solution you'd like**
Some way to specify whether or not I want each plugin's aliases. Perhaps it would be simplest to split completion and aliases to separate plugins?

**Describe alternatives you've considered**
I could edit the source to comment out all the aliases but that's not maintainable.
I could unalias everything after the fact but that's a mess and not maintainable.
I could install the completion separately but then why am I using ohmyzsh.

**Comment by mcornella** [comment] 2022-02-03 13:48
There's a proposal for a way to turn off aliases in https://github.com/ohmyzsh/ohmyzsh/issues/10644. Please have a look and add your feedback. Thanks!

**Comment by mcornella** [comment] 2022-02-03 13:49
I'll close this because it's a duplicate of #7328.

**Closed by mcornella** 2022-02-03 13:49 UTC
Labels: Feature
