### ISSUE TITLE
After each command, the executed command is printed before the result

### ISSUE THREAD

**Issue by xvitcoder** [ohmyzsh/ohmyzsh#9282] opened 2020-09-23 11:13 UTC
I am not sure if it is an issue of oh-my-zsh/ but I have tested with clean systems
After I install oh-my-zsh, all the commands executed afterwards are printed before the result

For example the command `ls` in my home folder outputs
> lsDesktop  Documents  Downloads  Music  Pictures  Temporary  Video  Workspace

as you can see the `ls` is the first what is printed

`lsblk` - outputs
> lsblkNAME   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT  
> sda      8:0    0  113G  0 disk  
> ├─sda1   8:1    0  512M  0 part  
> ├─sda2   8:2    0   50G  0 part /  
> └─sda3   8:3    0 62.5G  0 part /home  
> sdb      8:16   1  7.2G  0 disk  
> ├─sdb1   8:17   1  647M  0 part  
> └─sdb2   8:18   1   64M  0 part

and so with every command which is annoying

if I disable `oh-my-zsh` then the problem disappears.

**Comment by raghuraju** [comment] 2020-09-26 12:52
Can you mention the environment in which this is happening? Like OS, its version, version of ZSH etc.

**Comment by xvitcoder** [comment] 2020-09-26 16:34
OS: Arch Linux
Kernel: 5.8.10-arch1-1
Shell: zsh 5.8
Terminal: alacritty

it is the latest zsh, even today made the update of it, and the problem persist

**Comment by naveen-kumar-r** [comment] 2020-09-26 17:47
mostly it is originating from shell verbose config.

```
naveen@Naveen-HomePC:/boot$ set -v
set -v
naveen@Naveen-HomePC:/boot$ ls
ls
config-4.15.0-74-generic  grub                          initrd.img-5.4.0-42-generic  memtest86+.elf                System.map-5.4.0-42-generic  vmlinuz-4.15.0-76-generic
config-4.15.0-76-generic  initrd.img                    initrd.img-5.4.0-48-generic  memtest86+_multiboot.bin      System.map-5.4.0-48-generic  vmlinuz-5.4.0-42-generic
config-5.4.0-42-generic   initrd.img-4.15.0-74-generic  initrd.img.old               System.map-4.15.0-74-generic  vmlinuz                      vmlinuz-5.4.0-48-generic
config-5.4.0-48-generic   initrd.img-4.15.0-76-generic  memtest86+.bin               System.map-4.15.0-76-generic  vmlinuz-4.15.0-74-generic    vmlinuz.old
naveen@Naveen-HomePC:/boot$ set +v
set +v
naveen@Naveen-HomePC:/boot$ ls
config-4.15.0-74-generic  grub                          initrd.img-5.4.0-42-generic  memtest86+.elf                System.map-5.4.0-42-generic  vmlinuz-4.15.0-76-generic
config-4.15.0-76-generic  initrd.img                    initrd.img-5.4.0-48-generic  memtest86+_multiboot.bin      System.map-5.4.0-48-generic  vmlinuz-5.4.0-42-generic
config-5.4.0-42-generic   initrd.img-4.15.0-74-generic  initrd.img.old               System.map-4.15.0-74-generic  vmlinuz                      vmlinuz-5.4.0-48-generic
config-5.4.0-48-generic   initrd.img-4.15.0-76-generic  memtest86+.bin               System.map-4.15.0-76-generic  vmlinuz-4.15.0-74-generic    vmlinuz.old
```

**Comment by mcornella** [comment] 2020-09-26 18:08
> mostly it is originating from shell verbose config.

That would explain it if there was a newline after the command. My intuition instead is that there's a preexec function running. @xvitcoder please post the output of `which preexec $preexec_functions`.

**Comment by xvitcoder** [comment] 2020-09-26 22:16
the output of `which preexec $preexec_functions` is:

```sh
omz_termsupport_preexec () {
	[[ "${DISABLE_AUTO_TITLE:-}" == true ]] && return
	emulate -L zsh
	setopt extended_glob
	local -a cmdargs
	cmdargs=("${(z)2}")
	if [[ "${cmdargs[1]}" = fg ]]
	then
		local job_id jobspec="${cmdargs[2]#%}"
		case "$jobspec" in
			(<->) job_id=${jobspec}  ;;
			("" | % | +) job_id=${(k)jobstates[(r)*:+:*]}  ;;
			(-) job_id=${(k)jobstates[(r)*:-:*]}  ;;
			([?]*) job_id=${(k)jobtexts[(r)*${(Q)jobspec}*]}  ;;
			(*) job_id=${(k)jobtexts[(r)${(Q)jobspec}*]}  ;;
		esac
		if [[ -n "${jobtexts[$job_id]}" ]]
		then
			1="${jobtexts[$job_id]}"
			2="${jobtexts[$job_id]}"
		fi
	fi
	local CMD=${1[(wr)^(*=*|sudo|ssh|mosh|rake|-*)]:gs/%/%%}
	local LINE="${2:gs/%/%%}"
	title '$CMD' '%100>...>$LINE%<<'
}
```

about the shell verbose config

```sh
➜  ~ ls
lsDesktop  Documents  Downloads  Music  Notes  Pictures  Video  VirtualBox  Workspace
➜  ~ set -v
set%                                                                                                                                                                                                                                                                                      ➜  ~ ls
ls
lsDesktop  Documents  Downloads  Music  Notes  Pictures Video  VirtualBox  Workspace
➜  ~ set +v
set +v
set%                                                                                                                                                                                                                                                                                      ➜  ~ ls
lsDesktop  Documents  Downloads  Music  Notes  Pictures  Video  VirtualBox  Workspace
```

**Comment by pasha009** [comment] 2020-09-27 07:21
> mostly it is originating from shell verbose config.

I also had the same problem but it disappeared when i uninstalled ohmyzsh. So it has something to do with this.

**Comment by xvitcoder** [comment] 2020-09-27 09:22
If I remove the folder `~/.oh-my-zsh`, then no such problem occures

```sh
arch-workstation% ls
Desktop  Documents  Downloads  Music  Notes  Pictures Video  VirtualBox  Workspace
```
once I download the oh-my-zsh again, the problem returns

```sh
➜  ~ ls
lsDesktop  Documents  Downloads  Music  Notes  Pictures  Screenshots  Temporary  Video  VirtualBox  Workspace
```
and this is with the default `.zshrc` file, with no changes in it, so I think it definitly comes from the `oh-my-zsh` itself.
I had no such issue 2 weeks ago, it apeared after I updraded `oh-my-zsh`

**Comment by mcornella** [comment] 2020-09-27 11:23
Ok, it looks like the title function is the problem. Please run `typeset -f -t title` and post the output when running `ls` for example.

**Comment by mcornella** [comment] 2020-09-27 11:24
> I also had the same problem but it disappeared when i uninstalled ohmyzsh. So it has something to do with this.

@pasha009 which terminal do you use, and what's the value of `$TERM`?

**Comment by xvitcoder** [comment] 2020-09-27 12:01
@mcornella this is the result of `typeset`

```sh
➜  ~ typeset -f -t title
typeset%                                                                                                                                                                                                                                                                                  +title:1> emulate -L zsh
+title:2> setopt prompt_subst
+title:4> [[ '' == *term* ]]
+title:8> : '%n@%m: %~'
+title:10> case screen-256color (cygwin | xterm* | putty* | rxvt* | konsole* | ansi | mlterm*)
+title:10> case screen-256color (screen*)
+title:16> print -Pn '\ek%15\<..\<%~%\<\<\e\'
➜  ~ ls
+title:1> emulate -L zsh
+title:2> setopt prompt_subst
+title:4> [[ '' == *term* ]]
+title:8> : '%100>...>$LINE%<<'
+title:10> case screen-256color (cygwin | xterm* | putty* | rxvt* | konsole* | ansi | mlterm*)
+title:10> case screen-256color (screen*)
+title:16> print -Pn '\ek\$CMD\e\'
lsDesktop  Documents  Downloads  Music  Notes  Pictures Video  VirtualBox  Workspace
+title:1> emulate -L zsh
+title:2> setopt prompt_subst
+title:4> [[ '' == *term* ]]
+title:8> : '%n@%m: %~'
+title:10> case screen-256color (cygwin | xterm* | putty* | rxvt* | konsole* | ansi | mlterm*)
+title:10> case screen-256color (screen*)
+title:16> print -Pn '\ek%15\<..\<%~%\<\<\e\'
➜  ~
```

**Comment by mcornella** [comment] 2020-09-27 12:16
Ok are you running `screen`? Because if not, `$TERM` shouldn't be `screen-256color`, otherwise the `print`-ed sequence won't be swallowed by alacritty. If you're not using `screen`, try another TERM value, like `export TERM=xterm-256color`.

**Comment by pasha009** [comment] 2020-09-27 18:20
> @pasha009 which terminal do you use, and what's the value of `$TERM`?

Terminal: `Alacritty`
TERM: tried `screen-256color`, `xterm-256color` and `tmux-256color`, but none worked for me.
I use `tmux` but the behavior was same inside or outside it.

**Comment by mcornella** [comment] 2020-09-27 20:42
Can you try with `TERM=alacritty` and the following change? (copy-paste to the terminal is enough)

```zsh
function title {
  emulate -L zsh
  setopt prompt_subst

  [[ "$EMACS" == *term* ]] && return

  # if $2 is unset use $1 as default
  # if it is set and empty, leave it as is
  : ${2=$1}

  case "$TERM" in
    cygwin|xterm*|putty*|rxvt*|konsole*|ansi|mlterm*)
      print -Pn "\e]2;${2:q}\a" # set window name
      print -Pn "\e]1;${1:q}\a" # set tab name
      ;;
    screen*|tmux*)
      print -Pn "\ek${1:q}\e\\" # set screen hardstatus
      ;;
    alacritty)
      print -Pn "\e]0;${1:q}\a" # set tab name
      ;;
    *)
      if [[ "$TERM_PROGRAM" == "iTerm.app" ]]; then
        print -Pn "\e]2;${2:q}\a" # set window name
        print -Pn "\e]1;${1:q}\a" # set tab name
      else
        # Try to use terminfo to set the title
        # If the feature is available set title
        if [[ -n "$terminfo[fsl]" ]] && [[ -n "$terminfo[tsl]" ]]; then
          echoti tsl
          print -Pn "$1"
          echoti fsl
        fi
      fi
      ;;
  esac
}
```

**Comment by xvitcoder** [comment] 2020-09-28 06:06
Yes now it works, if changed the `TERM=alacritty`, also `TERM=xterm-256color` worked for me too.
Thank you @mcornella

**Comment by mcornella** [comment] 2020-09-28 09:40
So `xterm-256color` worked for you, but not for @pasha009? Which Alacritty version are you both using?

**Comment by pasha009** [comment] 2020-09-28 17:41
> So `xterm-256color` worked for you, but not for @pasha009? Which Alacritty version are you both using?

`alacritty 0.6.0-dev`

Sorry, I think I mistakenly recollected trying  `xterm-256color` . I had uninstalled oh-my-zsh some time ago. 
With fresh installation of oh-my-zsh without any edits, i see the problem appears when `TERM=screen-256color` but goes away with `TERM=xterm-256color`.

So i guess using `screen-256color` was the problem.

**Comment by mcornella** [comment] 2020-09-28 18:43
Ok I'll close this as not a bug then. Thanks!

**Closed by mcornella** 2020-09-28 18:43 UTC

**Comment by xvitcoder** [comment] 2020-09-29 04:55
I am on `alacritty 0.5.0`

**Comment by dobsondev** [comment] 2024-09-11 02:44
I just wanted to post and say that the fix mentioned here worked for me as well using OS X with iTerm2. Switching from `export TERM=screen-256color-bce` to `export TERM=xterm-256color` in my `.zshrc` file fixed the issue. I searched for quite a while to find this so hoping this helps someone else!

I was actually only experiencing the issue when I was in integrated Terminals (`nvim` and `zellij`) for whatever reason, but as mentioned this fix work. Thanks again!

**Comment by chandpriyankara** [comment] 2025-06-15 02:55
#export TERM=tmux-256color
I had tmux-256color enabled and it was printing the same command with result.
Once I set following, it was fixed. Not sure of the reason, but it worked for me while ohmyzsh enabled.

export TERM=xterm-256color

![Image](https://github.com/user-attachments/assets/d3e6d160-9522-4c4b-b756-d59b5666d27b)
