### ISSUE TITLE
System locks up during tab completion when oh-my-zsh is enabled

### ISSUE THREAD

**Issue by BryceBeagle** [ohmyzsh/ohmyzsh#7023] opened 2018-07-28 22:28 UTC
I am having an issue where my system locks up completely for a few seconds and then catches up to itself. It doesn't always happen, but I believe that it occurs most often when tab completion would result in either no results, or more than one. It doesn't seem to lock up if there is only one valid completion. Furthermore, repeating a tab completion for a specific input that just caused a lock up never causes another until a new shell is opened.

Here's a screenshot of gnome-system-monitor while I run tab completion:
![image](https://user-images.githubusercontent.com/5437880/43361012-0efcc94e-9279-11e8-9184-1f3d6bc285c7.png)

I have attached a log obtained using <kbd>CTRL</kbd><kbd>X</kbd>+<kbd>?</kbd> if it could be any help:
[tab-completion.log](https://github.com/robbyrussell/oh-my-zsh/files/2238332/tab-completion.log)

If I comment out `antigen use oh-my-zsh` from my .zshrc, I do not have this issue. My .zshrc can be seen [here](https://github.com/BryceBeagle/dotfiles/blob/f3ce13f441bd58640fd8464a90667bd52ffa1031/zsh/.zshrc).

I've done a bunch of searching on this topic and most issues related to zsh/oh-my-zsh tab completion result from using it in git tracked directories. This occurs in _all_ directories for me.

How can I troubleshoot this?

**Comment by dozor** [comment] 2018-08-17 18:30
I am also experiencing this issue of tab completion locking up.

When I comment out the oh-my-zsh.sh script (source $ZSH/oh-my-zsh.sh) in ~/.zshrc, tab completion works as expected.

I tried updating, but I am on the latest commit from Aug 16th 2018.

I have noticed that it seems to occur on full path (top level "/") directories, but the same path will not lock up if using the relative path.

**Examples**

This will lock up:
ls -l /mydir/< TAB >

This will work normally:
cd /
ls -l mydir/< TAB >

**Comment by dozor** [comment] 2018-08-17 18:40
Update.

I enabled case sensitive completion and it fixed the issue for me.

~/.zshrc
# Uncomment the following line to use case-sensitive completion.
CASE_SENSITIVE="true"

**Comment by mcornella** [comment] 2018-08-17 19:07
> How can I troubleshoot this?

Since this is a performance bug your best bet is to enabling completion tracing (`typeset -f -t _main_complete` will work for any command you try to complete), and looking for the place where the completion hangs, provided that it hangs somewhere.

**Comment by mcornella** [comment] 2018-08-17 19:09
It's also useful to provide your `zsh --version`.

**Comment by BryceBeagle** [comment] 2018-08-19 21:53
Unfortunately, enabling case sensitive completion doesn't fix the issue for me and it still hangs.

zsh --version: zsh 5.5.1 (x86_64-unknown-linux-gnu)

Package: zsh 5.5.1-2 (from Arch Extra repo)
OS: Arch Linux

It also does not hang in a consistent spot each time. Here's an output of an ls with the typeset called.
[typset.log](https://github.com/robbyrussell/oh-my-zsh/files/2300697/typset.log).

When the autocomplete hangs, it hangs my entire system, including the graphics rendering. My guess is that the terminal output isn't exactly at pace with the command and it freezes visually before the line that causes the hang is printed to the console.

Please let me know if there's anything more that I can provide.

**Comment by cmol** [comment] 2019-02-19 09:48
I have the same issue, it is not fixed with setting case sensitive to true. I can replicate the issue with a very high certainty using `ssh-copy-id part-of-name` and having entries in my ssh-config as: part-of-name-1 and part-of-name-2 (not exactly what I have, but for all purposes, this is the same).

I'm on ubuntu16.04 with zsh --version
zsh 5.1.1 (x86_64-ubuntu-linux-gnu)

**Comment by smac89** [comment] 2019-05-10 03:48
@cmol 
I had the same issue with ssh completions. See if this blog post fixes it for you:
https://destinmoulton.com/blog/2018/how-to-disable-zsh-ssh-hosts-completion/

**Comment by BryceBeagle** [comment] 2019-05-10 07:06
I should note here that I no longer have this issue. I found out that it only happened using the Budgie desktop environment and I switched to QTile for a while. I recently switched back to Budgie and the issue is completely gone. Whatever was broken for me must have been fixed while I was away.

**Comment by cmol** [comment] 2019-05-10 14:05
@smac89
I have added that fix, and will see how things are working out with that.

**Comment by cmol** [comment] 2019-05-15 10:51
@smac89
So far I haven't seen the issue so it looks like this workaround works for me as well.

**Comment by ogiekako** [comment] 2020-04-17 13:58
I experience the same issue. No update?

**Comment by mitsh** [comment] 2020-05-01 06:22
same here

**Comment by FacundoAcevedo** [comment] 2020-05-08 12:34
I'm having the same problem.

**Comment by pantuts** [comment] 2020-05-11 11:31
Same here.

**Comment by HendrikPoppe** [comment] 2020-05-12 17:09
Also got this hickups but only for npm completion.
zsh on termux at android

**Comment by alvinsunyixiao** [comment] 2020-05-29 15:45
I also have this issue, and I think this [powerlevel10k](https://github.com/romkatv/powerlevel10k) theme made the problem worse. With the default theme `robbyrussell`, the hiccup only happens during the first completion of a newly opened shell. But with `powerlevel10k`, my `vim` started experiencing random hiccups as well, and this would not have happened if oh-my-zsh is disabled.

**Comment by tylergannon** [comment] 2020-10-07 18:14
I've actually deactivated oh-my-zsh on the Centos 7 cluster I use for work, because this problem recently cropped up for me there and I don't really know how to troubleshoot.  I get very long hangups that I can't `^C` to break from ... 175-200 seconds, at random when invoking tab completion.

I'll keep watching this issue to see if there are any clues as to how I can troubleshoot.

**Comment by marfeljoergsen** [comment] 2020-10-15 10:17
Same problem here, when I try tab-completion on "cd ~/.config". I used "autoload -t _cd" and got the same:

```
...
+_path_files:454> [[ .config/ = (#b)*/(*) ]]
+_path_files:462> [[ -n '' ]]
+_path_files:465> compfiles -P tmp1 accex '' 'm:{a-zA-Z}={A-Za-z} m:{a-zA-Z}={A-Za-z}' '' fake

```
I've been using zsh for a very long time, but the problem first started now. In my case I have some bind-mounts to CIFS-mounted directories, but they're not mounted to ~/ (instead ~/Download/bindMount) - but these are the only changes to my system that I can think of that could've introduced this problem for me... So I suspect it's a bug - and from my perspective, I think it's related to handling of (bind-) mounted directories - am also using powerlevel10k + zsh 5.8 (x86_64-pc-linux-gnu). I'll keep watching this thread, to learn from others with the same problem - especially if you can confirm (or the opposite, deny) that this problem exists while you have (bind?-) - mounted directories, maybe this kind of info can lead to a solution or a bug-fix... I don't see tab-completion should hickup even if there are problems with (bind)-mounts in other directories (this is only my personal hypothesis of the cause of the problem, cannot talk on behalf of all of you).

**Comment by mcornella** [comment] 2020-10-15 22:37
The `compfiles` line is a distraction, it actually hangs in the line after that, when trying to expand the glob obtained from the `compfiles` call, stored in `tmp1`: https://github.com/zsh-users/zsh/blob/77d203f3fbbd76386bf197f9776269a1de580bb5/Completion/Unix/Type/_path_files#L472

I tried using a samba mount in my home directory, then severing the connection with the samba host, and it too hangs for a few seconds while trying to provide valid completion entries. I tried with completing `cd ~/.config` and having the mount in `~/Download/bindmount` but there was no hangup, zsh knew not to look in there, so it would be interesting to know which glob `compfiles` gave you.

You can do that by manually inserting the following in the line before [this line](https://github.com/zsh-users/zsh/blob/77d203f3fbbd76386bf197f9776269a1de580bb5/Completion/Unix/Type/_path_files#L472), in the `_path_files` file.
```zsh
typeset tmp1
```
This will print the value of `tmp1` when completing a cd command. You can find the `_path_files` file with the following snippet:
```zsh
ls -l $(for d ($fpath); do [[ -f $d/_path_files ]] && { echo $d/_path_files; break }; done)
```

**Comment by marfeljoergsen** [comment] 2020-10-17 15:12
@mcornella : Interesting - thanks a lot for helping! As for finding the _path_files-file, I just did a `yay -Ql zsh | grep -i path_file` which returned /usr/share/zsh/functions/Completion/Unix/_path_files ; but thanks, I also learned a nice (and really fast) method from your suggestion. I made a mistake in my previous post and have updated the post, with the new correct information, so it (maybe) can help others, if they did the same mistake as I did. As for the change you suggested, when my server to my bind-mounted directory is offline, this is what happens after I added "typeset tmp1" in line 472 - just before "tmp1=( $~tmp1 ) 2> /dev/null: 

So, I write "cd ~/.con" and want to type tab to expand to ~/.config - but with ~/.thunderbird as a bind-mounted (offline) directory, this seems to cause problems, here's the output:

`~  cd ~/.contmp1=( '/home/myuser/.*(-/)' /home/myuser/.. /home/myuser/. )`

It's like zfs wants to descend into ~/.thunderbird - even though I think it should only traverse files/directories inside the home-folder? At first, this was a bit unexpected - but I can see that it's the same problem when I just try to "ls -latrh" inside the home folder and using bash instead of zsh...

This means that I can conclude that my problem isn't related to zsh - it's related to the offline bind-mounted directory, in the same folder... Cannot speak or say anything about what other people experience, it seems to work fine for me now (or just the same as bash). Thanks for the help, my mystery seems to be solved, will leave this if it can help other people too (my solution obviously is to either turn on the server or force unmount the problematic folder)!

**Comment by mcornella** [comment] 2020-10-17 19:25
> I also learned a nice (and really fast) method from your suggestion

Actually it could be simplified with `ls -l ${^fpath}/_path_files(N)`.

### Getting to the root of the problem

With your setup I get the same problem: `tmp1=('.*(-/)' '..' '.')`. More concretely, if I run an strace of the zsh process when expanding the first glob,  with `strace zsh -c 'echo .*(-/)'`, the strace output hangs `lstat`-ing the `.thunderbird` folder:

```
lstat(".rustup", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
lstat(".subversion", {st_mode=S_IFDIR|0777, st_size=4096, ...}) = 0
lstat(".bash_profile", {st_mode=S_IFREG|0644, st_size=200, ...}) = 0
lstat(".npm", {st_mode=S_IFDIR|0777, st_size=4096, ...}) = 0
lstat(".otp", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
lstat(".w3m", {st_mode=S_IFDIR|0700, st_size=4096, ...}) = 0
lstat(".gradle", {st_mode=S_IFDIR|0777, st_size=4096, ...}) = 0
lstat(".thunderbird",
```

and the `lstat` call eventually fails (I counted ~2 minutes) with a `EHOSTDOWN (Host is down)` error.

This of course depends on the system that handles the CIFS mount. I used `mount.cifs`, so the setting that controls the timeout is `echo_interval`, which specifies the time between echo requests are sent on an idle connection. The timeout happens at 2 echo_intervals (the default is 60 seconds, so the timeout happens in 120 seconds). You can play with the settings to make the timeout shorter. 
I've tried with `echo_interval=10` (you specify this when `mount`ing) and the hangup is indeed shorter.

### Fixing one part of the problem

Still, I think the completion could be smarter when, for example, you already started completing something and it doesn't match the mounted share (i.e., if completing `cd .conf`, the `.thunderbird` folder doesn't start with `.conf` so `_path_files` shouldn't try to expand it). And indeed, without OMZ this specific case doesn't happen because the `case-insensitive` matching isn't there. Here's a trace of `_path_files` under `zsh -f`:

```console
$ zsh -f
% autoload -Uz compinit && compinit
% functions -t _path_files
% cd .con[TAB]
+_path_files:5> local splitchars
+_path_files:6> zstyle -s :completion::complete:cd:: file-split-chars splitchars
+_path_files:22> _have_glob_qual .con
...
+_path_files:452> tmp2=( '' )
+_path_files:454> [[ .con = (#b)*/(*) ]]
+_path_files:467> [[ -// = *[/f]* ]]
+_path_files:468> compfiles -p tmp1 accex '' ' ' '' fake '*(-/)'**
+_path_files:472> : tmp1: '.con*(-/)'  # this is a line I added to _path_files
+_path_files:473> tmp1=( .config )
...
```
Note the last three lines: the `compfiles` call doesn't get the `'m:{a-zA-Z}={A-Za-z} m:{a-zA-Z}={A-Za-z}'` argument which is responsible for the case-insensitive matching, and so the glob it returns (line 472) does begin with `.con` which is what I typed before completing. This means there's never a reason to `lstat` the `.thunderbird` folder. You can get this same behavior by disabling case-insensitive matching, which is using [the `CASE_SENSITIVE` ohmyzsh setting](https://github.com/ohmyzsh/ohmyzsh/wiki/Settings#case_sensitive):
```zsh
CASE_SENSITIVE=true
```

### Recap

So to recap, this issue seems to do with mounted directories which take a long time to return from an `lstat` call or to timeout altogether, so you can debug it like so:

1. Figure out where `_path_files` is: `ls -l ${^fpath}/_path_files(N)`
2. Edit it to add the line below, before the line that says `tmp1=( $~tmp1 ) 2>/dev/null`:
   ```zsh
   : tmp1: $tmp1
   ```
3. Restart the shell, then run `functions -t _path_files` to enable tracing of that function.
4. Try to complete the command that hangs and look at the globs in the `tmp1` variable (note that it is an array so there may be multiple values.
5. When the completion times out, or when you force quit the zsh process from another tab, try to locate the directory that's causing this hangup.
6. Optionally, disable case-insensitive completion to fix the corner case where you're not completing something that should match the faulty mount directory.

I'm going to close this now because we can't do anything else with it (we can't really fix an lstat call, that's up to you to fix slow mounts with the above process). But keep your information coming for other folks that encounter this issue in the future.

Thanks!

**Closed by mcornella** 2020-10-17 19:25 UTC
Labels: Topic: completion, performance

**Comment by smac89** [comment] 2021-01-26 08:33
I figured out the problem. I have a very large `/etc/hosts` file which is used to block ads, so the default behaviour for completing hosts seems to also involve reading from this file. I turned this off by adding the following to my `~/.zshrc` file:

```
zstyle ':completion:*:hosts' hosts
```

**Comment by adriandelgg** [comment] 2021-09-04 18:35
> @cmol
> I had the same issue with ssh completions. See if this blog post fixes it for you (it did for me):
> https://destinmoulton.com/blog/2018/how-to-disable-zsh-ssh-hosts-completion/

This fixed the issue for me. Thanks!

**Comment by keldian** [comment] 2022-09-14 04:04
I have a bit of a different experience. On a default ZSH setup on Ubuntu, I get a lockup when tabbing at e.g. `sudo ls /root/`. This no longer occurs after applying this old fix: https://www.victorquinn.com/solved-zsh-tab-completion-painfully-slow

However, installing oh-my-zsh reintroduces the issue.

**Comment by GiscardBiamby** [comment] 2024-07-16 05:00
Link above no longer works, here is one that works: https://destinmoulton.com/notes/howto/how-to-disable-zsh-ssh-hosts-completion/
