### ISSUE TITLE
NVM autoload and AutoEnv not coexisting together

### ISSUE THREAD

**Issue by sposmen** [ohmyzsh/ohmyzsh#10015] opened 2021-06-30 16:21 UTC
**Describe the bug**
A clear description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Enable `autoenv` and `nvm` (with `NVM_AUTOLOAD=1`)
2. Set some `.env`
3. Set a `.nvmrc` to a Node version
3. Load a terminal with the new configs
4. The error is shown
5. No autoenv variables set.

**Expected behavior**
Both loaders work fine together

**Screenshots and/or Recordings**
```bash
shasum: Now using node v16.2.0 (npm v7.13.0): No such file or directory
autoenv_source:.:6: no such file or directory: Now using node v16.2.0 (npm v7.13.0)
shasum: /.../.envReverting to nvm default version: No such file or directory
autoenv_source:.:6: no such file or directory: /.../.envReverting to nvm default version
```

**Self Check**
- Have you tried switching plugins order but sadly it didn't helped
- Using separately both plugins work as expected

**Desktop (please complete the following information):**

 - OS / Distro: macOS Big Sur
 - Latest ohmyzsh update?: Yes
 - ZSH Version: 5.8
 - Terminal emulator: iTerm2 and Rubymine (both same issue)

**Additional context**
Current active plugins config
`plugins=(git rake rails rbenv heroku docker docker-compose nvm node npm yarn autoenv)`

**Comment by carlosala** [comment] 2022-12-01 18:18
It's reproducible to me. Even though, it seems to be an issue with autoenv trying to execute the log from `nvm`. Closing as it's for `autoenv` project.

**Closed by carlosala** 2022-12-01 18:18 UTC
Labels: Bug, Area: plugin
