### ISSUE TITLE
NixOS package not up to speed with master for fzf

### ISSUE THREAD

**Issue by abctaylor** [ohmyzsh/ohmyzsh#9146] opened 2020-07-31 01:35 UTC
**Describe the bug**
fzf plugin enforces looking in `${fzf_base}/shell` on Nixos - the source code in `fzf.plugin.zsh` correctly has logic to avoid this but the nixos package has an `&& [[ -f etc/arch-release ]]` to only enforce this for Arch. It should not have this in the NixOS repository.

**To Reproduce**
1. Install the Nix fzf package and correctly point $FZF_BASE to its location (where you should find `completion.zsh`, `key-bindings.zsh`, etc)
2. Enable fzf plugin in `plugins=(... fzf ...)`
2. Open a zsh shell
3. You see it is trying to find a dir called `/shell` inside here, despite being in the correct directory!

**Expected behavior**
This shouldn't happen; it looks like we just need to update the NixOS package which is clearly diff to what's in git.

**Screenshots and/or Recordings**
![image](https://user-images.githubusercontent.com/30197206/88990395-bed94b00-d2d5-11ea-97fe-55b0205d9f6a.png)

**Desktop**
 - OS / Distro: NixOs 20.03.2611 (Markhor)
 - Latest ohmyzsh update?: latest from NixOS ;)
 - ZSH Version: 5.7.1
 - Terminal emulator: xterm

**Comment by scolobb** [comment] 2020-08-01 07:23
Hi @abctaylor . I cannot reproduce this behavior while running off the `nixos-unstable` channel.  Here is what I see in `fzf.plugin.zsh` on my computer:

```shell
    if [[ -d "${fzf_base}" ]]; then
        # Fix fzf shell directory for Arch Linux, NixOS or Void Linux packages
        if [[ ! -d "${fzf_base}/shell" ]]; then
...
```

This is also exactly what appears here: https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/fzf/fzf.plugin.zsh#L34-L36

Also, the Nix package has been updated on July 30 by @NeQuissimus: https://github.com/NixOS/nixpkgs/blob/master/pkgs/shells/zsh/oh-my-zsh/default.nix#L7-L9

I don't exactly follow NixOS version numbers since I'm running unstable anyway, but it looks like you are not using the latest Nixpkgs tree.

**Comment by mcornella** [comment] 2020-08-01 10:12
Thanks @scolobb for the thorough reply. Closing this then.

**Closed by mcornella** 2020-08-01 10:12 UTC
Labels: Type: support
