### ISSUE TITLE
Parse error in check-for-upgrade.sh

### ISSUE THREAD

**Issue by levinsamuel** [ohmyzsh/ohmyzsh#10485] opened 2021-12-06 16:59 UTC
### Describe the bug

I get this error when running the script in the title:
```
➜  .oh-my-zsh git:(master) . tools/check_for_upgrade.sh 
tools/check_for_upgrade.sh:35: parse error near `cd'
tools/check_for_upgrade.sh:71: parse error near `remote_head=$('
```
This started happening for me about two months ago, if I had to guess.

### Steps to reproduce

I reproduce the bug simply by running the script. I'm on Mac OS Big Sur 11.2.3.

### Expected behavior

Script should not have a parse error?

### OS / Linux distribution

Mac OS 11.2.3

### Zsh version

5.8

### Oh My Zsh version

master (841f3cb0)

### Terminal emulator

Mac Terminal.app

**Comment by mcornella** [comment] 2021-12-13 10:39
Can you check if that file contains CR? `file tools/check_for_upgrade.sh` should say
```
tools/check_for_upgrade.sh: ASCII text
```

If it says 
```
tools/check_for_upgrade.sh: ASCII text, with CR line terminators
```
you might have a wrong `core.autocrlf` or `core.eol` value.

**Comment by levinsamuel** [comment] 2021-12-13 20:53
> Can you check if that file contains CR? `file tools/check_for_upgrade.sh` should say
> 
> ```
> tools/check_for_upgrade.sh: ASCII text
> ```
> 
> If it says
> 
> ```
> tools/check_for_upgrade.sh: ASCII text, with CR line terminators
> ```
> 
> you might have a wrong git config `core.autocrlf` or `core.eol` value.

```
$ file ~/.oh-my-zsh/tools/check_for_upgrade.sh 
/Users/sam/.oh-my-zsh/tools/check_for_upgrade.sh: ASCII text
```

**Comment by mcornella** [comment] 2021-12-13 21:23
Can you source it with xtrace enabled and post the output?
```zsh
{ set -xv; . tools/check_for_upgrade.sh } always { set +xv }
```

**Comment by levinsamuel** [comment] 2021-12-13 22:59
```
$ { set -xv; . tools/check_for_upgrade.sh } always { set +xv }

+-zsh:4> . tools/check_for_upgrade.sh
# Migrate .zsh-update file to $ZSH_CACHE_DIR
if [[ -f ~/.zsh-update && ! -f "${ZSH_CACHE_DIR}/.zsh-update" ]]; then
  mv ~/.zsh-update "${ZSH_CACHE_DIR}/.zsh-update"
fi
+tools/check_for_upgrade.sh:2> [[ -f /Users/sam/.zsh-update ]]

# Get user's update preferences
#
# Supported update modes:
# - prompt (default): the user is asked before updating when it's time to update
# - auto: the update is performed automatically when it's time
# - reminder: a reminder is shown to the user when it's time to update
# - disabled: automatic update is turned off
zstyle -s ':omz:update' mode update_mode || update_mode=prompt
+tools/check_for_upgrade.sh:13> zstyle -s :omz:update mode update_mode
+tools/check_for_upgrade.sh:13> update_mode=prompt 

# Support old-style settings
[[ "$DISABLE_UPDATE_PROMPT" != true ]] || update_mode=auto
+tools/check_for_upgrade.sh:16> [[ '' != true ]]
[[ "$DISABLE_AUTO_UPDATE" != true ]] || update_mode=disabled
+tools/check_for_upgrade.sh:17> [[ true != true ]]
+tools/check_for_upgrade.sh:17> update_mode=disabled 

# Cancel update if:
# - the automatic update is disabled.
# - the current user doesn't have write permissions nor owns the $ZSH directory.
# - git is unavailable on the system.
if [[ "$update_mode" = disabled ]] \
   || [[ ! -w "$ZSH" || ! -O "$ZSH" ]] \
   || ! command -v git &>/dev/null; then
  unset update_mode
  return
fi
+tools/check_for_upgrade.sh:23> [[ disabled = disabled ]]
+tools/check_for_upgrade.sh:26> unset update_mode
+tools/check_for_upgrade.sh:27> return
+-zsh:4> set +xv
```

**Comment by mcornella** [comment] 2021-12-14 14:35
Looks like you disabled the automatic update, try it again after doing `unset DISABLE_AUTO_UPDATE`.

**Comment by levinsamuel** [comment] 2021-12-17 00:33
I see, here: 
```
+-zsh:8> unset DISABLE_AUTO_UPDATE
+-zsh:8> . tools/check_for_upgrade.sh
# Migrate .zsh-update file to $ZSH_CACHE_DIR
if [[ -f ~/.zsh-update && ! -f "${ZSH_CACHE_DIR}/.zsh-update" ]]; then
  mv ~/.zsh-update "${ZSH_CACHE_DIR}/.zsh-update"
fi
+tools/check_for_upgrade.sh:2> [[ -f /Users/sam/.zsh-update ]]

# Get user's update preferences
#
# Supported update modes:
# - prompt (default): the user is asked before updating when it's time to update
# - auto: the update is performed automatically when it's time
# - reminder: a reminder is shown to the user when it's time to update
# - disabled: automatic update is turned off
zstyle -s ':omz:update' mode update_mode || update_mode=prompt
+tools/check_for_upgrade.sh:13> zstyle -s :omz:update mode update_mode
+tools/check_for_upgrade.sh:13> update_mode=prompt 

# Support old-style settings
[[ "$DISABLE_UPDATE_PROMPT" != true ]] || update_mode=auto
+tools/check_for_upgrade.sh:16> [[ '' != true ]]
[[ "$DISABLE_AUTO_UPDATE" != true ]] || update_mode=disabled
+tools/check_for_upgrade.sh:17> [[ '' != true ]]

# Cancel update if:
# - the automatic update is disabled.
# - the current user doesn't have write permissions nor owns the $ZSH directory.
# - git is unavailable on the system.
if [[ "$update_mode" = disabled ]] \
   || [[ ! -w "$ZSH" || ! -O "$ZSH" ]] \
   || ! command -v git &>/dev/null; then
  unset update_mode
  return
fi
+tools/check_for_upgrade.sh:23> [[ prompt = disabled ]]
+tools/check_for_upgrade.sh:24> [[ ! -w /Users/sam/.oh-my-zsh || ! -O /Users/sam/.oh-my-zsh ]]
+tools/check_for_upgrade.sh:25> command -v git

function current_epoch() {
  zmodload zsh/datetime
  echo $(( EPOCHSECONDS / 60 / 60 / 24 ))
}

function is_update_available() {
  local branch
  branch=${"$(cd "$ZSH"; git config --local oh-my-zsh.branch)":-master}

  local remote remote_url remote_repo
  remote=${"$(cd "$ZSH"; git config --local oh-my-zsh.remote)":-origin}
  remote_url=$(cd "$ZSH"; git config remote.$remote.url)

  local repo
  case "$remote_url" in
  https://github.com/*) repo=${${remote_url#https://github.com/}%.git} ;;
  git@github.com:*) repo=${${remote_url#git@github.com:}%.git} ;;
  *)
    # If the remote is not using GitHub we can't check for updates
    # Let's assume there are updates
    return 0 ;;
  esac

  # If the remote repo is not the official one, let's assume there are updates available
  [[ "$repo" = ohmyzsh/ohmyzsh ]] || return 0
  local api_url="https://api.github.com/repos/${repo}/commits/${branch}"

  # Get local HEAD. If this fails assume there are updates
  local local_head
  local_head=$(cd "$ZSH"; git rev-parse $branch 2>/dev/null) || return 0

  # Get remote HEAD. If no suitable command is found assume there are updates
  # On any other error, skip the update (connection may be down)
  local remote_head
  remote_head=$(
    if (( ${+commands[curl]} )); then
      curl -fsSL -H 'Accept: application/vnd.github.v3.sha' $api_url 2>/dev/null
    elif (( ${+commands[wget]} )); then
      wget -O- --header='Accept: application/vnd.github.v3.sha' $api_url 2>/dev/null
    elif (( ${+commands[fetch]} )); then
      HTTP_ACCEPT='Accept: application/vnd.github.v3.sha' fetch -o - $api_url 2>/dev/null
tools/check_for_upgrade.sh:35: parse error near `cd'
tools/check_for_upgrade.sh:71: parse error near `remote_head=$('
+-zsh:8> set +xv
```

**Comment by mcornella** [comment] 2021-12-17 12:31
I can't see anything wrong, perhaps the problem is further down the file. Can you post it here?

**Comment by mcornella** [comment] 2021-12-20 12:34
A `diff` shows that it is the same content. Perhaps there's a hidden non-ASCII character in there?

Does `git status` show anything inside the folder? If not, can you send a hexdump of the file?
You can quickly copy a hexdump of the file like so, provided you have `hexdump` installed: `hd tools/check_for_upgrade.sh | clipcopy`

**Comment by mcornella** [comment] 2021-12-29 10:45
I'm going to close this because I cannot reproduce this. Reopen if you want and reply to https://github.com/ohmyzsh/ohmyzsh/issues/10485#issuecomment-997885797. If it still happens and you want a quick fix, you can delete the `$ZSH` folder and reclone the repository into it, provided you don't have custom files in `$ZSH/custom`:

```zsh
rm -rf "$ZSH"
git clone --depth 1 https://github.com/ohmyzsh/ohmyzsh "$ZSH"
```

**Closed by mcornella** 2021-12-29 10:45 UTC
Labels: Platform: macOS, Bug, Area: updater
