### ISSUE TITLE
Compound emojis rendered as separate components

### ISSUE THREAD

**Issue by AlienKevin** [ohmyzsh/ohmyzsh#10550] opened 2022-01-01 17:37 UTC
### Describe the bug

Compound emojis like 👩‍🔬 woman scientist consisting of three Unicode code points 👩U+1F469 ‍U+200D 🔬U+1F52C is displayed as 👩<200d>🔬 in zsh.

### Steps to reproduce

font: tried both macOS terminal default font and Source Code Pro
emoji font: system default Apple Color Emoji

On my system, compound emojis like👩‍🔬 and 👨‍👨‍👧‍👧 etc are displayed normally in VS Code and web pages. You can reproduce this issue in zsh by pasting the woman scientist 👩‍🔬 emoji onto the terminal and observe that it automatically expands into 👩<200d>🔬.

### Expected behavior

Should be displayed as a whole, rather than decomposed into individual components and a Zero Width Joiner.

### Screenshots and recordings

Terminal.app with macOS default terminal font:
<img width="411" alt="截圖 2022-01-01 12 33 39" src="https://user-images.githubusercontent.com/22850071/147856526-21ebf0e0-c3ad-473a-ae7a-56ac450fd4b4.png">

VSCode terminal with Source Code Pro font:
<img width="460" alt="截圖 2022-01-01 12 34 08" src="https://user-images.githubusercontent.com/22850071/147856576-dc25f9d2-d5a5-480f-933f-4631deb8b741.png">

iTerm (fresh install):
<img width="348" alt="截圖 2022-01-01 12 34 25" src="https://user-images.githubusercontent.com/22850071/147856599-a4a3370e-eef5-4692-801e-78700894c686.png">

### OS / Linux distribution

macOS Monterey 12.1

### Zsh version

5.8

### Terminal emulator

tried both Terminal.app and iTerm2

**Comment by mcornella** [comment] 2022-01-01 18:07
I think that's a terminal emulator issue, the shell has nothing to do with the rendering. For what it's worth, GNOME Terminal has the same problem ([looks like libvte should handle that](https://github.com/elementary/terminal/issues/558#issuecomment-756467348) in this case).

Looks like for `Terminal.app` you should [submit the bug report here](https://discussions.apple.com/welcome) (not a bug tracker per se though).

For iTerm2 looks like the output is handled correctly, but not when pasted into the command line:

![Screenshot_macOS_2022-01-01_19:01:24](https://user-images.githubusercontent.com/1441704/147857184-f39b2f22-757d-4586-a420-ec24e6313c1a.png)

The latter might be due to Zsh's formatting, you should ask in the [mailing list](https://zsh.org/mla).

You can specify Unicode codepoints with `$'\U<codepoint>', so you can more easily copy-paste your emoji example like this:
```zsh
echo $'\U1F469\U200D\U1F52C'
```

Since this is not an Oh My Zsh bug I'm going to close this, but feel free to post an update to this issue if you find a solution / submit a bug report elsewhere.

Happy 2022!

**Comment by rwmitchell** [comment] 2022-01-01 18:08
It does work in bash, must be a zsh thing.

**Closed by mcornella** 2022-01-01 18:07 UTC

**Comment by mcornella** [comment] 2022-01-01 18:13
Yeah the rendered output works in Terminal.app and iTerm2, just checked. I think the only problem is in the command line, where it detects `$'\U200D'` as a special character and renders it like that. So it is a zsh issue.

**Comment by AlienKevin** [comment] 2022-01-01 21:29
Happy new year! I also encountered this issue when printing to the console through Rust. Though it looks like the Zero Width Joiner is simply not displayed and only component emojis are shown. I wonder if this issue is related to zsh or the terminal?
