### ISSUE TITLE
Division by 0 error after recent update

### ISSUE THREAD

**Issue by tvanantwerp** [ohmyzsh/ohmyzsh#10213] opened 2021-09-24 14:15 UTC
### Describe the bug

It appears that [this](https://github.com/ohmyzsh/ohmyzsh/commit/d2269180b074263f4a0d3df3f9de15a1abae8110#diff-316fee2ff6feccb3a6fb7ebed95af23630624ba5cb7bca42c3f0b9fddbe9085e) recent update is causing problems with my system. When I run simple commands like a git commit or git push, they fail with this error (modified to use `~` to hide my full path):

```
~/.oh-my-zsh/oh-my-zsh.sh: line 17: (Ie)~/.oh-my-zsh/cache/completions: division by 0 (error token is "~/.oh-my-zsh/cache/completions")
```

### Steps to reproduce

1. On macOS, update to most recent version.
2. Try to commit something to a git repo or to push to a remote origin

### Expected behavior

Should not produce an error.

### OS / Distro

macOS 11.6

### Zsh version

5.8

### Terminal emulator

iTerm2

### Additional context

Using powerlevel9k theme.

Using one custom plugin for switching node versions with nvm on entering directories:

```
autoload -U add-zsh-hook
load-nvmrc() {
  if ! type "nvm" > /dev/null; then
    unset -f ${NODE_GLOBALS} || true;
    load_nvm
  fi
  local node_version="$(nvm version)"
  local nvmrc_path="$(nvm_find_nvmrc)"

  if [ -n "$nvmrc_path" ]; then
    local nvmrc_node_version=$(nvm version "$(cat "${nvmrc_path}")")

    if [ "$nvmrc_node_version" = "N/A" ]; then
      nvm install
    elif [ "$nvmrc_node_version" != "$node_version" ]; then
      nvm use
    fi
  elif [ "$node_version" != "$(nvm version default)" ]; then
    echo "Reverting to nvm default version"
    nvm use default
  fi
}
add-zsh-hook chpwd load-nvmrc
load-nvmrc
```

Cleaned up copy of `.zshrc` file:

```
export TERM="xterm-256color"

export ZSH=~/.oh-my-zsh

ZSH_THEME="powerlevel9k/powerlevel9k"

# Initialize nvm before custom nvm switch plugin
export NVM_DIR="$HOME/.nvm"
  . "/usr/local/opt/nvm/nvm.sh"

plugins=(
  brew
  git
  osx
  pyenv
  themes
  zsh-auto-nvm-use
)

source $ZSH/oh-my-zsh.sh

eval "$(pyenv init -)"

# Powerlevel9k config
POWERLEVEL9K_MODE='nerdfont-complete'
POWERLEVEL9K_SHORTEN_DIR_LENGTH=3
POWERLEVEL9K_SHORTEN_STRATEGY='truncate_from_right'
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=''
POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=''
POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR=''
POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR=''
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX='%F{blue}\u256D\uf07c %F{white}'
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX='%F{blue}\u2570\uf460%F{white} '
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(root_indicator dir dir_writable_joined)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(command_execution_time vcs
                                    background_jobs_joined time_joined)
POWERLEVEL9K_VCS_CLEAN_BACKGROUND='clear'
POWERLEVEL9K_VCS_CLEAN_FOREGROUND='green'
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='clear'
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='yellow'
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='clear'
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='yellow'
POWERLEVEL9K_DIR_HOME_BACKGROUND='clear'
POWERLEVEL9K_DIR_HOME_FOREGROUND='blue'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND='clear'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND='blue'
POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_BACKGROUND='clear'
POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_FOREGROUND='red'
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND='clear'
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND='white'
POWERLEVEL9K_ROOT_INDICATOR_BACKGROUND='red'
POWERLEVEL9K_ROOT_INDICATOR_FOREGROUND='white'
POWERLEVEL9K_STATUS_OK_BACKGROUND='clear'
POWERLEVEL9K_STATUS_OK_FOREGROUND='green'
POWERLEVEL9K_STATUS_ERROR_BACKGROUND='clear'
POWERLEVEL9K_STATUS_ERROR_FOREGROUND='red'
POWERLEVEL9K_TIME_FORMAT='%D{\uf073  %d.%m.%y \uf017 %T}' #  Jun 15  09:32
POWERLEVEL9K_TIME_BACKGROUND='clear'
POWERLEVEL9K_TIME_FOREGROUND='cyan'
POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND='clear'
POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND='magenta'
POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND='clear'
POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND='green'
POWERLEVEL9K_USER_ICON='\uf415' # 
POWERLEVEL9K_ROOT_ICON='\u26a1' # ⚡

# Aliases

# Syntax highlighting
source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
# Auto-complete
source /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh

export PATH="/usr/local/sbin:$PATH"

neofetch

# tabtab source for serverless package
# uninstall by removing these lines or running `tabtab uninstall serverless`
[[ -f ~/.config/yarn/global/node_modules/tabtab/.completions/serverless.zsh ]] && . ~/.config/yarn/global/node_modules/tabtab/.completions/serverless.zsh
# tabtab source for sls package
# uninstall by removing these lines or running `tabtab uninstall sls`
[[ -f ~/.config/yarn/global/node_modules/tabtab/.completions/sls.zsh ]] && . ~/.config/yarn/global/node_modules/tabtab/.completions/sls.zsh
# tabtab source for slss package
# uninstall by removing these lines or running `tabtab uninstall slss`
[[ -f ~/.config/yarn/global/node_modules/tabtab/.completions/slss.zsh ]] && . ~/.config/yarn/global/node_modules/tabtab/.completions/slss.zsh

# Flutter

export PATH="$PATH:~/flutter/bin"

# Check the whois of a domain or form a URL.
# @usage: whois google.com
# @usage: whois https://google.com
function whois() {
    local domain=$(echo "$1" | awk -F/ '{print $3}') # get domain from URL
    if [ -z $domain ] ; then
        domain=$1
    fi
    echo "Getting whois record for: $domain …"

    # Avoid recursion
                    # This is the best whois server AFAIK.
                                                # Strip extra fluff
    /usr/bin/whois -h whois.internic.net $domain | sed '/NOTICE:/q'
}
```

**Comment by mcornella** [comment] 2021-09-24 14:51
Thanks for the bug report, it should be fixed now (try `omz update`).

**Comment by tvanantwerp** [comment] 2021-09-24 15:32
Alas, it persists...

`/Users/me/.oh-my-zsh/oh-my-zsh.sh: line 17: (Ie)/Users/me/.oh-my-zsh/cache/completions: division by 0 (error token is "/me/.oh-my-zsh/cache/completions")`

**Comment by SalithaUCSC** [comment] 2021-09-27 05:51
The same issue is happening on Linux too. This was raised when I try to use `git commit`.
```
/home/<me>/.oh-my-zsh/cache/completions: division by 0 (error token is "home/<me>/.oh-my-zsh/cache/completions")
./node_modules/pre-commit/hook: line 48: : command not found
```

**Comment by mcornella** [comment] 2021-09-27 07:58
> Alas, it persists...
> 
> `/Users/me/.oh-my-zsh/oh-my-zsh.sh: line 17: (Ie)/Users/me/.oh-my-zsh/cache/completions: division by 0 (error token is "/me/.oh-my-zsh/cache/completions")`

What's your setup for `git push` or `git commit` (i.e. what are the hooks doing?) so I can try to reproduce this.

**Comment by tvanantwerp** [comment] 2021-09-27 14:13
I've had it happen in two different JS apps, one in Angular and one in React, both using husky for managing git hooks.

There's not much fancy that they are doing, but here it is:

## App 1

`pre-push` just runs a bunch of tests using jest, called from a script with yarn.
```sh
#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

yarn test:all
```

`pre-commit` runs a command that just lints any staged files.
```sh
#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

yarn precommit
```

## App 2

Husky does a little more here. It also does pre-commit linting, as well as checking against the package `commitlint` for formatting of the commit message.

```json
  "husky": {
    "hooks": {
      "commit-msg": "npx --no-install commitlint --verbose --edit $1",
      "pre-push": "hooks/pre-push.sh $HUSKY_GIT_STDIN",
      "pre-commit": "lint-staged"
    }
  }
```

`pre-push`  just warns you if you're trying to push to a predefined protected branch.
```
#!/bin/bash

protected_branch='refs/heads/develop'
remote_branch=$3

echo $remote_branch
echo $protected_branch

if [ $protected_branch = "$remote_branch" ]
then
    read -p "You're about to push develop, is that what you intended? [y|n] " -n 1 -r < /dev/tty
    echo
    if echo $REPLY | grep -E '^[Yy]$' > /dev/null
    then
        exit 0 # push will execute
    fi
    exit 1 # push will not execute
else
    exit 0 # push will execute
fi
```

**Comment by pauldiloreto** [comment] 2021-09-27 20:46
I don't know if this helps pin point the issue at all, but I've been able to consistently reproduce this issue when running with Tmux.

Currently running Ubuntu in WSL, using Windows Terminal. Oh-my-zsh runs fine normally, but every time I use Tmux, it throws this issue when sourcing my `~/.zshrc`. When I manually call `source ~/.zshrc` inside tmux, I see this division by 0 error every time.

**Comment by SunbowLiu** [comment] 2021-09-28 06:31
Back to commit 450acc0113b114352ce3b94870fe63fc461844bd works.

**Comment by mcornella** [comment] 2021-09-28 07:59
> I've had it happen in two different JS apps, one in Angular and one in React, both using husky for managing git hooks.
> 
> There's not much fancy that they are doing, but here it is:
> 
> ## App 1
> `pre-push` just runs a bunch of tests using jest, called from a script with yarn.
> 
> ```shell
> #!/bin/sh
> . "$(dirname "$0")/_/husky.sh"
> 
> yarn test:all
> ```
> 
> `pre-commit` runs a command that just lints any staged files.
> 
> ```shell
> #!/bin/sh
> . "$(dirname "$0")/_/husky.sh"
> 
> yarn precommit
> ```
> 
> ## App 2
> Husky does a little more here. It also does pre-commit linting, as well as checking against the package `commitlint` for formatting of the commit message.
> 
> ```json
>   "husky": {
>     "hooks": {
>       "commit-msg": "npx --no-install commitlint --verbose --edit $1",
>       "pre-push": "hooks/pre-push.sh $HUSKY_GIT_STDIN",
>       "pre-commit": "lint-staged"
>     }
>   }
> ```
> 
> `pre-push` just warns you if you're trying to push to a predefined protected branch.
> 
> ```
> #!/bin/bash
> 
> protected_branch='refs/heads/develop'
> remote_branch=$3
> 
> echo $remote_branch
> echo $protected_branch
> 
> if [ $protected_branch = "$remote_branch" ]
> then
>     read -p "You're about to push develop, is that what you intended? [y|n] " -n 1 -r < /dev/tty
>     echo
>     if echo $REPLY | grep -E '^[Yy]$' > /dev/null
>     then
>         exit 0 # push will execute
>     fi
>     exit 1 # push will not execute
> else
>     exit 0 # push will execute
> fi
> ```

These scripts either call `sh` or `bash`, are you calling zsh from `.bashrc`?

**Comment by mcornella** [comment] 2021-09-28 09:33
33c86fe80b5d838b3d3dd454c35aa94f4a38b3f7 detects this bad configuration and prints an error message when it happens. You need to fix your configuration so that neither `sh` nor `bash` are running `oh-my-zsh.sh`.

**Closed by mcornella** 2021-09-28 09:33 UTC
Labels: Bug

**Comment by tvanantwerp** [comment] 2021-09-29 19:28
Anyone know why `sh` and `bash` would be trying to run `oh-my-zsh.sh`? I don't see anything in `.bashrc`, `.bash_profile`, etc., which references it.

Trying to `git commit` now is much worse—I get this lovely output at every stage of the git hooks firing. At least the command works, so I guess I'm happy about that...

```
ERROR: Oh My Zsh can't be loaded from: .git/hooks/commit-msg. You need to run zsh instead.
/usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh: line 31: alias: -L: invalid option
alias: usage: alias [-p] [name[=value] ... ]
/usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh: line 36: unalias: -m: invalid option
unalias: usage: unalias [-a] name [name ...]
/usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh: line 39: 0=${(%):-%N}: bad substitution
/usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh: line 42: /.version: No such file or directory
/usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh: line 42: typeset: -g: invalid option
typeset: usage: typeset [-afFirtx] [-p] name[=value] ...
/usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh: line 43: /.revision-hash: No such file or directory
/usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh: line 43: typeset: -g: invalid option
typeset: usage: typeset [-afFirtx] [-p] name[=value] ...
/usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh: line 58: autoload: command not found
/usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh: line 59: is-at-least: command not found
/usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh: line 62: typeset: -g: invalid option
typeset: usage: typeset [-afFirtx] [-p] name[=value] ...
/usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh: line 66: typeset: -g: invalid option
typeset: usage: typeset [-afFirtx] [-p] name[=value] ...
/usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh: line 81: syntax error near unexpected token `}'
/usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh: line 81: `  if [[ $WIDGET == zle-isearch-update ]] && { $zsh_highlight__pat_static_bug || ! (( $+ISEARCHMATCH_ACTIVE )) }; then'
/usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh: line 35:  ! ${+ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE} : bad substitution
/usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh: line 38:  ! ${+ZSH_AUTOSUGGEST_ORIGINAL_WIDGET_PREFIX} : bad substitution
/usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh: line 42:  ! ${+ZSH_AUTOSUGGEST_STRATEGY} : bad substitution
/usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh: line 45:  ! ${+ZSH_AUTOSUGGEST_CLEAR_WIDGETS} : bad substitution
/usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh: line 48:  ! ${+ZSH_AUTOSUGGEST_ACCEPT_WIDGETS} : bad substitution
/usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh: line 51:  ! ${+ZSH_AUTOSUGGEST_EXECUTE_WIDGETS} : bad substitution
/usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh: line 54:  ! ${+ZSH_AUTOSUGGEST_PARTIAL_ACCEPT_WIDGETS} : bad substitution
/usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh: line 57:  ! ${+ZSH_AUTOSUGGEST_IGNORE_WIDGETS} : bad substitution
/usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh: line 60:  ! ${+ZSH_AUTOSUGGEST_COMPLETIONS_PTY_NAME} : bad substitution
/usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh: line 95: syntax error near unexpected token `('
/usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh: line 95: `		user:_zsh_autosuggest_(bound|orig)_*)'
```

**Comment by mcornella** [comment] 2021-09-30 10:49
Test PR #10234 with `omz pr test 10234` and try to reproduce the error again. It should show the correct calling shell and its process tree, so you can debug what steps are run until OMZ is sourced.

**Comment by tvanantwerp** [comment] 2021-09-30 18:15
Ok, I've done that, but I'm not really sure what to make of the output. I tried in both iTerm2 (my default) and the macOS Terminal and the results are slightly different, but with the same error.

## iTerm2

```
 PPID   PID COMMAND
    1   382 /Applications/iTerm.app/Contents/MacOS/iTerm2
66325 22748 git commit -m fix: test do not push
22748 22749 /bin/sh .git/hooks/pre-commit
  382 66323 /Applications/iTerm.app/Contents/MacOS/iTerm2 --server login -fqp myUsername
66323 66324 login -fqp myUsername
66324 66325 -zsh
```

## Terminal

```
 PPID   PID COMMAND
    1 24394 /System/Applications/Utilities/Terminal.app/Contents/MacOS/Terminal
24394 24395 login -pf myUsername
24395 24396 -zsh
24396 25687 git commit -m fix: test do not push
25687 25688 /bin/sh .git/hooks/pre-commit
```

**Comment by mcornella** [comment] 2021-10-01 09:51
> ## iTerm2
> ```
>  PPID   PID COMMAND
>     1   382 /Applications/iTerm.app/Contents/MacOS/iTerm2
> 66325 22748 git commit -m fix: test do not push
> 22748 22749 /bin/sh .git/hooks/pre-commit
>   382 66323 /Applications/iTerm.app/Contents/MacOS/iTerm2 --server login -fqp myUsername
> 66323 66324 login -fqp myUsername
> 66324 66325 -zsh
> ```

This one is weird because child processes have a lower PID than parents, it should be the same as the Terminal one. What this means is that the culprit is `.git/hooks/pre-commit` and you should figure out why it's sourcing `oh-my-zsh.sh` from that file.

You can add `set -x` to enable trace mode in the `.git/hooks/pre-commit` file, and following the execution trail until it gets to `oh-my-zsh.sh`.

**Comment by tvanantwerp** [comment] 2021-10-01 17:30
Thanks! I was finally able to figure out what was going wrong.

The `.huskyrc` file in my user root folder had `source .zshrc` inside of it. Presumably I put it in there, though I have neither memory of doing it nor the faintest idea why I would have done. I don't even recall creating that dotfile. Sharing details of my stupidity here, in case anyone else finds this issue some day because they did it too.

Thanks so much for all the help, @mcornella 👍
