### ISSUE TITLE
command line jump to next line automatically in  repository folder

### ISSUE THREAD

**Issue by appleyuchi** [ohmyzsh/ohmyzsh#9105] opened 2020-07-12 12:47 UTC
**Describe the bug**
command line jump to next line automatically

**To Reproduce**
Steps to reproduce the behavior, for example:
①set
```
TMOUT=1
TRAPALRM () { zle reset-prompt }
```
in ~/.zshrc
②anaconda configuration(see the end of this post please)
③open the terminal in any folder contains `.git`

**Expected behavior**
the command remain unchange except the clock

**Screenshots and/or Recordings**

https://asciinema.org/a/DOq78og1q0ZCdZW0c6RlOEDDe

**Self Check**
Check |  result|    
-|-
Have you tried reaching out on the [Discord server](discord.gg/ohmyzsh)? <br>This can help cut down on filling up issues. We always have a few people online that are in a variety of timezones that are willing to help you! | page not found | 5 |
Also searching existing [GitHub Issues](https://github.com/ohmyzsh/ohmyzsh/issues?q=)<br>might help you get quicker support | I did not find relevant issue

**Desktop (please complete the following information):**

Check |  result|    
-|-
OS / Distro: [e.g. Arch Linux, macOS]|Ubuntu20.04|
Latest ohmyzsh Update?|Yes|
ZSH Version|5.8-3ubuntu1
Terminal emulator|xfce4-terminal

**Additional context**

configuration file | link|    
-|-
bullet-train.zsh-theme|https://paste.ubuntu.com/p/BpYPJtW2wg/
~/.zshrc|https://paste.ubuntu.com/p/nzHtZY2Rd8/

**Comment by mcornella** [comment] 2020-07-12 15:40
I can reproduce this when the `locale` set is not found or isn't UTF-8. Run `locale -a` for a list of valid locales and `locale` for the current setup, and post both.

**Comment by mcornella** [comment] 2020-07-12 15:56
BTW, this is the only thing necessary to reproduce the problem:

- `.zshrc`:
```zsh
autoload -Uz colors && colors
setopt promptsubst

source bullet-train.zsh-theme

export LANG=C LC_ALL=C

TMOUT=1
TRAPALRM () { zle reset-prompt }
```

- `bullet-train.zsh-theme`: same as above (https://paste.ubuntu.com/p/BpYPJtW2wg/)

Then, resize the terminal until the prompt barely fits in one line.

**Comment by appleyuchi** [comment] 2020-07-13 01:45
$ locale
LANG=en_US.UTF-8
LANGUAGE=zh_HK
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8

**Comment by appleyuchi** [comment] 2020-07-13 01:47
As you said:"this is not our issue"
sorry to propose such a problem in unproper place.
could you tell me how to solve it
or should I post it in stackoverflow?



I just want to keep the dynamic clock in terminal 
could you tell me how to configure it to fix this bug?
Thanks for your help~!

**Comment by mcornella** [comment] 2020-07-13 15:35
> As you said:"this is not our issue"
> sorry to propose such a problem in unproper place.
> could you tell me how to solve it

Hey don't worry, the label is just there for statistics purposes. You didn't provide the output of `locale -a`!

**Comment by appleyuchi** [comment] 2020-07-13 15:40
apologise for my carelessness.
could you help me have a look at it again?
Thanks~!
-------------------------------------------------
$ locale -a
C
C.UTF-8
en_AG
en_AG.utf8
en_AU.utf8
en_BW.utf8
en_CA.utf8
en_DK.utf8
en_GB.utf8
en_HK.utf8
en_IE.utf8
en_IL
en_IL.utf8
en_IN
en_IN.utf8
en_NG
en_NG.utf8
en_NZ.utf8
en_PH.utf8
en_SG.utf8
en_US.utf8
en_ZA.utf8
en_ZM
en_ZM.utf8
en_ZW.utf8
es_CU.utf8
POSIX
zh_CN.utf8
zh_HK.utf8
zh_SG.utf8
zh_TW.utf8

**Comment by appleyuchi** [comment] 2020-07-13 15:56
And I post issue in this issue
https://github.com/caiogondim/bullet-train.zsh/issues/324
but no reply。。。。

**Comment by mcornella** [comment] 2020-07-13 17:00
Don't use tables for formatting output, you can use codeblocks like so:
<pre>
```
text
```
</pre>

As per your issue, try running `export LANG=en_US.utf8 LANGUAGE= LC_ALL=en_US.utf8` and checking if the problem still happens.

**Comment by appleyuchi** [comment] 2020-07-14 00:56
Thanks for your replies~!
I set
`export LANG=en_US.utf8`
`export LANGUAGE= en_US.utf8`
`export LC_ALL=en_US.utf8`
in ~/.zshrc
save and close
and **open a new Terminal to refresh the above setting.**
but the phenomenon remains

**Comment by appleyuchi** [comment] 2020-07-14 01:10
Is this bug due to the `git` part in theme file?

**Comment by appleyuchi** [comment] 2020-07-15 05:20
could you help me have a look it again?
Thanks

**Comment by mcornella** [comment] 2020-09-04 20:26
Hi @appleyuchi, since this is a theme bug and https://github.com/caiogondim/bullet-train.zsh/issues/324 is already filed, I'm closing this. I hope you find a solution.

**Closed by mcornella** 2020-09-04 20:26 UTC
Labels: Area: theme, Status: not our issue, Type: support
