### ISSUE TITLE
iconv: iconv_open(, -t): Invalid argument Error converting string from  to UTF-8

### ISSUE THREAD

**Issue by johnakash** [ohmyzsh/ohmyzsh#12455] opened 2024-05-27 03:27 UTC
### Describe the bug

I am getting an error whenever I am opening iTerm2. I tried to reinstall, but even after that, I am getting the same error.
```
iconv: iconv_open(, -t): Invalid argument
Error converting string from  to UTF-8
```

### Steps to reproduce

Just open the iterm2 console, and this error will show up. 

### Expected behavior

Normal console without error message. 

### OS / Linux distribution

Mac 14.5

### Zsh version

5.9

### Terminal emulator

iTersm2

### If using WSL on Windows, which version of WSL

None

**Comment by nodejh** [comment] 2024-05-27 03:41
I have the same question.
<img width="973" alt="image" src="https://github.com/ohmyzsh/ohmyzsh/assets/10287125/92c272f3-1a63-4804-83df-b3a13980e452">

**Comment by carlosala** [comment] 2024-05-27 06:16
Duplicate of #12444

**Closed** 2024-05-27 06:16 UTC

**Comment by fdwilogo** [comment] 2024-06-08 08:39
Somebody got this issue before and the solution is here:

https://github.com/ohmyzsh/ohmyzsh/issues/11645#issuecomment-1884685602
or
https://github.com/ohmyzsh/ohmyzsh/issues/11645#issuecomment-2124526554

I did that and it fixed the problem for me

**Comment by nikhilkumar12161** [comment] 2024-06-29 04:39
To fix this, just open .zshrc or .bashrc
and then add this line to the end of the file

export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

and restart

and it will be fixed
