### ISSUE TITLE
MacOs Ventura Terminal is super slow when Oh My Zsh is installed

### ISSUE THREAD

**Issue by MerzMax** [ohmyzsh/ohmyzsh#11670] opened 2023-05-04 12:11 UTC
### Describe the bug

When installing Oh My Zsh the Terminal gets super slow and is not responding. Commands can be executed but they very slow / never return. 

### Steps to reproduce

1. installed Oh My Zsh in the standard ZSH Mac Terminal 
2. tried to change the directory 

### Expected behavior

the directory should change

### OS / Linux distribution

MacOs 13.3.1 (a)

### Zsh version

5.9

### Oh My Zsh version

master (5a3f565)

### Terminal emulator

MacOs Terminal

### If using WSL on Windows, which version of WSL

None

**Comment by carlosala** [comment] 2023-05-06 11:42
Hi! Could you try with [default .zshrc template](https://github.com/ohmyzsh/ohmyzsh/blob/master/templates/zshrc.zsh-template) to see if it's an omz issue or your own config?
Thanks!

**Comment by gpgkd906** [comment] 2023-08-04 07:07
I have the same issues, and I tried with  [default .zshrc template](https://github.com/ohmyzsh/ohmyzsh/blob/master/templates/zshrc.zsh-template).
 then I opened with new terminal and the speed is lightly faster.
and then i restored my .zshrc, and opened another new terminal, and it also be faster.
I don’t know what is changed...

**Comment by carlosala** [comment] 2023-08-23 21:43
Closing this as it seems it's machine related, not able to reproduce.

**Closed by carlosala** 2023-08-23 21:43 UTC
Labels: Bug
