### ISSUE TITLE
Change directory listing when zoxide is used

### ISSUE THREAD

**Issue by JediMaster25** [ohmyzsh/ohmyzsh#11247] opened 2022-10-08 13:58 UTC
### Describe the proposed feature.

Oh My Zsh shows the latest directories with `dirs` and shows them preceded by a number with `d`.

I want to change this for the zoxide listing `zoxide query -l`.

zoxide's scoring algorithm factors in number of directory accesses as well as recency of access, so I'd say the result is more relevant.

How can I use the list provided by zoxide in [this function](https://github.com/ohmyzsh/ohmyzsh/blob/master/lib/directories.zsh#L25-L32)?
```
function d () {
  if [[ -n $1 ]]; then
    dirs "$@"
  else
    dirs -v | head -n 10
  fi
}
compdef _dirs d
```

**Comment by mcornella** [comment] 2022-10-14 17:23
Duplicate of #11199

**Closed by mcornella** 2022-10-14 17:23 UTC
Labels: Feature
