### ISSUE TITLE
iconv: iconv_open(, -t): Invalid argument

### ISSUE THREAD

**Issue by josearodrigueze** [ohmyzsh/ohmyzsh#12463] opened 2024-05-30 01:06 UTC
### Describe the bug

When start my terminal in mac m1 with omzsh show this messages:

iconv: iconv_open(, -t): Invalid argument
Error converting string from  to UTF-8

### Steps to reproduce

Looking for an existing zsh config...
Using the Oh My Zsh template file and adding it to /Users/....../.zshrc.

         __                                     __
  ____  / /_     ____ ___  __  __   ____  _____/ /_
 / __ \/ __ \   / __ `__ \/ / / /  /_  / / ___/ __ \
/ /_/ / / / /  / / / / / / /_/ /    / /_(__  ) / / /
\____/_/ /_/  /_/ /_/ /_/\__, /    /___/____/_/ /_/
                        /____/                       ....is now installed!

Before you scream Oh My Zsh! look over the `.zshrc` file to select plugins, themes, and options.

• Follow us on Twitter: @ohmyzsh
• Join our Discord community: Discord server
• Get stickers, t-shirts, coffee mugs and more: Planet Argon Shop

iconv: iconv_open(, -t): Invalid argument
Error converting string from  to UTF-8
➜  ~

### Expected behavior

Dont show that message

### OS / Linux distribution

MacOs 14.2.1 (23C71)

### Zsh version

5.9

### Oh My Zsh version

master (071b8f8)

### Terminal emulator

iTerm2

### If using WSL on Windows, which version of WSL

None

**Comment by galoberlyn** [comment] 2024-05-30 03:14
I encountered the same issue. Solved it when choosing a UNIX locale with UTF-8 in it
![image](https://github.com/ohmyzsh/ohmyzsh/assets/25279611/ffbba8b8-aec7-45f4-8963-8630408dd4c6)

![image](https://github.com/ohmyzsh/ohmyzsh/assets/25279611/6e01d0d4-e66d-4b23-8837-151a90f7c4a1)

**Comment by carlosala** [comment] 2024-05-30 05:55
Duplicate of #11645

**Closed by carlosala** 2024-05-30 05:55 UTC
Labels: Bug
