### ISSUE TITLE
auto-update interferes with VSCode shell environment detection

### ISSUE THREAD

**Issue by alexchandel** [ohmyzsh/ohmyzsh#11390] opened 2022-12-14 18:36 UTC
### Describe the bug

Visual Studio Code [launches a shell to detect your environment](https://code.visualstudio.com/docs/supporting/faq#_resolving-shell-environment-fails).  However, Oh My Zsh will occasionally block shell startup with the prompt `[oh-my-zsh] Would you like to update? [Y/n]` when enough time has passed since the last update.

I've seen this problem also occur when other GUIs run an embedded shell too.

### Steps to reproduce

1. Install Oh My Zsh with auto-update enabled
2. Wait
3. Start VS Code (or any other GUI that runs an embedded shell)

### Expected behavior

It would be nice if Oh My Zsh did not block for an auto-update confirmation unless the user was actually capable of answering it (i.e. when running from Terminal.app).

### OS / Linux distribution

macOS 12

### Zsh version

5.8.1

### Oh My Zsh version

master (29cf199)

### Terminal emulator

Terminal.app

### If using WSL on Windows, which version of WSL

None

**Comment by carlosala** [comment] 2022-12-19 12:10
I'll look into it asap, thanks for the report!

**Comment by mcornella** [comment] 2022-12-19 12:17
Should be a matter of just checking for `[[ -o interactive ]]` in the `check_for_upgrade.sh` script.

**Comment by carlosala** [comment] 2022-12-19 12:28
@mcornella yes, exactly. I was planning to check the script, fix it,  and push a PR for testing

**Comment by carlosala** [comment] 2022-12-19 15:47
@mcornella it looks like it's this function that spawns the process https://github.com/microsoft/vscode/blob/82ba981835aeeff0f64c9175be7d87d4451d9b3e/src/vs/platform/shell/node/shellEnv.ts#L102. I let this here and when I have time try to see what's going on.

Even though, I was not able to reproduce the issue on linux.

**Comment by mcornella** [comment] 2022-12-19 16:11
> @mcornella it looks like it's this function that spawns the process https://github.com/microsoft/vscode/blob/82ba981835aeeff0f64c9175be7d87d4451d9b3e/src/vs/platform/shell/node/shellEnv.ts#L102. I let this here and when I have time try to see what's going on.

Looks like they run interactive login shells in order to capture the user configuration: 
https://github.com/microsoft/vscode/blob/82ba981835aeeff0f64c9175be7d87d4451d9b3e/src/vs/platform/shell/node/shellEnv.ts#L143

This is because usually the user configuration lives in .zshrc, instead of in .zshenv as is recommended (we even suggest setting the `$PATH` in .zshrc in our template, so we can see why it's so).

This means we can't rely on the interactive shell option, we could instead check for one of the env variables they set in the file, the best one being `VSCODE_RESOLVING_ENVIRONMENT` IMO.

**Comment by mcornella** [comment] 2022-12-19 16:16
I'm wondering whether the shell is spawned such that `[[ ! -t 1 ]]` works, which checks whether stdout is a tty, so it would be a better option since it's more generic.

**Comment by carlosala** [comment] 2022-12-19 17:08
Not sure, it's a bit difficult to debug actually.

**Comment by carlosala** [comment] 2022-12-19 22:53
@alexchandel we have two solutions that might solve your issue, one super general, and the second specific to vscode. Let's first try the generic one so we introduce as less code as possible in core directly related to some external app. We need your test for this (I was not able to reproduce using Linux!). So, the steps in this case would be:

- Edit your zshrc adding `zstyle ':omz:update' frequency 0` *before* sourcing `oh-my-zsh.sh`. This will make `omz` to ask for update every time you open a session (it'd be easier for testing, so we don't have to wait).
- Update once oh-my-zsh running `omz update`.
- Go to `cd $ZSH` and run `git reset --hard HEAD^`. This will get 1 commit back in the history of oh-my-zsh and, then, `omz` will detect an upgrade an propose it every time we open a terminal (answer `NO` all times to prevent updating before testing with vscode).
- Run `omz pr test 11400` to download the fix branch and use it, then run `exit` and answer `NO` to the question `omz` asks you, to keep yourself in that branch.
- Open vscode and see if it's fixed.

To come back to previous state, you should remove that line from `zshrc` and run `cd $ZSH; git switch master`, close and reopen the terminal, and `omz update; omz pr clean`.

Thanks for testing it, tell me if you have any doubt!

**Comment by carlosala** [comment] 2023-01-03 08:52
@alexchandel friendly ping :)

**Comment by carlosala** [comment] 2023-01-17 11:49
Closing, if this don't solves the issue feel free to test it and ping us 😊

**Closed** 2023-01-17 11:48 UTC
Labels: Bug, Area: init

**Comment by camillol** [comment] 2023-11-10 00:22
@carlosala there are still issues with vscode. When starting a python debugging session, vscode opens a terminal with an interactive shell and immediately sends `source some_virtualenv/bin/activate` into it. If the update prompt `[oh-my-zsh] Would you like to update? [Y/n]` happens to trigger for that shell, it eats the "s" from "source".

I put this in my `.zshrc` before sourcing omz:
```
[[ $TERM_PROGRAM = vscode ]] && zstyle ':omz:update' mode disabled
```

**Comment by carlosala** [comment] 2023-11-10 09:50
It's indeed a good option. Even though it should only happen in certain specific cases. Normally, when you open a vscode terminal, you'd be interested in updating ohmyzsh. Using `mode auto` would be useful as well, since it cancels the upgrade if there's input before updating.

**Comment by camillol** [comment] 2023-11-11 06:27
If you already have the ability to detect if there is pending input, then I think it would be a good idea to check for that before displaying the update prompt, and skipping it if there is input. In fact, it seems even more important to do that in the prompt case than in the auto-update case.

In general, I think it's reasonable to expect that if you start an interactive shell and send commands into it, the shell will receive them. Omz's update prompt breaks this assumption by "hijacking" the shell's prompt. The problem is not vscode-specific, either; a user opening a new terminal tab and immediately pasting commands into it could also run into this problem.

I think the best thing to do would be to change omz's default behavior to print a reminder ("updates available, run <command> to update") without prompting for a response.

**Comment by carlosala** [comment] 2023-11-11 07:19
Actually, if you type input before the prompt it'll also stop the update in that mode. I didn't read properly the upgrade file.
We need to check how vscode is sending the text. A screen recording of it would be useful. You can set `zstyle ':omz:update frequency 0` to force it on each terminal startup.
