### ISSUE TITLE
detect-clipboard is slow on startup

### ISSUE THREAD

**Issue by blayz3r** [ohmyzsh/ohmyzsh#8827] opened 2020-04-12 16:36 UTC
**Describe the bug**
A clear description of what the bug is.
_**detect-clipboard is slow on startup**_

**To Reproduce**
Steps to reproduce the behavior, for example:
**_start zsh with profiler on_**

**Expected behavior**
A brief description of what should happen.
**_Start normally_**
**Screenshots and/or Recordings**

![image](https://user-images.githubusercontent.com/12205650/79074339-cee30580-7cb9-11ea-844c-b4512938c061.png)

**Desktop (please complete the following information):**
 - OS / Distro: [Ubunutu 20.04/wsl2]
 - Latest ohmyzsh Update?: [e.g. Yes]
 - ZSH Version: [5.8]
 - WSL2

**Additional context**
Add any other context about the problem here. This can be themes, plugins, custom configs.
num  calls                time                       self            name
-----------------------------------------------------------------------------------
 **_1)    1         196.85   196.85   85.97%    196.85   196.85   85.97%  detect-clipboard_**
 2)    1          11.32    11.32    4.94%     11.32    11.32    4.94%  compinit
 3)    1           9.18     9.18    4.01%      9.18     9.18    4.01%  handle_completion_insecurities
 4)    1           4.79     4.79    2.09%      4.71     4.71    2.06%  _zsh_highlight_load_highlighters
 5)    1           4.09     4.09    1.78%      4.09     4.09    1.78%  _zsh_highlight_bind_widgets
 6)    8           0.75     0.09    0.33%      0.75     0.09    0.33%  add-zsh-hook
 7)    1           0.66     0.66    0.29%      0.66     0.66    0.29%  colors
 8)    9           0.52     0.06    0.23%      0.52     0.06    0.23%  compdef
 9)    3           0.48     0.16    0.21%      0.48     0.16    0.21%  is-at-least
10)    1           0.13     0.13    0.06%      0.13     0.13    0.06%  (anon)
11)    5           0.09     0.02    0.04%      0.09     0.02    0.04%  spaceship::deprecated
12)    6           0.09     0.01    0.04%      0.09     0.01    0.04%  is_plugin
13)    1           0.27     0.27    0.12%      0.06     0.06    0.03%  prompt_spaceship_setup
14)    2           0.04     0.02    0.02%      0.04     0.02    0.02%  env_default
15)    1           0.01     0.01    0.01%      0.01     0.01    0.01%  bashcompinit

**Comment by mcornella** [comment] 2020-05-23 16:49
@rwe can we do anything to make it faster?

**Comment by rwe** [comment] 2020-05-23 18:29
Relevant function is located here: https://github.com/ohmyzsh/ohmyzsh/blob/3f245edf1be1592e70d6deca6b3ecb8abf8e1356/lib/clipboard.zsh#L51-L107

The report shows a single call (ie it's not doing anything crazy like re-running detection).

`detect-clipboard` basically does two things: it checks env/paths and defines (but doesn't run) functions. The only external command it will possibly run (`uname -r`) does not show up in the profiler list (and should be extremely fast anyway).

I can't easily repro this locally, but my guess is: when `detect-clipboard` checks `${+commands[…]}` to see which clipboard is available, it is _possible_ this is the first time the [`command` hash table special parameter gets filled in](https://github.com/zsh-users/zsh/blob/zsh-5.8/Src/Modules/parameter.c#L210-L277).

To verify this, @blayz3r could try temporarily modifying `lib/clipboard.zsh` like so and see if it gives similar timing results.
```diff
+# Still slow?
+function detect-clipboard() {
+  emulate -L zsh
+  (( ${+commands[wl-copy]} )) || true
+}
 
-function detect-clipboard() {
+function _disabled_detect-clipboard() {
   emulate -L zsh
 
   if [[ "${OSTYPE}" == darwin* ]] && (( ${+commands[pbcopy]} )) && (( ${+commands[pbpaste]} )); then
```

If the timing looks roughly similar, then it's just zsh instantiating that parameter for the first time, which would happen normally anyway. (If the timing is *not* similar, at least this shows how to narrow down the hotspot!).

Alternatively, my open PR #8000 (_Enhanced clipboard detection and management_) permits users to set `ZSH_CLIPBOARD` to skip detection altogether.

**Comment by 0x7d7b** [comment] 2021-04-12 13:09
I was wondering if there are any updates on this? I still have the same issue on the current master branch.

**Comment by MostHated** [comment] 2021-12-29 19:29
I am wondering about this as well ^.

![](https://i.imgur.com/uStZshh.png)

**Comment by Crazy-Ginger** [comment] 2023-01-09 18:38
Encountering this as well. Moved to powerlevel10k but the problem seems to be at startup. 

The speed was still about the same after:

```zsh
+# Still slow?
+function detect-clipboard() {
+  emulate -L zsh
+  (( ${+commands[wl-copy]} )) || true
+}
  
-function detect-clipboard() {
+function _disabled_detect-clipboard() {
```
trying this change

Though it only affects WSL2, my arch laptop and headless Debian server (which uses the same dotfiles) are still just as fast, if a bit faster thanks to powerlevel10k. 

Why is it so slow for wsl2?

**Comment by carlosala** [comment] 2023-01-11 18:59
Hi! Could someone using WSL2 please post the output of `which clipcopy` and `which clippaste` after sourcing `oh-my-zsh.sh`. Let's see where's the issue!

**Comment by Crazy-Ginger** [comment] 2023-01-12 17:13
```console
$ which clipcopy
clipcopy () {
        cat "${1:-/dev/stdin}" | clip.exe
}
$ which clippaste
clippaste () {
        powershell.exe -noprofile -command Get-Clipboard
}
```

**Comment by Crazy-Ginger** [comment] 2023-01-12 17:20
I usually run everything in a tmux session and that returns:
``` console
$ which clipcopy
clipcopy () {
        tmux load-buffer "${1:--}"
}
$ which clippaste
clippaste () {
        tmux save-buffer -
}
```

**Comment by carlosala** [comment] 2023-01-12 19:03
@Crazy-Ginger could you also share `echo $OSTYPE`, `echo ${+commands[clip.exe]}` and `time uname -r`.
Thanks!

**Comment by Crazy-Ginger** [comment] 2023-01-12 19:12
```console
$ echo $OSTYPE
linux-gnu
$ echo ${+commands[clip.exe]}
1
$ time uname -r
5.15.79.1-microsoft-standard-WSL2
uname -r  0.00s user 0.00s system 84% cpu 0.001 total
```

**Comment by carlosala** [comment] 2023-01-12 19:23
It's weird, because the only thing can make that slow is that `uname`, and it doesn't look it's slow.

**Comment by carlosala** [comment] 2023-01-12 19:27
@Crazy-Ginger could you test #11440? You can do that by running `omz pr test 11440`, then `exit` and answering NO to the question.

**Comment by carlosala** [comment] 2023-01-12 19:27
Then try to profile the startup to see if it stills have the issue. Thanks!

**Comment by Crazy-Ginger** [comment] 2023-01-12 19:47
```console
$ zprof
num  calls                time                       self            name
-----------------------------------------------------------------------------------
 1)    1         282.90   282.90   55.68%    282.90   282.90   55.68%  detect-clipboard
 2)    1         194.60   194.60   38.30%    194.58   194.58   38.29%  __conda_activate
 3)  192           9.18     0.05    1.81%      7.79     0.04    1.53%  _zsh_autosuggest_bind_widget
 4)    2           4.89     2.45    0.96%      4.89     2.45    0.96%  compaudit
 5)    1          13.25    13.25    2.61%      4.07     4.07    0.80%  _zsh_autosuggest_bind_widgets
 6)    1           7.04     7.04    1.39%      2.15     2.15    0.42%  compinit
 7)    2           1.88     0.94    0.37%      1.88     0.94    0.37%  (anon)
```

Still no luck somehow

**Comment by carlosala** [comment] 2023-01-12 19:52
It makes no sense. I did another try, just moving WSL detection higher in the priority list. It'd make no sense if it works, but could you try?

**Comment by Crazy-Ginger** [comment] 2023-01-12 20:17
`omz pr test 11440` returned an error when I tried to re-run it, but I assume its just doing a git pull to actually get the updates

**Comment by carlosala** [comment] 2023-01-12 20:20
You can do `cd $ZSH; git switch master; omz pr clean` before.

**Comment by Crazy-Ginger** [comment] 2023-01-12 20:29
Still no change
```console
$ zprof
num  calls                time                       self            name
-----------------------------------------------------------------------------------
 1)    2         537.40   268.70   47.26%    537.40   268.70   47.26%  detect-clipboard
 2)    1         236.11   236.11   20.76%    236.11   236.11   20.76%  compdump
 3)    1         195.93   195.93   17.23%    195.91   195.91   17.23%  __conda_activate
 4)    2         336.16   168.08   29.56%     46.33    23.16    4.07%  compinit
````

Just to make sure its not something stupid in my dotfile I used the template one in .oh-my-zsh, appending `zmodload zsh/zprof`
```console
$ zprof
num  calls                time                       self            name
-----------------------------------------------------------------------------------
 1)    1         275.54   275.54   94.11%    275.54   275.54   94.11%  detect-clipboard
 2)    2           7.77     3.88    2.65%      7.77     3.88    2.65%  compaudit
 3)    1           9.96     9.96    3.40%      2.19     2.19    0.75%  compinit
 4)    1           1.91     1.91    0.65%      1.91     1.91    0.65%  (anon)
 5)    1           1.54     1.54    0.53%      1.54     1.54    0.53%  zrecompile
 6)    1           0.81     0.81    0.28%      0.81     0.81    0.28%  regexp-replace
 7)    1           0.67     0.67    0.23%      0.67     0.67    0.23%  colors
```

**Comment by Crazy-Ginger** [comment] 2023-01-12 20:41
I've also found an issue in neovim regarding the clipboard, when trying to use the middle click paste I get this error:

```console
Error detected while processing function provider#clipboard#Call[9]..function provider#clipboard#Call[6]..268[7]..<SNR>44_try_cmd:   line    1:
E475: Invalid value for argument cmd: 'pbpaste' is not executable
Press ENTER or type command to continue
clipboard: provider returned invalid data
```
I also get a similar error but with `pbcopy` not existing when trying to `yank` anything into `"+`
I have no idea whether this is related or a result of other issues.

**Comment by carlosala** [comment] 2023-01-13 16:42
That has no relation with `detect-clipboard` nor with omz👌🏻

**Comment by Crazy-Ginger** [comment] 2023-01-16 07:32
I don't think this has been fixed with https://github.com/ohmyzsh/ohmyzsh/pull/11440 still seeing same behaviour after updating

**Comment by carlosala** [comment] 2023-01-16 07:40
@Crazy-Ginger #11440 has been merged because of [this comment](https://github.com/ohmyzsh/ohmyzsh/pull/11440#issuecomment-1383182404). Let's reopen, it was closed not on purpose.

**Comment by mcornella** [comment] 2023-01-27 18:43
I think we can avoid making this detection on startup and lazy-load the functions as they're needed. The logic for this is already in the `else` statement of the `detect-clipboard` function so it will be easy to do.

**Comment by carlosala** [comment] 2023-01-27 18:45
@mcornella I was thinking on doing that actually, I completely forgot to create an issue to track that 👌🏻

**Comment by junaire** [comment] 2023-07-22 00:34
Hi maintainers, thanks for your incredible work and I really appreciate it. However, I still have this problem. Are there any fixes or workaround?

zsh version: `zsh 5.8.1 (x86_64-ubuntu-linux-gnu)`

oh my zsh version: `master (8a6fc5c)`

OS: WSL2

uname -r `5.15.90.1-microsoft-standard-WSL2`

profiler shows:
```
num  calls                time                       self            name
-----------------------------------------------------------------------------------
 1)    1         232.27   232.27   79.58%    232.27   232.27   79.58%  detect-clipboard
 2)    1         265.94   265.94   91.12%     11.03    11.03    3.78%  antigen-apply-cached
 3)    1           7.03     7.03    2.41%      6.96     6.96    2.38%  -antigen-cache-generate
 4)    2           4.13     2.06    1.41%      4.13     2.06    1.41%  compaudit
 5)   51         288.07     5.65   98.71%      3.92     0.08    1.34%  -antigen-hook-handler
 6)    6           3.54     0.59    1.21%      3.54     0.59    1.21%  antigen-remove-hook
 7)  265           3.26     0.01    1.12%      3.26     0.01    1.12%  WARN
 8)    1           2.87     2.87    0.98%      2.86     2.86    0.98%  antigen-lock
 9)    4           3.22     0.80    1.10%      2.64     0.66    0.90%  (anon)
10)    1           2.50     2.50    0.86%      2.50     2.50    0.86%  _zsh_highlight_bind_widgets
11)    1           2.54     2.54    0.87%      2.49     2.49    0.85%  _zsh_highlight_load_highlighters
12)   16           1.68     0.10    0.58%      1.68     0.10    0.58%  -antigen-parse-args
13)    1           1.62     1.62    0.56%      1.62     1.62    0.56%  fzf_setup_using_debian
14)    1           5.69     5.69    1.95%      1.56     1.56    0.54%  compinit
```

**Comment by junaire** [comment] 2023-07-22 00:41
NOTE, the normal zsh startup time is OK, but when I open a tmux session, it's very slow. Let me know if you want me to provide more information. Thanks!

**Comment by junaire** [comment] 2023-07-22 00:57
FWIW I copied the `detect-clipboard` function and put it in a zsh file and rename it to `my-detect-clipboard`. Below are the benchmarks:
```
❯ time zsh --interactive -c ./clip.zsh
zsh --interactive -c ./clip.zsh  0.13s user 0.11s system 17% cpu 1.451 total
❯ time zsh --interactive -c ./clip.zsh
zsh --interactive -c ./clip.zsh  0.11s user 0.14s system 16% cpu 1.536 total
❯ time zsh --interactive -c ./clip.zsh
zsh --interactive -c ./clip.zsh  0.15s user 0.15s system 20% cpu 1.491 total
```
I think it indeed is the cause but I don't know to debug that :(

**Comment by junaire** [comment] 2023-07-22 12:11
I don't know why but obviously it takes a very long time to execute the commands below.
```zsh
❯ time zsh --interactive -c 'echo ${+commands[powershell.exe]}'
1
zsh --interactive -c 'echo ${+commands[powershell.exe]}'  0.13s user 0.17s system 17% cpu 1.681 total
❯ time zsh --interactive -c 'echo ${+commands[powershell.exe]}'
1
zsh --interactive -c 'echo ${+commands[powershell.exe]}'  0.13s user 0.11s system 17% cpu 1.326 total
❯ time zsh --interactive -c 'echo ${+commands[powershell.exe]}'
1
zsh --interactive -c 'echo ${+commands[powershell.exe]}'  0.11s user 0.16s system 18% cpu 1.467 total
❯ time zsh --interactive -c 'echo ${+commands[clip.exe]}'
1
zsh --interactive -c 'echo ${+commands[clip.exe]}'  0.10s user 0.15s system 17% cpu 1.380 total
❯ time zsh --interactive -c 'echo ${+commands[clip.exe]}'
1
zsh --interactive -c 'echo ${+commands[clip.exe]}'  0.17s user 0.12s system 16% cpu 1.777 total
❯ time zsh --interactive -c 'echo ${+commands[clip.exe]}'
1
zsh --interactive -c 'echo ${+commands[clip.exe]}'  0.16s user 0.14s system 18% cpu 1.668 total
```

Maybe it's because these commands are from Windows? I did find a related issue (https://github.com/microsoft/WSL/issues/8943)

Do you think it is possible to work around this by not invoking these external commands? @carlosala

**Comment by junaire** [comment] 2023-07-22 12:32
That's interesting. I tried to replace the original check from `(( $+commands[clip.exe] )) && (( $+commands[powershell.exe] ))` to `$(uname -r) = *icrosoft*` and indeed I can observe `detect-clipboard` disappeared in the profiler list. However, it doesn't have a good improvement? I'm really really confused...

```
❯ time zsh --interactive -c exit
num  calls                time                       self            name
-----------------------------------------------------------------------------------
 1)    9         279.50    31.06   99.79%    264.17    29.35   94.31%  antigen
 2)    4           3.76     0.94    1.34%      2.98     0.75    1.06%  (anon)
 3)    1           2.93     2.93    1.05%      2.93     2.93    1.05%  _zsh_highlight_bind_widgets
 4)    1           2.54     2.54    0.91%      2.49     2.49    0.89%  _zsh_highlight_load_highlighters
 5)    1           2.36     2.36    0.84%      2.36     2.36    0.84%  detect-clipboard
 6)    1           1.54     1.54    0.55%      1.54     1.54    0.55%  fzf_setup_using_debian
 7)    9           0.66     0.07    0.24%      0.66     0.07    0.24%  is-at-least

zsh --interactive -c exit  0.17s user 0.08s system 22% cpu 1.128 total
```

**Closed** 2023-08-24 15:27 UTC
Labels: Area: core, Performance

**Comment by carlosala** [comment] 2023-08-24 15:29
It should not be slow anymore, since the clipboard will be detected when used 🎉
