### ISSUE TITLE
Make default 'master' to 'main' 

### ISSUE THREAD

**Issue by sabahzero** [ohmyzsh/ohmyzsh#10460] opened 2021-11-29 17:59 UTC
Reasoning and execution:
https://stevenmortimer.com/5-steps-to-change-github-default-branch-from-master-to-main/

![Screen Shot 2021-11-29 at 9 59 20 AM](https://user-images.githubusercontent.com/16907482/143922918-f52f10ba-3942-47d4-8137-d6423296c958.png)

**Comment by mcornella** [comment] 2022-01-19 18:16
Duplicate of #9015

**Closed by mcornella** 2022-01-19 18:16 UTC
Labels: Feature
