### ISSUE TITLE
Plugins: Debian and Ubuntu

### ISSUE THREAD

**Issue by jkemp814** [ohmyzsh/ohmyzsh#10359] opened 2021-10-30 04:00 UTC
### If the feature request is for a plugin or theme, specify it here.

Debian, Ubuntu

### Describe the proposed feature.

Combine the plugins Debian and Ubuntu and rename to APT or (apt)

### Additional context

Most of the aliases are for apt, apt-get, or aptitude. Very redundant. Only a couple of aliases are for dpkg, or deb package management between the two plugins. I can't see anything aliased for either OS.  Mainly pertaining to APT. Renaming would cover all the other Debian based or Ubuntu derivatives, i.e. Mint, MX Linux, PopOS, and a whole slew of others.

Thank you for anytime spent reviewing this proposal.

**Comment by mcornella** [comment] 2021-11-02 11:42
Duplicate of #7745.

**Closed by mcornella** 2021-11-02 11:42 UTC
Labels: Feature
