### ISSUE TITLE
history-substring-search matches only from beginning of line

### ISSUE THREAD

**Issue by david-morris** [ohmyzsh/ohmyzsh#7255] opened 2018-10-08 22:13 UTC
When using history-substring-search, I expect to be able to use arbitrarily positioned substrings, like in fizsh.  However, it appears that I can only search history by substrings anchored at the beginning of the history item, unlike in fizsh.

For example, in fizsh, `googl` :arrow_up: would match `ping google.com`, however, in history-substring-search, it does not.

However, history-substring-search seems to be enabled; `pin` :arrow_up: does match `ping google.com`.

I'm on 3320658f30e0556bae0844629a265ae71f807cc1, just pulled and reproduced bug as written above.  Using an arch system.

**Comment by mcornella** [comment] 2019-04-09 10:11
I'm on the latest version and it works for me, verify that your up arrow key is really set to run `history-substring-search-up` by looking at the bindkey associated to it: press `CTRL`+`V` then the up arrow and it should display the up arrow bindkey sequence. 

Use that sequence to run `bindkey 'sequence'`; it should print `history-substring-search-up`. For example, in my system:
```
$ bindkey '^[OA'
"^[OA" history-substring-search-up
```

If that's not properly set up there is a bug because the plugin should bind the up/down arrow keys to the history-substring-search widgets.

**Comment by robbyrussell** [comment] 2019-12-29 04:11
@david-morris Do you have time to help us test this out?

**Comment by mcornella** [comment] 2020-05-16 16:49
I'm gonna close this as non-reproducible.

**Closed by mcornella** 2020-05-16 16:49 UTC
Labels: Area: plugin, Type: support
