### ISSUE TITLE
history-substring-search no longer functions after latest update

### ISSUE THREAD

**Issue by mayersj1** [ohmyzsh/ohmyzsh#2735] opened 2014-04-21 14:01 UTC
After updating oh_my_zsh this morning, the history-substring-search plugin no longer functions.  Even manually sourcing the history-substring-search.zsh file doesn't bring it back to life.

**Comment by donnykurnia** [comment] 2015-03-04 05:37
I have no vi-mode and no safe-paste. up arrow still works last week before latest update.

**Comment by jarofghosts** [comment] 2015-05-15 21:03
this seems to be a problem again

**Comment by donnykurnia** [comment] 2015-05-23 09:06
All I had to do is close all screen session and start over. Now the arrow works normally. Looks like some update affect existing sessions and restart the whole session is the only way to make it right, rather than only reloading the zsh config.

**Comment by kappa** [comment] 2015-05-23 19:45
The problem is not fixed. I see that still only the keypad versions get binded.
This is needed:
bindkey "$terminfo[cuu1]" history-substring-search-up
bindkey "$terminfo[cud1]" history-substring-search-down

**Comment by kappa** [comment] 2015-05-23 19:52
Although even this does not fix the "Down" arrow.

**Comment by apjanke** [comment] 2015-06-25 22:39
@kappa: What's your setup where this isn't working for you? (OS, terminal emulator, `$plugins`, and `$TERM` value?) I can reproduce your situation on OS X 10.9.5 running iTerm2, `TERM=xterm-256color`, and `$plugins` being `( vi-mode history-substring-search )`, in either order.

When I add your extra `cuu1` and `cud1` bindings, the up arrow starts working, but not the down arrow, same as for you.

**Comment by kappa** [comment] 2015-06-25 22:45
Ubuntu 15.04, gnome-terminal, TERM=xterm, plugins=(git vi-mode cpanm zsh-syntax-highlighting history-substring-search lein perl vagrant)

**Comment by apjanke** [comment] 2015-06-25 22:49
I think part of the issue is that the `vi-mode` plugin [redefines the ZLE widgets `zle-line-init` and `zle-line-finish`](https://github.com/robbyrussell/oh-my-zsh/blob/599831b85a5fd4564ab820530e2bb45f37ca3f99/plugins/vi-mode/vi-mode.plugin.zsh#L1-L15), but it does them in a wonky way.

```
function zle-keymap-select zle-line-init zle-line-finish {
  # The terminal must be in application mode when ZLE is active for $terminfo
  # values to be valid.
  if (( ${+terminfo[smkx]} )); then
    printf '%s' ${terminfo[smkx]}
  fi
  if (( ${+terminfo[rmkx]} )); then
    printf '%s' ${terminfo[rmkx]}
  fi

  zle reset-prompt
  zle -R
}
```

That looks like it's issuing `smkx` and then `rmkx` in sequence whenever the line editing starts or ends. That means the terminal will *not* be in application mode when ZLE is active, because `zle-line-init` will issue `rmkx` last.

Here's what the [widget definitions look like in `lib/key-bindings.zsh`](https://github.com/robbyrussell/oh-my-zsh/blob/599831b85a5fd4564ab820530e2bb45f37ca3f99/lib/key-bindings.zsh#L5-L16). They issue `smkx` when editing starts, and `rmkx` only when editing is finished. (`echoti foo` is equivalent to `printf '%s' ${terminfo[foo]}`.)

```
  function zle-line-init() {
    echoti smkx
  }
  function zle-line-finish() {
    echoti rmkx
  }
```

If I disable the weird definitions from `vi-mode` by changing the line to `function zle-keymap-select-OFF zle-line-init zle-line-finish-OFF {` so the `lib/key-bindings.zsh` ones take precedence, then the up and down arrows for history-substring-search start working again, even if I have `vi-mode` loaded. Doing the extra `cuu1` and `cud1` bindings is not necessary for me in that case.

It looks like these widget definitions were changed in #1533. The [old version](https://github.com/gberenfield/oh-my-zsh/blob/3199d2ed8d70dc45911f34dd7c2ec4b702db3b28/plugins/vi-mode/vi-mode.plugin.zsh#L6-L16)  used to check whether it was being called as `zle-line-init` or `zle-line-finish` and issue `smkx` or `rmkx` respectively, instead of both in a row for either case. @gberenfield, looks like you were the author for this. Can you comment?

I think #1479 is basically the same problem as this and #1387 fixed it, but the change in #1533 caused a regression.

I suspect the thing to do is to just remove the `zle-line-init` and `zle-line-finish` widget definitions from `vi-mode`, because the current `lib/key-bindings.zsh` widgets do what looks like the original intent of the old `vi-mode` widgets, and what most terminals and terminfo clients will be expecting, I think.

**Comment by apjanke** [comment] 2015-06-25 22:52
@kappa, can you try disabling the widgets from `vi-mode` and see if it fixes things for you too? It's a one line change.

```
diff --git a/plugins/vi-mode/vi-mode.plugin.zsh b/plugins/vi-mode/vi-mode.plugin.zsh
index 4424bb2..d8cdb30 100644
--- a/plugins/vi-mode/vi-mode.plugin.zsh
+++ b/plugins/vi-mode/vi-mode.plugin.zsh
@@ -1,6 +1,6 @@
 # Ensures that $terminfo values are valid and updates editor information when
 # the keymap changes.
-function zle-keymap-select zle-line-init zle-line-finish {
+function zle-keymap-select zle-line-init-OFF zle-line-finish-OFF {
   # The terminal must be in application mode when ZLE is active for $terminfo
   # values to be valid.
   if (( ${+terminfo[smkx]} )); then
```

**Comment by apjanke** [comment] 2015-06-25 22:54
@donnykurnia – you're not running vi-mode? What's your setup (OS, terminal program, `$TERM` value, `$plugins` list)?

**Comment by apjanke** [comment] 2015-06-25 22:56
@regolith – I think you're misreading that documentation on `kcu1` vs `cuu1`. It sounds to me like `kcu1` is a key*board* arrow key press, where `cuu1` is not a particular key, but a command to the terminal to move the cursor. (Which isn't to say that a particular terminal emulator might not be set up to issue `cuu1` for some keys.) I'll see if I can find a reference that clears this up.

**Comment by apjanke** [comment] 2015-06-25 23:40
I've set up a branch [fix-vi-mode-zle-widgets](https://github.com/apjanke/oh-my-zsh/tree/fix-vi-mode-zle-widgets) with this fix on it. It removes `vi-mode`'s line start and end widgets in deference to `lib/key-bindings.zsh`. Works for me on OS X.

Anyone want to test it before I turn this in to a PR? To test:

```
cd .oh-my-zsh
git remote add apjanke https://github.com/apjanke/oh-my-zsh
git fetch apjanke
git checkout -b apjanke/fix-vi-mode-zle-widgets
```
And then `git checkout master` when you're done.

**Comment by southdesign** [comment] 2015-07-06 15:04
@apjanke Unfortunately, on OS X with iTerm2 I'm not able to enter search mode with your branch.
I loaded vi-mode before history-substring-search - did you do it the other way round?

**Comment by apjanke** [comment] 2015-07-06 22:27
@southdesign Yes. I had `$plugins=(git vi-mode history-substring-search)`. Looks like it is order dependent; if I load `vi-mode` last, then the history substring search doesn't work for me either. I don't know if that can be fixed, because both plugins want to bind the up and down arrow keys, and the last one wins.

I think this might be a related, pre-existing issue. The `vi-mode` plugin unconditionally resets the key bindings [with `bindkey -v`](https://github.com/robbyrussell/oh-my-zsh/blob/7b71dccbaff4a9bb72fc069407723d2ecb7c0eae/plugins/vi-mode/vi-mode.plugin.zsh#L28). This will clobber the key mappings set by `history-substring-search` if you loaded it prior.

So why did loading `history-substring-search` before `vi-mode` used to work? Here's where it gets complicated. This has to do with tricky terminal configuration stuff, so I'm not 100% sure what's "right" here, but I think this is the gist of what's going on.

* Prior to #2511, `history-substring-search` was [using hardcoded terminal-specific escape sequences](https://github.com/robbyrussell/oh-my-zsh/blob/fd732eb3ff4984ddc9109e950cf7ceb472cb9824/plugins/history-substring-search/history-substring-search.zsh#L166-L167) for its key bindings.
 * Those sequences were not the normal `xterm` up and down arrow (`kcuu1`/`kcud1`) transmit ("Normal Keypad") mode sequences, but the `urxvt` up/down arrow sequences.
 * *But*, those `urxvt` transmit-mode sequences happen to match the sequences that `xterm` sends in local ("Application Keypad") mode.
* `bindkey -v` respects terminfo, and only binds the key sequences which are available in `terminfo`. These include the "normal"/"transmit" mode sequences for arrow keys, but not the "local"/"application" mode sequences. So it doesn't clobber the hardcoded sequences that `vi-mode` was using that matched the `xterm` application mode sequences.
* The change to `vi-mode` in #1533 is accidentally leaving the terminal in "application"/"local" mode after line editing starts. This means the old hardcoded local-mode up arrow in `history-substring-search` happened to line up with what the arrow key was sending during command line editing.
* Then the change in #2511 switched to using terminfo-defined key bindings, which are the "normal"/"transmit" mode ones. This caused it to stop working at all with the broken #1533 local keypad mode, and to collide with the mappings that `vi-mode` is doing, too.

(This is made confusing by the fact that [the comments in the `smkx`/`rmkx` code](https://github.com/robbyrussell/oh-my-zsh/blob/7b71dccbaff4a9bb72fc069407723d2ecb7c0eae/plugins/vi-mode/vi-mode.plugin.zsh#L4) may be using "application mode" in the wrong sense. I think "application keypad mode" actually means the non-transmitting version enabled by `rmkx`, based on reading through other documentation.)

But this overall state of affairs isn't portable or intentional. It's more like these were complementary bugs that enabled this particular use case.

I don't think there's a good way to make `vi-mode` and `history-substring-search` work together in both orders, because they both want to define the behavior for up-arrow. And there's no good way to check if it was already set and avoid clobbering it, because there's always a default binding of some sort by the time it gets to OMZ load time.

I think the best you could do is just say that `history-substring-search` must come after `vi-mode` or any other plugin that wants to re-bind the up and down arrows. And it could examine `$plugins` and issue a warning when it sees this isn't the case.

**Comment by apjanke** [comment] 2015-07-07 01:19
Looks like this `vi-mode` key binding clobbering is a known issue:  #3435.

There's an attempt in #1629 to define "special" key bindings which take precedence, and to have the `vi-mode` plugin re-source a lib file to restore those special key bindings. I'm not endorsing this approach.

**Comment by apjanke** [comment] 2015-07-07 03:31
Hi folks. Unrelated to this particular issue, but I'm asking because you're apparently the major users of the `history-substring-search` plugin.

There's an upstream for this plugin at [zsh-users/zsh-history-substring-search](https://github.com/zsh-users/zsh-history-substring-search) with a couple years of work on it, and we might want to pull that in to fix #3913. Could you head over #3913 and comment if you have thoughts on that?

**Comment by apjanke** [comment] 2015-07-07 20:57
Hey, thanks to @sunaku et al's work on the upstream zsh-history-substring-search, I think there's a fix for this. Check out the [README where it talks about key bindings](https://github.com/zsh-users/zsh-history-substring-search#usage).

If we switch `history-substring-search` to use `bindkey -m` to add bindings to specific keymaps, and bind the up/down arrows in both `emacs` and `viins` keymaps, then this should work again, regardless of whether `vi-mode` is loaded before or after it. Interested in giving it a try?

And what about binding those emacs- and vi-specific key strokes too, as discussed in the readme?

**Comment by southdesign** [comment] 2015-07-08 08:18
Just as a little update - I have no trouble if I just rebind the incremental search key manually:

    plugins=(git vi-mode history-substring-search)
    bindkey '^r' history-incremental-search-backward

Like this, for me both, vi-mode and the history-search works like a charm.

**Comment by apjanke** [comment] 2015-07-13 15:49
@southdesign: That makes sense. The `'^r`' binding is first made by `lib/key-bindings.zsh` when it runs early in the OMZ process. At that point, the `emacs` keymap is linked to `main`, so the binding gets added to that keymap. When the `vi-mode` plugin loads, it does `bindkey -v` and switches to the `vi` keymaps, and `viins` gets linked to `main`. When it returns to your `.zshrc`, that `bindkey '^r'` call adds the binding to the `viins` keymap, which is now the main keymap.

Having OMZ "double bind" the keys to both keymaps using `bindkey -m` would have a similar effect.

**Comment by apjanke** [comment] 2015-07-28 02:37
Hi folks. I think I mostly have a fix for this. (Except for the `^r` clobbering.)

Fixing it requires both #4191 (to fix the smkx/rmkx issue in vi-mode) and #4192 or #4193 (which adds explicit "double-binding" to history-substring-search). You can see their combined effect in my branch https://github.com/apjanke/oh-my-zsh/tree/histsubstr-fix-bind-and-smkx-no-upstream, which merges them both in.

If these work for you, please drop a :+1: on the corresponding PRs.

**Comment by apjanke** [comment] 2015-11-07 00:33
Hi folks. I've written a little [`omz_bindkey_dump` diagnostic tool](https://github.com/apjanke/oh-my-zsh-custom/blob/master/diagnostics-extras.zsh) which will output your current `bindkey` state, decorated with the capability names for your current terminal, as indicated by `$TERM` and `$terminfo`. This could help diagnosing these key binding states a little easier.

Example:

```
$ omz_bindkey_dump
bindkey -A emacs main
Key        Capability
Sequence   (xterm-256color)       Command
      ^@                          set-mark-command
      ^A                          beginning-of-line
...
     ^[H   hts                    run-help
     ^[L                          down-case-word
     ^[N                          history-search-forward
    ^[OA   kcuu1                  up-line-or-beginning-search
    ^[OB   kcud1                  down-line-or-beginning-search
    ^[OC   kcuf1                  forward-char
    ^[OD   kcub1                  backward-char
    ^[OF   kend                   end-of-line
    ^[OH   khome                  beginning-of-line
...
```

This tells me that `beginning-of-line` is indeed bound to the sequence that `zsh` and `curses` think that my terminal (as an `xterm-256color` emulator) emits for the Home key.

This is not part of main OMZ, so you'll need to download and source it separately.

**Comment by ikhthiandor** [comment] 2015-11-08 05:28
@apjanke The following bindkeys seem to work for me. As seen here. https://github.com/sorin-ionescu/prezto/issues/516

bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

**Comment by apjanke** [comment] 2015-11-08 22:56
```
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down
```

Those are the sequences that `xterm` sends for the up and down arrow keys when in "keypad-local" mode. If that's working for you, that probably means that you are loading `vi-mode` or something else which is breaking `zle-line-init` so it doesn't send `smkx` to put the terminal in "keypad-application" mode.

Have a look at the [email on the Zsh mailing list](http://www.zsh.org/mla/users/2014/msg00030.html) that is referenced in that bug. The important bit is this.

> [T]he values from $terminfo
are _only_ valid in "keyboard-transmit-mode". That's the mode you enter,
by issuing "smkx" and you leave by "rmkx" (see terminfo(5)).

#4191 will fix things so that is manual key binding is no longer necessary.

**Comment by billcarroll** [comment] 2015-11-12 19:32
Finally found the issue keeping history-substring-search from working in my setup.

I had to remove "vi-mode" from plugins in ~/.zshrc to get "history-substring-search" working again. Other plugins with keybindings might cause the same or similar issues.

**Comment by sunaku** [comment] 2015-11-12 21:11
A good way to rule out differences in configuration is to run `zsh -f` (don't load with any ZSH configuration) and then [manually load/configure the zsh-history-substring-search plugin as shown in the README](https://github.com/zsh-users/zsh-history-substring-search#usage). :neckbeard:

**Comment by Konfekt** [comment] 2015-11-15 21:37
Had the same problem using either the `vi-mode` plugin or a snippet that changes the cursor shape according to the vi-mode on https://bbs.archlinux.org/viewtopic.php?id=95078

In either case https://github.com/robbyrussell/oh-my-zsh/issues/2735#issuecomment-42705323 resolved the issue and better be merged.

**Comment by Konfekt** [comment] 2015-11-29 19:27
The commit did not solve the issue over here. But
```sh
# bind UP and DOWN arrow keys
zmodload zsh/terminfo
bindkey "$terminfo[kcuu1]" history-substring-search-up
bindkey "$terminfo[kcud1]" history-substring-search-down
bindkey "$terminfo[cuu1]" history-substring-search-up
bindkey "$terminfo[cud1]" history-substring-search-down
```
does.

**Comment by mcornella** [comment] 2015-12-13 22:59
@Konfekt can you check if it works now after merging #4193? If I understand correctly, that should make it work even with `vi-mode` plugin enabled.

**Comment by mcornella** [comment] 2015-12-14 08:36
Oh, wait, it should also bind those
```zsh
bindkey "$terminfo[cuu1]" history-substring-search-up
bindkey "$terminfo[cud1]" history-substring-search-down
```
right?

**Comment by Konfekt** [comment] 2015-12-14 11:10
Yep, it better should as the `k` in `[kcu..]` means the Keypad arrow keys.

**Comment by mcornella** [comment] 2015-12-14 11:17
Ok, let me put together a PR to fix that.

**Comment by mcornella** [comment] 2015-12-14 11:49
#4693 should do it

**Comment by sunaku** [comment] 2015-12-14 19:16
@Konfekt Where are you getting those `cuu1` and `cud1` codes from? :cold_sweat:

I ask because [terminfo does not define](http://invisible-island.net/ncurses/man/terminfo.5.html#h3-Keypad-and-Function-Keys) any `cuu1` or `cud1` codes (without "k" prefix):

> The codes sent by the left arrow, right arrow,  up  arrow,
> down  arrow,  and  home keys can be given as kcub1, kcuf1,
> kcuu1, kcud1, and khome respectively.

**Comment by Konfekt** [comment] 2015-12-14 19:30
Over here
```vim
# bind UP and DOWN arrow keys
zmodload zsh/terminfo
bindkey "$terminfo[cuu1]" history-substring-search-up
bindkey "$terminfo[cud1]" history-substring-search-down
```
worked, but not `kcuu1`.

**Comment by apjanke** [comment] 2015-12-14 20:04
You shouldn't have to bind `cuu1` and `cud1`. 

>  terminfo does not define any cuu1 or cud1 codes (without "k" prefix):

Those are defined in terminfo; they're cursor control sequences that the program can send to the terminal to control its cursor movement. They're not defined to be the sequence issued by any keys.

From that terminfo documentation, in the "Basic capabilities" section:

> If there is a code to move the cursor one position to  the
       left  (such  as backspace) that capability should be given
       as cub1.  Similarly, codes to move to the right,  up,  and
       down should be given as cuf1, cuu1, and cud1.  These local
       cursor motions should not alter the text they  pass  over,
       for  example,  you would not normally use "cuf1= " because
       the space would erase the character moved over.

However, the sequences used for `cuu1` and `cud1` may be the same sequences a given terminal issues in keypad local mode. This is kind of a coincidence – the terminfo database doesn't define it that way – but it's true for many common terminals. This is the case for iTerm2, xterm, and urxvt. I don't know if it's true for all terminals. So, if your `zle-line-init` hook is not working as OMZ expects and issuing `smkx`, then you'll still be in keypad local mode in ZLE, and those extra `cuu1`/`cud1` bindings will work for some terminals. But it's not how the overall system is supposed to be working.

We may not want them in the main OMZ code, because they shouldn't be needed and their presence could be misleading. On the other hand, there presence probably won't hurt anything, because it probably won't collide with any other sequences, and it's going to be a partial workaround for users whose `smkx`/`rmkx` is broken.

From @Konfekt:
> Had the same problem using either the vi-mode plugin or a snippet that changes the cursor shape according to the vi-mode on https://bbs.archlinux.org/viewtopic.php?id=95078

Here's that snippet:

```
zle-keymap-select () {
if [ $KEYMAP = vicmd ]; then
echo -ne "\033]12;Red\007"
else
echo -ne "\033]12;Grey\007"
fi
}
zle -N zle-keymap-select
zle-line-init () {
zle -K viins
echo -ne "\033]12;Grey\007"
}
zle -N zle-line-init
bindkey -v
```

It redefines `zle-line-init` to not issue `smkx` [like the one in OMZ's `lib/key-bindings.zsh` does](https://github.com/robbyrussell/oh-my-zsh/blob/531789e4fa725e519069118aba0bea63b77466a8/lib/key-bindings.zsh#L8-L10), so terminfo-based bindings for keypad keys aren't valid. 

Too many things want to use `zle-line-init` for different things. Maybe we should try to add support for a `$zle_line_init_functions`, like zsh's `$precmd_functions`, so multiple hooks can be added.

**Comment by FiloSottile** [comment] 2016-04-15 15:58
This is still an issue with `safe-mode`

**Comment by spijet** [comment] 2016-05-17 10:15
Using git-version of Termite terminal emulator also requires me to bind cuu1/cud1 keys, not k versions. `$TERM` is `xterm-termite`.

**Comment by apjanke** [comment] 2016-05-24 02:43
Okay, folks. I've finally put together a PR to address this:  #5113. It does away with `smkx`/`rmkx` and switches to hardcoded Xterm style character sequences for cursor keys, with an `omz_bindkey` extension so we can still use the nice, readable terminfo mnemonics. I think it'll go a long ways toward clearing this whole mess up.

Works for me locally. Would appreciate it if you folks could test it and let me know if it fixes things for you, too.

(@spijet, I don't have Termite, but I believe it will fix things for you, too; your description sounds like exactly this problem.)

**Comment by mcornella** [comment] 2024-06-12 10:44
Hi there, a lot of things have happened within the project these 10(!) years on the key binding space and I believe we have solved this because we are unable to reproduce this anymore. I'm going to close the issue, but feel free to reopen or create a new one if this is still happening. Sorry for the delay, and thanks for your patience!

**Closed by mcornella** 2024-06-12 10:44 UTC
Labels: Topic: bindkey
