### ISSUE TITLE
Slow Close of zsh on Ubuntu 20.04

### ISSUE THREAD

**Issue by bit-user** [ohmyzsh/ohmyzsh#8885] opened 2020-05-04 18:30 UTC
When I close ZSH with ctrl+d I see a newline, until the shell closes after 4-5 seconds.
What kind of information do you need, so I can provide that?

Thanks :)

**Comment by mcornella** [comment] 2020-05-05 17:01
You can run `set -xv` to enable tracing and then press CTRL+D to exit and see if it's running a command while closing. I'd bet though that this is a terminal emulator problem, try to search Ubuntu bugs for the same issue.

**Comment by alberpilot** [comment] 2020-05-06 07:29
Hello

  I have a similar problem here. I have a very slow zsh terminal when I am located into a git repository. 
I attach the `set -xv` trace of `cd ~` in order to take it as an example. Then, the other attachment is a `cd myrepofolder` which is very slow. 

In addition to this, a new "information" appears in the prompt line:
![image](https://user-images.githubusercontent.com/3830293/81148030-ca89cf80-8f7b-11ea-948d-ccb9e460c015.png)

[cdhome.txt](https://github.com/ohmyzsh/ohmyzsh/files/4585296/cdhome.txt)
[cdrepo.txt](https://github.com/ohmyzsh/ohmyzsh/files/4585297/cdrepo.txt)




Thanks for the help!

**Comment by bit-user** [comment] 2020-05-06 20:43
I think the biggest problem is, that this doesn't happen all the time. Should I better add something like
`zsh -xv &> >(tee ~/omz-debug.log 2>/dev/null)` to my bashrc so I don't miss setting `set -xv` ?

**Comment by mcornella** [comment] 2020-05-07 10:36
@alberpilot your problem sounds like https://github.com/ohmyzsh/ohmyzsh/issues/8237, since you seem to be using the agnoster theme. Check that you're using the latest ohmyzsh version (`upgrade_oh_my_zsh`) and post there your problem otherwise.

**Comment by alberpilot** [comment] 2020-05-07 10:50
Awesome, the upgrade solved my problem. I didn't notice that I had disabled the automatic upgrades. 
Thanks @mcornella!

**Comment by mcornella** [comment] 2020-05-07 12:07
> I think the biggest problem is, that this doesn't happen all the time. Should I better add something like
> `zsh -xv &> >(tee ~/omz-debug.log 2>/dev/null)` to my bashrc so I don't miss setting `set -xv` ?

Maybe use `zsh -xv 2> >(tee ~/omz-debug.log &>/dev/null)`. You won't get the trace output in your shell. Let me know once you get a trace of the reproduced problem.

**Comment by mcornella** [comment] 2020-12-11 14:40
Closing due to inactivity.

**Closed by mcornella** 2020-12-11 14:40 UTC
Labels: Support
