### ISSUE TITLE
Install via homebrew

### ISSUE THREAD

**Issue by reggi** [ohmyzsh/ohmyzsh#9726] opened 2021-03-11 22:03 UTC
I'd love it if were possible to install ohmyzsh via homebrew.

**Comment by arthurduarte1** [comment] 2021-03-11 22:04
+1

**Comment by Logicer16** [comment] 2021-05-28 04:24
The current configuration of ohmyzsh would violate multiple requirements in [Acceptable Formulae](https://docs.brew.sh/Acceptable-Formulae), including:

- We don’t like tools that upgrade themselves (Given, this can be disabled)
- We don’t like install scripts that download unversioned things (i.e. no cloning from master)
- Stable versions (see above)

So, in summery, if we want to get ohmyzsh on Homebrew, we're going to have to set up versioned releases, or something similar.

**Comment by Logicer16** [comment] 2021-05-28 05:01
Though, if we somehow manage to convince the maintainers to setup tagged releases, the *theoretical* `ohmyzsh.rb` would look somewhat similar to [`git-fresh.rb`](https://github.com/Homebrew/homebrew-core/blob/11d3369762a7eccf2349eefc732ffe183cb0ba13/Formula/git-fresh.rb), including the `bottle :unneeded` and running `install.sh` in an install function, though I'm unsure of the correct way to run `uninstall.sh` (or at least a variation seen as it currently requires user confirmation).

**Comment by Logicer16** [comment] 2021-05-28 05:09
There is references to a removed `Homebrew/homebrew-headonly` scattered around GitHub, which would be the perfect place for ohmyzsh in it's current state.

**Comment by Logicer16** [comment] 2021-05-28 05:11
Ohmyzsh could also host `ohmyzsh.rb` in one of its own repos and get users to tap into it.

**Comment by mcornella** [comment] 2024-07-24 10:52
Duplicate of #9726 (in progress).

**Closed by mcornella** 2024-07-24 10:52 UTC
Labels: Feature

**Comment by Logicer16** [comment] 2024-07-24 10:54
>Duplicate of https://github.com/ohmyzsh/ohmyzsh/issues/9726
That's this issue...

**Comment by mcornella** [comment] 2024-07-24 12:31
Sorry, meant to say #9216.
