### ISSUE TITLE
Regression in tab filename completion behaviour with oh-my-zsh and zsh 5.9

### ISSUE THREAD

**Issue by litmus-ritten** [ohmyzsh/ohmyzsh#10996] opened 2022-06-16 05:56 UTC
### Describe the bug

Good day.

Tab completion of filenames fails under certain circumstances outlined in the *steps to reproduce* section using a fresh install of oh-my-zsh and zsh 5.9. The problem appears to be limited to filenames that have a lexicographic distance of one letter of the alphabet in their first difference, and have two or more additional subsequent letters thereafter, however I have not exhaustively tested it. For instance:

- `test-file.aaa` and `test-file.bar` **will** induce the bug.
- `test-file.a` and `test.file.b` **will not**.
- `test-file.aa` and `test.file.ba` **will not**.
- `test-file.service` and `test-file.timer` **will** induce the bug.
- `test-file.aervice` and `test-file.timer` **will not**.

- **This behaviour does not occur with zsh 5.8**, as ascertained by a downgrade of the relevant package.
- I have observed this bug on two hosts with different zshrc/oh-my-zsh configurations, both running zsh 5.9.
- However the bug is not observed when I copy my everyday oh-my-zsh configuration to an Ubuntu host running zsh 5.8.

Thank you for your time.

### Steps to reproduce

1. Install zsh 5.9.
2. Install oh-my-zsh via curl of GitHub repository.
3. `touch` two files called `test-file.aaa` and `test-file.bar`
4. Attempt to tab complete the string `./test`
5. Observe that the autocomplete result is `./test-file.Ba`
6. Press tab again.
7. Observe that the autocomplete result is `./test-file.bar`

### Expected behavior

Tab completion should only complete to the first difference between filenames. Successive tabs should display and cycle through the options.

### Screenshots and recordings

Anomalous behaviour after tabbing `./test` in a directory containing `test.aaa` and `test.bar`:
![gh - zsh anomalous](https://user-images.githubusercontent.com/62781197/174000297-cb265af1-127b-4770-9ccd-600586ac1b0d.png)

Expected behaviour after tabbing `./test` twice in a directory containing `test.a` and `test.b`:
![gh - zsh expected](https://user-images.githubusercontent.com/62781197/174000494-6377a08f-47d1-40aa-b381-e72ba32c9f8b.png)

### OS / Linux distribution

Manjaro Linux x86_64

### Zsh version

5.9

### Terminal emulator

Tilix

**Comment by carlosala** [comment] 2022-06-16 08:38
I'm also experiencing this. Could you take a look on this @mcornella? You are our completion expert😉😉

**Comment by mcornella** [comment] 2022-06-16 09:38
Duplicate of #10972. See https://github.com/ohmyzsh/ohmyzsh/issues/10972#issuecomment-1146806099.

**Closed by mcornella** 2022-06-16 09:38 UTC

**Comment by mcornella** [comment] 2023-02-26 19:38
Fixed in https://github.com/ohmyzsh/ohmyzsh/pull/11526. Get the fix with `omz update`.
