### ISSUE TITLE
No space found between folder name and command in visual studio code

### ISSUE THREAD

**Issue by darkb0ts** [ohmyzsh/ohmyzsh#12390] opened 2024-05-02 07:20 UTC
### Describe the bug

I am using Windows 10 and Git Bash for the terminal in Visual Studio Code, and it is working well in Git Bash terminal and WSL. However, the space between the folder name and command is not properly working in the Visual Studio Code Git terminal.

### Steps to reproduce

nil

### Expected behavior

It is working well in the regular Git Bash terminal and WSL. I am using the Visual Studio Code Integrated Terminal. However, when I make changes to PowerShell terminal, Git Bash, WSL, etc., if I use Git Bash where the shell is Zsh, the space is not found between the folder name and the command 

### Screenshots and recordings

![image](https://github.com/ohmyzsh/ohmyzsh/assets/113747108/6561ea2e-d4b4-4088-9a29-632125c8f4b9)
![image](https://github.com/ohmyzsh/ohmyzsh/assets/113747108/6ff90b54-8755-438d-b9b5-854357d04833)

### OS / Linux distribution

window 10

### Zsh version

5.9

### Oh My Zsh version

master (1b5503a)

### Terminal emulator

Integrated Terminal in vsc

### If using WSL on Windows, which version of WSL
Ubuntu-20.04

**Comment by carlosala** [comment] 2024-05-10 17:18
Duplicate of #12398

**Closed by carlosala** 2024-05-10 17:18 UTC
Labels: Bug
