### ISSUE TITLE
Pipenv plugin fails to autoactive from Ranger shell out...

### ISSUE THREAD

**Issue by apocalypse2012** [ohmyzsh/ohmyzsh#10959] opened 2022-05-27 18:56 UTC
### Describe the bug

Using OMZ Pipenv plugin to auto activate virtual environments on cd to piping project folders works correctly from the terminal, but it fails when shelling out from Ranger file browser. I get the error below generated when the virtual environment tries to activate...

### Steps to reproduce

Start ranger from a non-project directory.
Navigate to a project folder.
Shell out with the <SHIFT-'S'> shortcut.
Receive error and fail to enter the virtual environment for python.

### Expected behavior

The Shell out operation from ranger should open the shell and auto activate the virtual environment just like the 'cd' command does in the terminal.

### Screenshots and recordings

❯ ranger

[WARNING]: Console output during zsh initialization detected.

When using Powerlevel10k with instant prompt, console output during zsh
initialization may indicate issues.

You can:

  - Recommended: Change ~/.zshrc so that it does not perform console I/O
    after the instant prompt preamble. See the link below for details.

    * You will not see this error message again.
    * Zsh will start quickly and prompt will update smoothly.

  - Suppress this warning either by running p10k configure or by manually
    defining the following parameter:

      typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet

    * You will not see this error message again.
    * Zsh will start quickly but prompt will jump down after initialization.

  - Disable instant prompt either by running p10k configure or by manually
    defining the following parameter:

      typeset -g POWERLEVEL9K_INSTANT_PROMPT=off

    * You will not see this error message again.
    * Zsh will start slowly.

  - Do nothing.

    * You will see this error message every time you start zsh.
    * Zsh will start quickly but prompt will jump down after initialization.

For details, see:
https://github.com/romkatv/powerlevel10k/blob/master/README.md#instant-prompt

-- console output produced during zsh initialization follows --

Launching subshell in virtual environment...
Traceback (most recent call last):
  File "/usr/local/Cellar/pipenv/2022.1.8/libexec/bin/pipenv", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/Cellar/pipenv/2022.1.8/libexec/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/pipenv/2022.1.8/libexec/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/pipenv/2022.1.8/libexec/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/pipenv/2022.1.8/libexec/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/pipenv/2022.1.8/libexec/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/Cellar/pipenv/2022.1.8/libexec/lib/python3.10/site-packages/pipenv/vendor/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/Cellar/pipenv/2022.1.8/libexec/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/Cellar/pipenv/2022.1.8/libexec/lib/python3.10/site-packages/pipenv/cli/command.py", line 393, in shell
    do_shell(
  File "/usr/local/Cellar/pipenv/2022.1.8/libexec/lib/python3.10/site-packages/pipenv/core.py", line 2340, in do_shell
    shell.fork_compat(*fork_args)
  File "/usr/local/Cellar/pipenv/2022.1.8/libexec/lib/python3.10/site-packages/pipenv/shells.py", line 121, in fork_compat
    c.interact(escape_character=None)
  File "/usr/local/Cellar/pipenv/2022.1.8/libexec/lib/python3.10/site-packages/pipenv/vendor/pexpect/pty_spawn.py", line 788, in interact
    mode = tty.tcgetattr(self.STDIN_FILENO)
termios.error: (19, 'Operation not supported by device')

### OS / Linux distribution

Mac OS 12.4

### Zsh version

zsh 5.8 (x86_64-apple-darwin19.6.0)

### Terminal emulator

OhMyZshell

**Comment by j-ulrich** [comment] 2023-10-30 16:25
I guess this is a duplicate of https://github.com/ohmyzsh/ohmyzsh/issues/10600

**Comment by carlosala** [comment] 2023-10-31 16:29
Indeed, it is. Closing

**Closed by carlosala** 2023-10-31 16:29 UTC
