### ISSUE TITLE
Terminal2 remember history of Terminal1

### ISSUE THREAD

**Issue by tringuyen-yw** [ohmyzsh/ohmyzsh#9324] opened 2020-10-10 02:21 UTC
**Describe the bug**
Using macOS 10.15.x (Catalina) and iTerm2
When open several terminals (different tabs in iTerm2). The history of any terminal remember the commands typed in other terminals

**Expected behavior**
The history of each terminal must be unique to that terminal. 

**Self Check**
Seen on Stackoverflow someone suggested to add `unsetopt share_history` in ~/.zshrc
But maybe it is time to fix this bug for good.

**Desktop (please complete the following information):**

 - OS / Distro: macOS 10.15.x (Catalina)
 - ZSH Version: zsh 5.7.1 (x86_64-apple-darwin19.0)
 - Terminal emulator: iTerm2

**Comment by mcornella** [comment] 2020-10-10 10:38
Duplicate of #2537.

**Closed by mcornella** 2020-10-10 10:38 UTC

**Comment by mcornella** [comment] 2020-11-09 11:04
I reverted the change in 28ed2880c766eb5a360354fb71d597dbc07abaa0 based on user feedback. You can still fix that with `unsetopt share_history` in your zshrc file, after OMZ is sourced.
