### ISSUE TITLE
FAQ: 

### ISSUE THREAD

**Issue by ehackett00** [ohmyzsh/ohmyzsh#9828] opened 2021-04-14 15:20 UTC
Can't install.  
got the following message in iTerm:

Last login: Wed Apr 14 07:56:27 on console
/Users/macbacupfb11/.zshrc:49: unknown file attribute: z
[oh-my-zsh] Insecure completion-dependent directories detected:
drwxrwxr-x  3 macbacupfb11  admin  96 Apr 12 13:09 /usr/local/share/zsh
drwxrwxr-x  3 macbacupfb11  admin  96 Apr 12 13:13 /usr/local/share/zsh/site-functions

[oh-my-zsh] For safety, we will not load completions from these directories until
[oh-my-zsh] you fix their permissions and ownership and restart zsh.
[oh-my-zsh] See the above list for directories with group or other writability.

[oh-my-zsh] To fix your permissions you can do so by disabling
[oh-my-zsh] the write permission of "group" and "others" and making sure that the
[oh-my-zsh] owner of these directories is either root or your current user.
[oh-my-zsh] The following command may help:
[oh-my-zsh]     compaudit | xargs chmod g-w,o-w

[oh-my-zsh] If the above didn't help or you want to skip the verification of
[oh-my-zsh] insecure directories you can set the variable ZSH_DISABLE_COMPFIX to
[oh-my-zsh] "true" before oh-my-zsh is sourced in your zshrc file.

**Comment by ehackett00** [comment] 2021-04-14 15:23
I hope you can help.  I'm not  a programmer, just want to write a simple shell script.

Ed

**Comment by rwmitchell** [comment] 2021-04-14 16:10
You don’t need OMZ to write a simple shell script, just need an editor and a simple shell. I suggest bash.

**Comment by ehackett00** [comment] 2021-04-14 17:55
Any ideas about Oh My zsh?  Does it work?

Ed

**Comment by rwmitchell** [comment] 2021-04-14 18:31
Works great, use it on several OS X and Ubuntu systems.

**Comment by ehackett00** [comment] 2021-04-14 18:39
Any idea why it would not work on a standard Mac?

**Comment by rwmitchell** [comment] 2021-04-14 19:07
What words in the error msg do you need explained?  Look at line 40 of your .zshrc file and fix the permissions the directory.

**Comment by mcornella** [comment] 2021-04-15 07:13
Duplicate of https://github.com/ohmyzsh/ohmyzsh/issues/9592. If you don't care about it, you can just add `ZSH_DISABLE_COMPFIX=true` in your zshrc file, before Oh My Zsh is sourced.

**Closed by mcornella** 2021-04-15 07:13 UTC
