### ISSUE TITLE
MobaXTerm "xterm" terminal - END, HOME, DEL keys not working

### ISSUE THREAD

**Issue by Lopson** [ohmyzsh/ohmyzsh#4872] opened 2016-02-23 16:41 UTC
I don't know if putting this up on this project is the right way to go, but when I searched for tickets in this git, I saw similar ones, so here goes.

I have a CentOS 7.2.1511 machine, with ZSH 5.0.2 installed. I have the latest version of oh-my-zsh installed, along with the plugin ZSH-Syntax-Highlighting.

To connect to this machine, I use MobaXTerm (latest version). I connect to the CentOS machine through SSH and present the terminal as being of the "xterm" type (the default option for this SSH client).

The standard HOME, END, DEL, etc keys don't work out-of-the-box. I don't know how to make a Terminfo file for this case, and it seems like I shouldn't be needing to come up with a new Terminfo in the first place, seeing as MobaXTerm truly is an xterm terminal.

As such, I'd like to hear from you on this matter: is there some kind of known bug with this specific ZSH version that impedes MobaXTerm from working as intented?

Thanks for your time.

**Comment by apjanke** [comment] 2016-02-24 12:05
This is an ongoing issue with key bindings and terminfo in OMZ. #3061 is probably closest to your issue, and has some detailed information. You can see various other Home/End key binding issues in the list in #4344.

Thought we had Home/End cleared up for most terminals. Check that the character sequences MobaXTerm is sending for Home and End match those in the `xterm` terminfo entry.

**Comment by apjanke** [comment] 2016-02-24 12:35
I grabbed MobaXterm and tried it out. It looks like in application cursor mode, it's sending the character sequences for the VT220 editing keypad Home/End keys (`^[[1~` and `^[[4~`) instead of the PC style Home/End keys like xterm does (`^[OH` and `^[OF`). So its behavior doesn't match the `xterm` terminfo entry, at least for those keys. OMZ currently sets up bindings that rely on the terminfo entry.

Eventually OMZ may be able to handle this automatically, but in the mean time you'll have to configure a workaround.

If you can configure MobaXterm to send the normal xterm sequences, that should fix it.

PuTTY does the same thing in one of its configurations. Have a look at #3757, which is specifically about PuTTY. As a workaround, you could add this in your `~/.zshrc` file.

```
bindkey '^[[1~' beginning-of-line
bindkey '^[[4~' end-of-line
```

**Comment by apjanke** [comment] 2016-02-24 12:43
And looking at the Help > About MobaXterm dialog, it seems like that may actually be an embedded PuTTY that they're using for the SSH client. Could be why the behavior is similar.

<img width="656" alt="mobaxterm - about - annotated" src="https://cloud.githubusercontent.com/assets/2618447/13285733/4583cd8c-daca-11e5-9dc0-7997d3208119.png">

**Comment by Lopson** [comment] 2016-02-24 15:25
MobaXterm is based on PuTTY, somehow. From their documentation page:
> MobaXterm features a great terminal emulator based on the efficient PuTTY program (by Simon Tatham).

I've sent them an e-mail a while back asking them about this specific matter, but I haven't heard back from them yet. I've taken a look at the files the program generates in its configuration folder, but I haven't found a way of changing the characters it sends when I press the aforementioned keys.

In its configuration folder, I managed to snag two relevant files. One of them is a terminfo file; another is a inputrc file. Hopefully, they'll be useful for something!

[https://drive.google.com/file/d/0Bwi2temj01hfaEdCNTZ3T24xWFU/view?usp=sharing](MobaXterm Files.zip)

**Comment by apjanke** [comment] 2016-02-24 21:24
Ah! In that case, you can try setting `$TERM` to `putty` instead of `xterm`. Many systems have a `putty` terminfo entry which has Home/End entries that match putty's default behavior.

```
$ infocmp -1 putty  | grep 'khome\|end'
	kend=\E[4~,
	khome=\E[1~,
```

**Comment by Lopson** [comment] 2016-02-25 08:37
Setting the terminal type to `putty` doesn't set the correct keybindings for `HOME` and `END`, but the `DELETE` key is set properly.

Here's `showkey -a`'s output when pressing `HOME` and `END` by this order in MobaXterm:

```
» |root@Base 8:34:44| /root showkey -a
Press any keys - Ctrl-D will terminate this program

^[[H     27 0033 0x1b
         91 0133 0x5b
         72 0110 0x48
^[[F     27 0033 0x1b
         91 0133 0x5b
         70 0106 0x46
```

**Comment by apjanke** [comment] 2016-02-25 20:27
There's a catch here: OMZ switches the terminal into "application keypad" mode when the ZLE command line editor is active, using terminfo's `smkx`. (This is so it can use portable terminfo-based key bindings.) This causes the cursor keys (up/down/left/right/home/end) to send different character sequences. It's switched back in to normal/local mode after line editing ends. So the key sequences that `showkey` is seeing for home and end may not (and usually shouldn't) be the same ones that the zsh command line editor is seeing. When [I tried out MobaXterm](https://docs.google.com/spreadsheets/d/1Ue5gb2hLjz058QEtEXwaw8YR7QoVZpSYzbXQKrRcGKk/edit#gid=0), it respected keypad mode switching, and gave `^[[1~`/`^[[4~` in application mode. Could you test that too?

Instead of `showkey`, try using Ctrl-v ("verbatim") to see what sequences the keys are sending, without leaving the command line editor. Ctrl-v followed by another keystroke will just add the literal character sequence to the command line buffer, even if it's an escape or other control sequence.

Could also be that your setup is leaving the terminal in local cursor mode.

Maybe MobaXterm has their own documentation on configuring their terminal, though I didn't see much in my brief poking around at it.

(I wonder what version and configuration of Putty they're using. When I was doing that testing, I tested a few Putty configurations, and none of them gave `^[[H`/`^[[F`; the closest was `^[[H`/`^[Ow`. And it didn't respect keypad mode switches.)

**Comment by Lopson** [comment] 2016-02-26 08:35
Just did the CTRL+V test on the same CentOS 7 machine I've been using thus far; got, yet again, `^[[H` for Home and `^[[F` for End. Again, much like in my last post, I set the terminal type to `putty`.

If I use the default `xterm` terminal type, I get `^[[1~` for Home, `^[[4~` for End, and `^[[3~` for Delete.

I don't really understand this `smkx` business, so I'm not entirely sure how to help you any further. If more data is required in order to help you guys out, just say what needs to be done and I'll get on it!

**Comment by apjanke** [comment] 2016-02-26 09:21
Interesting.

Setting `$TERM` to whatever shouldn't affect this test – that should just change how programs interpret the character sequences, not what your terminal sends.

This makes me think that the "terminal type" setting in MobaXterm is affecting not just the `$TERM` it reports, but PuTTY's character sequence settings. Which makes sense: PuTTY can be configured in terms of what its cursor keys send to the server.

<img width="465" alt="putty cursor keys annotated" src="https://cloud.githubusercontent.com/assets/2618447/13348037/28e31a04-dc3f-11e5-9ea5-0c6a43718c34.png">

And in stock PuTTY, this is configured independent of the `$TERM` string that PuTTY defines for the server. This makes me think that maybe MobaXterm is conflating these things and presenting a simplified configuration sheet.

I dunno what to suggest you do right now. This really ought to be Not Your Problem.

To OMZ contributors: this looks to me like more support for ditching `[sr]mkx` and going with hacking in terminal-specific codes. Local-mode behavior is so much more regular.

> I don't really understand this smkx business, ...

Yeah, no reason you should. This is a bunch of historical stuff going all the way back to the sixties and the particular terminals that were built then. Sorry it's making your (and my) life harder.

**Comment by fabceolin** [comment] 2016-06-03 13:02
Try to set terminal type = byobu in xmobaterm

**Comment by hiephm** [comment] 2017-05-21 05:10
Suggestion from @Lopson works for me. After using `showkey -a` and know the key code, I just put these lines to .zshrc and it works perfect:
```
# Fix MobaXterm Home/End key with ZSH
bindkey '^[[H' beginning-of-line
bindkey '^[[F' end-of-line
```

**Comment by tldrblt** [comment] 2017-05-21 20:57
@hiephm:

I tried your suggestion with $TERM = putty and the Home and End keys still don't work (my showkey -a results are the same as yours).
I then tried with $TERM = linux and then the Home and End keys worked, but after every command I get the error message:
`zle-line-finish:echoti:1: no such terminfo capability: rmkx
zle-line-init:echoti:1: no such terminfo capability: smkx`

I think the errors are being caused by my OMZ theme prompt (theme = ys).

How did you get yours to work with $TERM = putty?

**Comment by goldeneye977** [comment] 2017-08-24 18:49
I fixed the issue by using an [AutoHotkey ](https://autohotkey.com )script. I wrote a small script that if the active window is MobaXTerm's, change the Home/End keys to "CTRL+A/CTRL+E" respectively. Here's the script if anyone wants to try it out:

#If WinActive("ahk_class TMobaXtermForm") 
{
Home::    
   #UseHook Off
   Send ^A
   #UseHook   
   return

End::
   #UseHook Off
   Send ^E
   #UseHook   
   return
}
#If

**Comment by tldrblt** [comment] 2017-08-25 08:56
Thanks @goldeneye977 . Your AutoHotkey script works for me as well. My time in the terminal just got a little bit nicer thanks to you. Cheers.

**Comment by goldeneye977** [comment] 2017-08-25 17:50
BTW @tldrblt, the script has a minor issue. If u detach the MobaXTerm window, it's won't work there because the window's ahk_class changes. This can be fixed by using "ahk_exe MobaXterm.exe" instead. Hope that helps!

**Comment by rb1980** [comment] 2017-10-13 22:57
Wow @goldeneye977 I literally spent hours trying to get ALL the other suggestions floating around out there working till I came across your AutoHotKey script. Since I was already using AHK, literally a copy/paste/reload, and 10 seconds later, I am a happy camper. +1 +1 +1

**Comment by sirhaplo** [comment] 2019-05-27 14:14
> # Fix MobaXterm Home/End key with ZSH
> bindkey '^[[H' beginning-of-line
> bindkey '^[[F' end-of-line



> Suggestion from @Lopson works for me. After using `showkey -a` and know the key code, I just put these lines to .zshrc and it works perfect:
> 
> ```
> # Fix MobaXterm Home/End key with ZSH
> bindkey '^[[H' beginning-of-line
> bindkey '^[[F' end-of-line
> ```
> 
> Edit: $TERM need to be `linux` or `putty` since `xterm` will not work.

I used this solution, but i **wrote manually** `linux` in the terminal select box of Mobaxterm

**Comment by rebeccasf** [comment] 2019-08-05 08:19
> > # Fix MobaXterm Home/End key with ZSH
> > bindkey '^[[H' beginning-of-line
> > bindkey '^[[F' end-of-line
> 
> > Suggestion from @Lopson works for me. After using `showkey -a` and know the key code, I just put these lines to .zshrc and it works perfect:
> > ```
> > # Fix MobaXterm Home/End key with ZSH
> > bindkey '^[[H' beginning-of-line
> > bindkey '^[[F' end-of-line
> > ```
> > 
> > 
> > Edit: $TERM need to be `linux` or `putty` since `xterm` will not work.
> 
> I used this solution, but i **wrote manually** `linux` in the terminal select box of Mobaxterm

This works!

**Comment by rupingmo** [comment] 2020-02-04 00:50
From MobaXterm window, click "Settings", select "X11", and then deselect "Unix-compatible keyboard". It works for this way.

**Comment by pytimer** [comment] 2020-07-06 01:43
> Suggestion from @Lopson works for me. After using `showkey -a` and know the key code, I just put these lines to .zshrc and it works perfect:
> 
> ```
> # Fix MobaXterm Home/End key with ZSH
> bindkey '^[[H' beginning-of-line
> bindkey '^[[F' end-of-line
> ```
> 
> Edit: $TERM need to be `linux` or `putty` since `xterm` will not work.

It works for me!

**Comment by jbroq** [comment] 2020-08-10 12:44
> 
> 
> > # Fix MobaXterm Home/End key with ZSH
> > bindkey '^[[H' beginning-of-line
> > bindkey '^[[F' end-of-line
> 
> > Suggestion from @Lopson works for me. After using `showkey -a` and know the key code, I just put these lines to .zshrc and it works perfect:
> > ```
> > # Fix MobaXterm Home/End key with ZSH
> > bindkey '^[[H' beginning-of-line
> > bindkey '^[[F' end-of-line
> > ```
> > 
> > 
> > Edit: $TERM need to be `linux` or `putty` since `xterm` will not work.
> 
> I used this solution, but i **wrote manually** `linux` in the terminal select box of Mobaxterm

I works for me too. Thanks

**Comment by 1Mark** [comment] 2022-04-06 19:19
Any chance getting a fix for this?

**Comment by 1Mark** [comment] 2022-04-06 19:24
The following works with `xterm-256color`
```
bindkey '^[[H' beginning-of-line
bindkey '^[[F' end-of-line
```

**Comment by miku86** [comment] 2022-08-27 15:17
Just to summarize this for people like me, who needed 2h of internet search to fix this with xterm and zsh:

1. Open a terminal and run `showkey -a`
2. Hit the key, e.g. `Home` and look for code like `^[[H`
3. Add a `bindkey` instruction for each key to your `.zshrc` file

---

My `.zshrc` file now looks like this:

```
bindkey '^[[H' beginning-of-line # Home
bindkey '^[[F' end-of-line # End
bindkey '^[[2~' overwrite-mode # Insert
bindkey '^[[3~' delete-char # Delete
bindkey '^?' backward-delete-char # Backspace
```

The comment at the end of each line (starting with a `#`) is just that I know which key it is for.

**Comment by MrSunny-M** [comment] 2022-11-04 14:45
> Just to summarize this for people like me, who needed 2h of internet search to fix this with xterm and zsh:
> 
> 1. Open a terminal and run `showkey -a`
> 2. Hit the key, e.g. `Home` and look for code like `^[[H`
> 3. Add a `bindkey` instruction for the key to your `.zshrc` file
> 4. Do step 2 and 3 for each key you want to change
> 
> My `.zshrc` file now looks like this:
> 
> ```
> bindkey '^[[H' beginning-of-line # Home
> bindkey '^[[F' end-of-line # End
> bindkey '^[[2~' overwrite-mode # Insert
> bindkey '^[[3~' delete-char # Delete
> bindkey '^?' backward-delete-char # Backspace
> ```
> 
> The comment at the end of each line (starting with a `#`) is just that I know which key it is for.

This is the best solution so far !!

**Comment by carlosala** [comment] 2022-11-04 15:33
Let's close then, thanks!☺️

**Closed by carlosala** 2022-11-04 15:33 UTC
Labels: Topic: bindkey
