### ISSUE TITLE
[git plugin] git stash drop <tab> fails

### ISSUE THREAD

**Issue by EHJ-52n** [ohmyzsh/ohmyzsh#9264] opened 2020-09-18 12:06 UTC
**Describe the bug**
I am entering in a git repo `git stash drop` <kbd>tab</kbd> and receive an error message and not a list of the available stash entries:

```
_arguments:comparguments:325: invalid argument: _git-notes
_git-stash:88: command not found: (-q --quiet)-q[suppress all output]
_arguments:comparguments:325: invalid argument: _git-notes
_git-stash:88: command not found: (-q --quiet)-q[suppress all output]
_arguments:comparguments:325: invalid argument: _git-notes
```

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Enable this plugin 'git'
2. Create a new repository with an empty file.
3. Commit this file.
4. Change the file
5. Stash the changes
6. Try to drop the change and use <tab> completion after `git stash drop`
7. See error

**Expected behavior**
I expected a list of available stashes and the ability to select one of the entries by continuous tabbing. 

**Self Check**

- [ ] Have you tried reaching out on the [Discord server](https://discord.gg/ohmyzsh)? 
  This can help cut down on filling up issues. We always have a few people
  online that are in a variety of timezones that are willing to help you!

- [x] Also searching existing [GitHub Issues](https://github.com/ohmyzsh/ohmyzsh/issues?q=) might help you get quicker support

**Desktop (please complete the following information):**

 - OS / Distro: Ubuntu 20.04.1 LTS core-11.1.0ubuntu2-noarch:printing-11.1.0ubuntu2-noarch:security-11.1.0ubuntu2-noarch
 - Latest ohmyzsh update?: Yes: 2020-09-14T19:32:23+01:00
 - ZSH Version: 5.8 (x86_64-ubuntu-linux-gnu)
 - Terminal emulator: GNOME Terminal 3.36.2 using VTE 0.60.3 +BIDI +GNUTLS +ICU +SYSTEMD

**Additional context**

- git version 2.25.1
- Autocompletion with `git stash pop`<kbd>tab</kbd> is working as expected.

**Comment by mcornella** [comment] 2020-09-18 13:46
Duplicate of https://github.com/ohmyzsh/ohmyzsh/issues/8956. This was a bug in zsh's git completion, fixed in https://github.com/zsh-users/zsh/commit/754658aff38e1bdf487c58bec6174cbecd019d11 ([mailing list ref.](https://www.zsh.org/mla/workers/2020/msg00915.html)).

It should probably be fixed in the next zsh version, whenever that comes out. In the meantime, you can manually look for the `_git` file and modify the `_git-stash` function so that [the extra `_git-notes` line is removed](https://github.com/zsh-users/zsh/commit/754658aff38e1bdf487c58bec6174cbecd019d11#diff-64ad373b9ca8d63aba051ba03245fd9eR1812). You'll find the `_git` file by running `ls -l ${^fpath}/_git(N)`. 

Another solution is to override the whole `_git-stash` function in your zshrc file. This should be the whole thing:
```zsh
_git-stash () {
  local curcontext=$curcontext state line ret=1
  declare -A opt_args
  local -a save_arguments

  save_arguments=(
    '(-p --patch -a --all -u --include-untracked)'{-p,--patch}'[interactively select hunks from diff between HEAD and working tree to stash]'
    '(-k --keep-index --no-keep-index)'{-k,--keep-index}'[all changes already added to the index are left intact]'
    '(-k --keep-index)--no-keep-index[all changes already added to the index are undone]'
    '(-q --quiet)'{-q,--quiet}'[suppress all output]'
    '(-p --patch -a --all -u --include-untracked)'{-u,--include-untracked}'[include untracked files]'
    '(-p --patch -a --all -u --include-untracked)'{-a,--all}'[include ignored files]'
  )

  _arguments -C \
    '*::: :->args' \
    '(-m --message)'{-m,--message}'[specify stash description]' \
    ${save_arguments//#\(/(* } && ret=0

  if [[ -n $state ]]; then
    if (( CURRENT == 1 )); then
      local -a commands

      commands=(
        {push,save}:'save your local modifications to a new stash'
        list:'list the stashes that you currently have'
        show:'show the changes recorded in the stash as a diff'
        pop:'remove and apply a single stashed state from the stash list'
        apply:'apply the changes recorded in the stash'
        branch:'branch off at the commit at which the stash was originally created'
        clear:'remove all the stashed states'
        drop:'remove a single stashed state from the stash list'
        create:'create a stash without storing it in the ref namespace'
      )

      _describe -t commands command commands && ret=0
    else
      curcontext=${curcontext%:*}-$line[1]:
      compset -n 1

      case $line[1] in
        (save)
          _arguments -S $endopt \
            $save_arguments \
            ':: :_guard "([^-]?#|)" message' && ret=0
          ;;
        (push)
          _arguments -S $endopt \
            $save_arguments \
	    '(-m --message)'{-m,--message}'[specify stash description]' \
            ':: :__git_modified_files' && ret=0
          ;;
        (--)
            __git_modified_files
          ;;
        (list)
          local -a log_options revision_options
          __git_setup_log_options
          __git_setup_revision_options

          _arguments -s \
            $log_options \
            $revision_options && ret=0
          ;;
        (show)
          local diff_options
          __git_setup_diff_options

          _arguments -S -s $endopt \
            $diff_options \
            ':: :__git_stashes' && ret=0
          ;;
        (pop|apply)
          _arguments -S $endopt \
            '--index[try to reinstate the changes added to the index as well]' \
            '(-q --quiet)'{-q,--quiet}'[suppress all output]' \
            ':: :__git_stashes' && ret=0
          ;;
        (branch)
          _arguments \
            ': :__git_guard_branch-name' \
            ':: :__git_stashes' && ret=0
          ;;
        (clear)
          _nothing
          ;;
        (drop)
          _arguments -S $endopt \
            '(-q --quiet)'{-q,--quiet}'[suppress all output]' \
            ':: :__git_stashes' && ret=0
          ;;
        (create)
          _nothing
          ;;
        (*)
          _nothing
          ;;
      esac
    fi
  fi

  return ret
}
```

**Closed** 2020-09-18 13:47 UTC

**Comment by EHJ-52n** [comment] 2020-09-21 10:36
Sorry for not finding the duplicate.

The manual fix outlined by @mcornella to use zsh-users/zsh@754658aff38e1bdf487c58bec6174cbecd019d11 worked for me.

**Comment by mcornella** [comment] 2021-11-05 16:06
Duplicates: #8956 #10156

If you've come across this issue, here's the workaround until a new Zsh version is released: https://github.com/ohmyzsh/ohmyzsh/issues/10156#issuecomment-912399945.
