### ISSUE TITLE
npm autocomplete plugin seems to be not working

### ISSUE THREAD

**Issue by ataube** [ohmyzsh/ohmyzsh#8665] opened 2020-02-21 12:55 UTC
**Describe the bug**
Running `npm run <tab>` does not autocomplete the npm run scripts. Instead there is a problem reported in the internal npm [completion](https://github.com/npm/cli/blob/latest/lib/completion.js#L80) module. I'm not sure if I'm addressing this issue at the right place here, since the the ohmyzsh npm plugin uses `npm completion` to generate the autocompletion script. However the plugin stopped working for me with the most recent ohmyzsh updates. 

I also tried the following things
* reset the completion settings https://github.com/ohmyzsh/ohmyzsh/wiki/Troubleshooting#completion-problems
* removed the `npm_completion` from the `.oh-my-zsh/cache`. 

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Enable this plugin 'npm'
2. Create new folder
3. Init new nodejs project `npm init`
4. Run `npm run <tab>`
5. Nothing gets shown, instead a npm error gets locked in `~/.npm/_logs`

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/Users/andreas.taube/.nvm/versions/node/v12.16.1/bin/node',
1 verbose cli   '/Users/andreas.taube/.nvm/versions/node/v12.16.1/bin/npm',
1 verbose cli   'completion',
1 verbose cli   '--',
1 verbose cli   'npm',
1 verbose cli   'run'
1 verbose cli ]
2 info using npm@6.13.4
3 info using node@v12.16.1
4 verbose stack TypeError: Cannot read property 'length' of undefined
4 verbose stack     at EventEmitter.completion (/Users/andreas.taube/.nvm/versions/node/v12.16.1/lib/node_modules/npm/lib/completion.js:80:23)
4 verbose stack     at Object.commandCache.<computed> (/Users/andreas.taube/.nvm/versions/node/v12.16.1/lib/node_modules/npm/lib/npm.js:156:13)
4 verbose stack     at EventEmitter.<anonymous> (/Users/andreas.taube/.nvm/versions/node/v12.16.1/lib/node_modules/npm/bin/npm-cli.js:131:30)
4 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:79:11)
5 verbose cwd /Users/andreas.taube/dev/collectai/claims
6 verbose Darwin 18.7.0
7 verbose argv "/Users/andreas.taube/.nvm/versions/node/v12.16.1/bin/node" "/Users/andreas.taube/.nvm/versions/node/v12.16.1/bin/npm" "completion" "--" "npm" "run"
8 verbose node v12.16.1
9 verbose npm  v6.13.4
10 error Cannot read property 'length' of undefined
11 verbose exit [ 1, true ]
```
**Expected behavior**
The autocomplete should kick in and show the `test` run script

**Desktop (please complete the following information):**
 - OS / Distro: macOS
 - Latest ohmyzsh Update?: yes `bc9fe742`
 - ZSH Version: 5.8
 - Terminal emulator iTerm2

**Comment by mcornella** [comment] 2020-02-21 15:31
This looks like an npm bug. Can you post the contents of `$ZSH/cache/npm_completion`?

**Comment by ataube** [comment] 2020-02-22 20:00
@mcornella Thanks for looking into this, the `npm_completion` has the following content.

```sh
###-begin-npm-completion-###
#
# npm command completion script
#
# Installation: npm completion >> ~/.bashrc  (or ~/.zshrc)
# Or, maybe: npm completion > /usr/local/etc/bash_completion.d/npm
#

if type complete &>/dev/null; then
  _npm_completion () {
    local words cword
    if type _get_comp_words_by_ref &>/dev/null; then
      _get_comp_words_by_ref -n = -n @ -n : -w words -i cword
    else
      cword="$COMP_CWORD"
      words=("${COMP_WORDS[@]}")
    fi

    local si="$IFS"
    IFS=$'\n' COMPREPLY=($(COMP_CWORD="$cword" \
                           COMP_LINE="$COMP_LINE" \
                           COMP_POINT="$COMP_POINT" \
                           npm completion -- "${words[@]}" \
                           2>/dev/null)) || return $?
    IFS="$si"
    if type __ltrim_colon_completions &>/dev/null; then
      __ltrim_colon_completions "${words[cword]}"
    fi
  }
  complete -o default -F _npm_completion npm
elif type compdef &>/dev/null; then
  _npm_completion() {
    local si=$IFS
    compadd -- $(COMP_CWORD=$((CURRENT-1)) \
                 COMP_LINE=$BUFFER \
                 COMP_POINT=0 \
                 npm completion -- "${words[@]}" \
                 2>/dev/null)
    IFS=$si
  }
  compdef _npm_completion npm
elif type compctl &>/dev/null; then
  _npm_completion () {
    local cword line point words si
    read -Ac words
    read -cn cword
    let cword-=1
    read -l line
    read -ln point
    si="$IFS"
    IFS=$'\n' reply=($(COMP_CWORD="$cword" \
                       COMP_LINE="$line" \
                       COMP_POINT="$point" \
                       npm completion -- "${words[@]}" \
                       2>/dev/null)) || return $?
    IFS="$si"
  }
  compctl -K _npm_completion npm
fi
###-end-npm-completion-###
```

Note: The npm completion module did not change since 2 years, that why I ruled it out so far.

**Comment by mcornella** [comment] 2020-02-24 17:54
Hmm maybe this is because we changed OMZ to automatically load `bashcompinit` when starting up, which makes zsh follow the first conditional (`type complete`). Try commenting out the [`autoload -Uz bashcompinit` line in `lib/completion.zsh`](https://github.com/ohmyzsh/ohmyzsh/blob/bc9fe7423f5d8c639b208ebb9a7dbfce078bfd9b/lib/completion.zsh#L76), and restarting the terminal.

**Comment by mcornella** [comment] 2020-02-24 18:01
Yes, that seems to be the issue. In theory, `bashcompinit` should be able to seamlessly run bash completion scripts, but the npm one seems to be failing for some reason.

**Comment by ataube** [comment] 2020-02-24 18:30
Hm, I just tested the steps you described in https://github.com/ohmyzsh/ohmyzsh/issues/8665#issuecomment-590465004. Unfortunately it is not fixing it. Something I forgot to mention, the autocomplete works if you type at least one letter of a npm script listed in the package.json. If the npm run command is empty it fails.

**Comment by mcornella** [comment] 2020-02-24 18:35
It is due to that; it's important to restart the shell, otherwise the effects of the `bashcompinit` call still linger. Anyway, here's what I've found

These are the traces of both completion functions (emulated bash vs native zsh)

This using the emulated bash completion function:
```
+_npm_completion:1> local words cword
+_npm_completion:2> type _get_comp_words_by_ref
+_npm_completion:5> cword=2
+_npm_completion:6> words=( npm run )
+_npm_completion:9> local si=$' \t\C-M\n\C-@'
+_npm_completion:10> IFS=$'\n' COMPREPLY=
+_npm_completion:10> COMP_CWORD=2 COMP_LINE='npm run ' COMP_POINT=8 npm completion -- npm run
+_npm_completion:10> IFS=$'\n' COMPREPLY=( )
+_npm_completion:14> return 1
```

This using the native zsh completion function:
```
+_npm_completion:1> local si=$' \t\C-M\n\C-@'
+_npm_completion:2> COMP_CWORD=2 COMP_LINE='npm run ' COMP_POINT=0 npm completion -- npm run ''
+_npm_completion:2> compadd -- build dev lint start test test:watch
+_npm_completion:7> IFS=$' \t\C-M\n\C-@'
```

The only difference in the call to `npm completion` is the extra `''` argument at the end of the call. Let's look at the completion functions side by side:

**Emulated bash:**
```sh
_npm_completion () {
  local words cword
  if type _get_comp_words_by_ref &>/dev/null; then
    _get_comp_words_by_ref -n = -n @ -n : -w words -i cword
  else
    cword="$COMP_CWORD"
    words=("${COMP_WORDS[@]}")
  fi

  local si="$IFS"
  IFS=$'\n' COMPREPLY=($(COMP_CWORD="$cword" \
                          COMP_LINE="$COMP_LINE" \
                          COMP_POINT="$COMP_POINT" \
                          npm completion -- "${words[@]}" \
                          2>/dev/null)) || return $?
  IFS="$si"
  if type __ltrim_colon_completions &>/dev/null; then
    __ltrim_colon_completions "${words[cword]}"
  fi
}
```

**Native zsh:**
```zsh
_npm_completion() {
  local si=$IFS
  compadd -- $(COMP_CWORD=$((CURRENT-1)) \
                COMP_LINE=$BUFFER \
                COMP_POINT=0 \
                npm completion -- "${words[@]}" \
                2>/dev/null)
  IFS=$si
}
```

The calls are the same, the only difference is in the emulated bash one it uses `${COMP_WORDS[@]}` to get the words typed in the command line:
```
words=("${COMP_WORDS[@]}")
```
If I modify the functions, I can look at how many elements the words array has in both, which gives me 2 elements for the `$COMP_WORDS` array in the bash function, 3 elements in the `$words` array in the zsh function.

**This looks like a bug in zsh implementation**: it should preserve the last element even if it is an empty string. And turns out I'm right.

I traced it back to the `_bash_complete` function, which treats the `$words` array very carelessly. If I change the [COMP_WORDS assignment line](https://github.com/zsh-users/zsh/blob/a6a1b28b9807c8c19d5fef424a86b86ddf33bc7f/Completion/bashcompinit#L13) like so:
```diff
-  COMP_WORDS=( $words )
+  COMP_WORDS=( "${words[@]}" )
```
Then the bash function works correctly, like it should:
```
+_npm_completion:1> local words cword
+_npm_completion:2> type _get_comp_words_by_ref
+_npm_completion:5> cword=2
+_npm_completion:6> words=( npm run '' )
+_npm_completion:9> local si=$' \t\C-M\n\C-@'
+_npm_completion:10> IFS=$'\n' COMPREPLY=+_npm_completion:10> COMP_CWORD=2 COMP_LINE='npm run ' COMP_POINT=8 npm completion -- npm run ''
+_npm_completion:10> IFS=$'\n' COMPREPLY=( build dev lint start test test:watch )
+_npm_completion:15> IFS=$' \t\C-M\n\C-@'
+_npm_completion:16> type __ltrim_colon_completions
```

## Summary

The quick TL;DR is that there's a bug in `bashcompinit`. The problem is that it'll have to be fixed in a newer zsh version, making the problem still present in older versions. 

So a quick fix is to remove the `bashcompinit` call in `lib/completion.zsh`, but if a plugin you load before the npm one also calls `bashcompinit` the problem will persist.

Another option is to patch the npm plugin so that it always loads the native zsh function. I'll think about it; until then, here's me posting the findings.

**Comment by ataube** [comment] 2020-02-24 18:49
Alright, at least we found the root cause; thanks for the detailed analyses and accepting it as a bug. Let me know if I can support you testing something.

**Comment by mcornella** [comment] 2020-02-25 21:15
The fix was commited yesterday: https://github.com/zsh-users/zsh/commit/f7c6a0008b105c945ba3935d7ecb8c87fe0cd0e5. It will probably make it into 5.8.1. 

In the meantime, I've submitted #8679, which will fix your problem. Still needs to be checked whether old npm versions will still work with that.

**Closed** 2020-02-25 21:23 UTC
Labels: Area: plugin, Topic: completion, Type: bug
