### ISSUE TITLE
Tab completion is eating above lines when using af-magic theme

### ISSUE THREAD

**Issue by zachscheider** [ohmyzsh/ohmyzsh#8497] opened 2019-12-26 15:54 UTC
**Describe the bug**
Tab completion is eating above lines when using af-magic theme.

**To Reproduce**
1. Use the af-magic theme
2. Press tab for autocomplete at the terminal
3. The line immediately above was deleted

**Expected behavior**
Tab completion should not delete any lines from the display.

**Screenshots or recordings**
#### Before Tab:
```
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
~/.oh-my-zsh(tab-complete-af-magic) » date                                                                                                                                                zach@zach-desktop
Thu Dec 26 09:53:46 EST 2019
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
~/.oh-my-zsh(tab-complete-af-magic) »

```
#### After Tab:
```
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
~/.oh-my-zsh(tab-complete-af-magic) » date                                                                                                                                                zach@zach-desktop
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
~/.oh-my-zsh(tab-complete-af-magic) » ls themes/
```

#### Before Tab:
```
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
~/.oh-my-zsh(tab-complete-af-magic*) » source ~/.zshrc                                                                                                                                    zach@zach-desktop
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
~/.oh-my-zsh(tab-complete-af-magic*) » date                                                                                                                                               zach@zach-desktop
Thu Dec 26 09:56:50 EST 2019
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
~/.oh-my-zsh(tab-complete-af-magic*) » 

```
#### After Tab:
```
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
~/.oh-my-zsh(tab-complete-af-magic*) » source ~/.zshrc                                                                                                                                    zach@zach-desktop
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
~/.oh-my-zsh(tab-complete-af-magic*) » date                                                                                                                                               zach@zach-desktop
Thu Dec 26 09:56:50 EST 2019
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
~/.oh-my-zsh(tab-complete-af-magic*) » ls themes/ 
```

**System:**
 - OS: Ubuntu
 - zsh 5.4.2 (x86_64-ubuntu-linux-gnu)

**Additional context**
I started seeing the error after [this change](https://github.com/ohmyzsh/ohmyzsh/commit/17f4cfca99398cb5511557b8515a17bf1bf2948a).  
It looks like the root cause was introduced by [zsh 5.3](http://www.zsh.org/mla/workers/2017/msg00021.html) when using multiline prompts.
It would be nice to fix here for compatibility. I have a solution and will open a pull request.

**Comment by mcornella** [comment] 2019-12-26 21:27
Duplicate of #5765.

**Comment by zachscheider** [comment] 2019-12-27 00:41
I saw that and this is actually a separate issue. They both have a similar effect, but have a different cause. This issue and the pull request I opened to fix it are specific to the af-magic theme that I use, not COMPLETION_WAITING_DOTS. Can you reopen this because there is a separate cause?

**Comment by mcornella** [comment] 2019-12-27 11:52
What other plugins are you using? This must be a `zle redisplay` issue.

**Comment by mcornella** [comment] 2019-12-28 16:51
Confirmed to be due to `COMPLETION_WAITING_DOTS` (https://github.com/ohmyzsh/ohmyzsh/pull/8498#issuecomment-569367114). Closing as duplicate of #5765.

**Closed by mcornella** 2019-12-28 16:51 UTC
Labels: Area: theme, Topic: completion, Type: bug
