### ISSUE TITLE
Please store configuration in ~/.config/oh-my-sh

### ISSUE THREAD

**Issue by bjourne** [ohmyzsh/ohmyzsh#10817] opened 2022-04-01 08:38 UTC
### Describe the bug

The practice of polluting users' home directories with dotfiles and dotdirectories is [nowadays discouraged](https://0x46.net/thoughts/2019/02/01/dotfile-madness/) on Linux. Oh My Zsh should follow the XDG spec which for most users means putting the config in ~/.config/oh-my-sh.

### Steps to reproduce

none

### Expected behavior

~/.config/oh-my-sh filled

### OS / Linux distribution

Arch

### Zsh version

5.8.1

### Oh My Zsh version

master (dbadfa08)

### Terminal emulator

konsole

**Comment by bjourne** [comment] 2022-04-02 11:16
[Spec says](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html):

> $XDG_DATA_HOME defines the base directory relative to which user-specific data files should be stored. If $XDG_DATA_HOME is either not set or empty, a default equal to $HOME/.local/share should be used.

> $XDG_CONFIG_HOME defines the base directory relative to which user-specific configuration files should be stored. If $XDG_CONFIG_HOME is either not set or empty, a default equal to $HOME/.config should be used.

So if `~/.oh-my-sh` is data it should go to `~/.local/share/oh-my-sh`.

**Comment by mcornella** [comment] 2022-04-02 20:41
This is a feature request, not a bug. Duplicate of #9543.

**Closed by mcornella** 2022-04-02 20:41 UTC
Labels: Bug
