### ISSUE TITLE
common-aliases causes extra returns

### ISSUE THREAD

**Issue by vstthomas** [ohmyzsh/ohmyzsh#11965] opened 2023-10-13 03:10 UTC
### Describe the bug

When opening the terminal, the prompt typically looks like this:

```sh
Last login: Thu Oct 12 19:54:00 on ttys000
user@host ~ % 
user@host ~ % 
user@host ~ % 
user@host ~ % 
```

After editing `~/.zshrc` and adding [common-aliases] to the plugins, the terminal now adds some unnecessary returns:

```sh
Last login: Thu Oct 12 19:56:40 on ttys002
                                                                                                                                                                          

user@host ~ %  # this one naturally occurs from opening the terminal
                                                                                                                                                                          

user@host ~ % # this one is me just hitting the ENTER key
                                                                                                                                                                          

user@host ~ % 
```

It's worth noting that this does NOT happen in iTerm2. 

### Steps to reproduce

1. Enable plugin: `common-aliases`
2. `:w ~/.zshrc`
3. Open a new Terminal window
4. Fail: the additional lines are introduced

### Expected behavior

The prompt looks as preferred:

```sh
Last login: Thu Oct 12 19:54:00 on ttys000
user@host ~ % 
user@host ~ % 
user@host ~ % 
user@host ~ % 
```

### OS / Linux distribution

macOS/13.5.2 (Venura)

### Zsh version

5.9

### Oh My Zsh version

master (b1821a2)

### Terminal emulator

Terminal.app

### If using WSL on Windows, which version of WSL

None

### Additional context

Thank you!

**Comment by mcornella** [comment] 2023-10-13 07:35
Hi Todd, thanks for the report! I'm not able to reproduce this issue using either `robbyrussell` or no zsh theme, and the `common-aliases` theme does not set any variables, functions or prompts that could be causing this as far as I can tell.

Could you tell us which theme you are using, and preferably the rest of the `.zshrc` file? Thanks!

**Comment by todd-dsm** [comment] 2023-10-13 16:19
oh no, it's already sounding like a compound problem :expressionless:

To answer your question: no theme; I've only disabled the default:

```sh
% grep -B1 '^ZSH_THEME' ~/.zshrc 
#ZSH_THEME="robbyrussell"
ZSH_THEME=""
```

I'll keep digging for the other part of the issue. I'll likely have to do a reset and enable custom settings one at a time. I can do some testing over the weekend. 

_**Is there a quick/easy/recommended way to reset omzsh back to defaults?**_

**Comment by mcornella** [comment] 2023-10-13 17:08
You could use docker if you have it installed:
```sh
docker run -it ohmyzsh/ohmyzsh zsh
```
Note that it comes bare-bones, without any extra tooling, and it's using Ubuntu so it's unlikely that you'll be able to reproduce it.

You can also copy the `templates/zshrc.zsh-template` file into the `.zshrc` after backing it up, however this assumes that you don't have any other changes made, like to `.zshenv`, `.zprofile`, or other global files installed by your OS.

In your case there may be other integrations that make this issue happen combined with the `common-aliases` plugin. The fastest way to see the full rc files is creating a log file of the startup:
```sh
zsh -xvlic exit &>~/omz-debug.log
```
and sharing this over at logs@ohmyz.sh

FWIW, I have tested your repro with Terminal.app on my macOS 13.6 VM (Ventura) and I was unable to reproduce it as well.

**Comment by mcornella** [comment] 2023-10-19 18:51
I'm going to close this as not reproducible, please feel free to reopen anytime if you have logs or different reproduction steps. Thanks!

**Closed by mcornella** 2023-10-19 18:51 UTC
Labels: Status: not reproducible

**Comment by todd-dsm** [comment] 2023-10-21 19:01
Finally had a chance to go through this. I ran the command to output the logs and I got lucky; right at the top of the first log was a mis-configuration (on my part) in `~/.zprofile`

```sh
+/Users/USERNAME/.zprofile:3> [ -f /Users/USERNAME/.zshrc ']'
+/Users/USERNAME/.zprofile:4> . /Users/USERNAME/.zshrc
```

Some automation gone wild 😬  Anyway, all fixed...

And now I know how to generate logs  😀  thank you @mcornella
