### ISSUE TITLE
Respect ZDOTDIR across all Oh My Zsh

### ISSUE THREAD

**Issue by Shea690901** [ohmyzsh/ohmyzsh#6523] opened 2018-01-02 00:46 UTC
I´ve noticed that **every** plugin referencing any zsh startup file assumes, that those are located in the users home directory, disregarding the possibility of setting ```ZDOTDIR``` to something else within ```/etc/zshenv```...
In fact there are only 3 files (lib/compfix.zsh, lib/diagnostics.zsh and oh-my-zsh.sh) that use ```ZDOTDIR```, while there are 45(!!!) files (not counting any readme's) referencing ```.zshrc```

**Comment by natemaia** [comment] 2018-01-19 22:53
I would also like to see this addressed.

I've forked my own and patched a number of plugins for just this reason

**Comment by fox91** [comment] 2019-01-04 10:07
Duplicate of #7052?

**Comment by Shea690901** [comment] 2019-04-22 18:53
Not really, that's only 1 out of those 45 modules....

**Comment by robbyrussell** [comment] 2023-10-13 21:37
Any chance someone would be keen to work on a PR for this?

**Comment by carlosala** [comment] 2023-10-16 10:10
I'd say this is mostly done, at least in the `oh-my-zsh.sh`, `lib/` and `tools/`.
Plugins might still rely on `~/.zshrc`.
We'd kindly accept PRs fixing it!
Thanks!

**Closed by carlosala** 2023-10-16 10:10 UTC
Labels: Area: plugin, Area: core, Enhancement
