### ISSUE TITLE
No-input upgrade reminder

### ISSUE THREAD

**Issue by blagh** [ohmyzsh/ohmyzsh#12587] opened 2024-07-30 16:38 UTC
### If the feature solves a problem you have, specify it here.

oh-my-zsh will display a "Would you like to upgrade" prompt when a new shell is opened (mostly fine), but if you're opening a shell with some built-in initialization commands (for example, with something like [`poetry shell`](https://github.com/python-poetry/poetry/blob/2e3a42174ce247a9b18250f4ad683e77ba1b1579/src/poetry/utils/shell.py#L123-L126)) this steals the first character of the next command which will likely cause the script to fail in a confusing and largely non-Googleable way. 

### Describe the proposed feature.

Only display a reminder for available updates, do not prompt for input.

### Describe alternatives you've considered

- I'd rather not turn on automatic updates
- `omz update` fixes the issue of course, but I was stuck for a good bit trying to figure out what the heck a `mulate` command is supposed to be.

**Comment by mcornella** [comment] 2024-07-30 21:25
Hi Kannele, thanks for reporting this!

We have the reminder mode for this use case, you can see it documented in [^1] and [^2].

We also have some logic to detect input but it seems it didn't work here. Could you provide a self-contained repro (with setup steps) to see what's happening and why it's not working properly? 

Thanks! 

[^1]: https://github.com/ohmyzsh/ohmyzsh?tab=readme-ov-file#getting-updates
[^2]: https://github.com/ohmyzsh/ohmyzsh/wiki/Settings#update-settings

**Comment by mcornella** [comment] 2024-08-15 15:59
I have set up poetry locally to test this, I will try to make a reproduction to see if there's something happening on their end or our end that can be fixed.

**Comment by mcornella** [comment] 2024-09-01 08:28
I was not able to reproduce this with poetry 1.8.3:

![image](https://github.com/user-attachments/assets/b820eb73-4d2a-40d3-a169-7a91ad75c52d)


You can see in the trace file of the same process when there is typed input the `has_typed_input` function does what it's supposed to do:

```sh
 364   │ +(anon):59> [[ prompt = reminder ]]
 365   │ +(anon):59> [[ prompt != background-alpha ]]
 366   │ +(anon):59> has_typed_input
 367   │ +has_typed_input:3> emulate -L zsh
 368   │ +has_typed_input:4> zmodload zsh/zselect
 369   │ +has_typed_input:9> local termios
 370   │ +has_typed_input:10> termios=+has_typed_input:10> stty --save
 371   │ +has_typed_input:10> termios=500:5:bf:8a33:3:1c:7f:15:4:0:1:0:11:13:1a:0:12:f:17:16:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0 
 372   │ +has_typed_input:14> stty -icanon
 373   │ +has_typed_input:17> zselect -t 0 -r 0
 374   │ +has_typed_input:18> return 0
 375   │ +has_typed_input:21> stty 500:5:bf:8a33:3:1c:7f:15:4:0:1:0:11:13:1a:0:12:f:17:16:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0
 376   │ +(anon):60> printf '\r\e[0K'
 377   │ +(anon):61> echo '[oh-my-zsh] It'\''s time to update! You can do that by running `omz update`'
 378   │ +(anon):62> return 0
 379   │ +handle_update:1> ret=0 
```

If you are able to reproduce this, please set up tracing as in the git patch below and capture a trace of the update prompt:

```patch
diff --git a/oh-my-zsh.sh b/oh-my-zsh.sh
index b1032841..e1ffc569 100644
--- a/oh-my-zsh.sh
+++ b/oh-my-zsh.sh
@@ -67,9 +67,23 @@ fi
 mkdir -p "$ZSH_CACHE_DIR/completions"
 (( ${fpath[(Ie)$ZSH_CACHE_DIR/completions]} )) || fpath=("$ZSH_CACHE_DIR/completions" $fpath)
 
+# Capture stdout and stderr to a log file:
+# - duplicate stderr (fd 2) and redirect to fd 4: 4>&2
+# - open file descriptor 3 and redirect to log file: 3>~/update.log
+# - redirect stderr (fd 2) to fd 3: 2>&3
+exec 4>&2 3>~/update.log 2>&3
+# Enable trace mode
+set -xv
+
 # Check for updates on initial load...
 source "$ZSH/tools/check_for_upgrade.sh"
 
+# Disable trace mode
+set +xv
+# Restore stdout and stderr
+exec 2>&4 3>&- 4>&-
+
+
 # Initializes Oh My Zsh
 
 # add a function path
```

There may be more complex setup needed so let me know if you have any doubts. Closing for now as not reproducible.

**Closed by mcornella** 2024-09-01 08:28 UTC
Labels: Bug, Area: updater
