### ISSUE TITLE
Add FAQ for brew installation

### ISSUE THREAD

**Issue by Siddhant** [ohmyzsh/ohmyzsh#12428] opened 2024-05-18 05:05 UTC
### If the feature solves a problem you have, specify it here.

As a first time Mac user, the first thing I learnt on the internet was to install `homebrew.` The second thing eveyone tells you is to install `ohmyzsh`. Hence, it came as a surprise that I can't install `ohmyzsh` using `brew`. I also went thought the [FAQ#how-do-i-install-zsh](https://github.com/ohmyzsh/ohmyzsh/wiki/FAQ#how-do-i-install-zsh) but did not see anything.

### Describe the proposed feature.

Kindly add an FAQ on why ohmyzsh can't be installed using `brew` on macOS. At least one other person faced a similar question in https://github.com/ohmyzsh/ohmyzsh/issues/12381. Hence my request for an FAQ. Maybe others have asked you similar question over the years.

_If this is too small a topic to warrant a new FAQ_, at least somewhere in the install instructions (maybe you can just mention it in passing) that the user won't be able to install using brew.

### Additional context

Maybe I'm showing extreme newbie behaviour in asking this - please ignore this issue if you feel otherwise.
Thank you.

### Related Issues

https://github.com/ohmyzsh/ohmyzsh/issues/12381

**Comment by ColtonIdle** [comment] 2024-05-19 19:20
Same issue. Was going to create an issue here.

Is it really true that I can't install ohmyzsh via brew? If so... weird! Guess there's some technical limitation as to why?

**Comment by carlosala** [comment] 2024-05-21 18:55
Hi! Thanks for the idea!
It's indeed a duplicate of #12381. I'd be happy to have ohmyzsh in brew. If anyone does create the brew formula we'll add it to our README!

**Closed by carlosala** 2024-05-21 18:55 UTC
Labels: Feature
