### ISSUE TITLE
Docker logs tab plugin fails with custom docker ps format

### ISSUE THREAD

**Issue by FreddieDev** [ohmyzsh/ohmyzsh#11841] opened 2023-08-11 13:15 UTC
### Describe the bug

Previously with OhMyZsh, I was able to use tab to auto-complete docker container names when typing `docker logs my-service-name-fo...` etc.

However, this functionality broke after applying a custom psFormat format in `~/.docker/config.json`.

My suggestion is, if hitting tab is internally processing the output of `docker ps` for the active container names, that the internal command instead also uses its own hard-coded format, such as: `docker ps --format='{{.Names}}'`

My `config.json` is configured as follows:
```json
{
  "psFormat": "table {{.ID}}\t{{.Names}}\t{{.Status}}\t{{.Image}}\t{{.Command}}"
}
```

You can view all configurable options using this command:
`docker ps --format='{{json .}}'`

### Steps to reproduce

1. Type docker logs <partial-container-name>
2. Hit tab to check auto-complete works
3. Implement a custom docker ps format in  `~/.docker/config.json`, where the name column is moved
4. Check docker ps has updated
5. Type docker logs <partial-container-name>
6. Hit tab and observe auto-complete fails

### Expected behavior

Auto-complete works no matter the user's custom PS format 

### OS / Linux distribution

CentOS 9

### Zsh version

5.8

### Terminal emulator

GNOME Terminal

**Comment by alanJames00** [comment] 2023-10-01 20:15
@mcornella , Can you please assign this issue to me under Hacktoberfest. 
I personally use OhMyZsh a lot. I've tinkered with the project enough for customization. I believe i can find the issue and i'm willing to raise a PR.
Thanks in advance

**Comment by robbyrussell** [comment] 2023-10-13 22:42
@alanJames00 added to Hacktoberfest

**Comment by mihir1739** [comment] 2023-10-21 13:16
Can I work on this if this issue is still open? Please assign this to me!

**Comment by BlueBeret** [comment] 2023-10-23 09:08
Is this issue still exist? I cannot reproduce it
![image](https://github.com/ohmyzsh/ohmyzsh/assets/63086194/6116b96f-21ec-4488-bda1-0f91d5f28a55)

**Comment by mcornella** [comment] 2023-10-23 09:11
Can confirm, this is not an issue with the latest Docker version:
```console
$ docker --version
Docker version 24.0.6, build ed223bc
```
Thanks for the update!

**Closed by mcornella** 2023-10-23 09:11 UTC
Labels: Bug, Hacktoberfest, Good first issue
