### ISSUE TITLE
Adding pipe to a command when editing it sometimes causes the rest of line to get deleted

### ISSUE THREAD

**Issue by d33tah** [ohmyzsh/ohmyzsh#9260] opened 2020-09-15 16:06 UTC
**Describe the bug**
A clear description of what the bug is.

**To Reproduce**

I actually don't know how to reproduce this - it happens randomly. In the attched video (see two sections below), I'm just trying to add a pipe to a command line and for some reason the rest gets deleted. I failed to reproduce this on another box.

**Expected behavior**

The removal should not happen.

**Screenshots and/or Recordings**

https://asciinema.org/a/oT1Lq8v9Rn0Hey9wyT1u0cPkt

**Self Check**

- Have you tried reaching out on the [Discord server](https://discord.gg/ohmyzsh)? 
  This can help cut down on filling up issues. We always have a few people
  online that are in a variety of timezones that are willing to help you!

Nope, but I tried posting on IRC.

- Also searching existing [GitHub Issues](https://github.com/ohmyzsh/ohmyzsh/issues?q=) might help you get quicker support

**Desktop (please complete the following information):**

 - OS / Distro: Ubuntu 20.04
 - Latest ohmyzsh update?: Yes
 - ZSH Version: 5.4.2
 - Terminal emulator: Konsole

**Additional context**

Here's my zshrc: https://github.com/d33tah/dotfiles/blob/master/dotfiles/zshrc

And a minified version:

```
export ZSH="/home/d33tah/.oh-my-zsh"
ZSH_THEME="robbyrussell"
plugins=(git)
source $ZSH/oh-my-zsh.sh
PROMPT='[%{$fg_bold[blue]%}%*%{$reset_color%}] ${ret_status}%{$fg_bold[green]%}%p %{$fg[cyan]%}%c %{$fg_bold[blue]%}$(git_prompt_info)%{$fg_bold[blue]%} % %{$reset_color%}'
. ~/.shrc
if [ "$SSH_CONNECTION" != "" ]; then
  if echo $TERM | grep -v 'screen' && ! tmux attach; then
      tmux
  fi
fi
bindkey \^U backward-kill-line
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
```

**Comment by mcornella** [comment] 2020-09-15 16:22
This is a duplicate of https://github.com/ohmyzsh/ohmyzsh/issues/8572 but we never actually found a culprit I think. Try to delete zshrc file sections until you can no longer reproduce this. I'd suggest removing tmux and fzf, or even OMZ.

**Comment by d33tah** [comment] 2020-09-15 17:50
@mcornella thanks for replying! Is it at least known whether it's an OMZ or zsh bug?

**Comment by mcornella** [comment] 2020-09-15 19:02
We really don't know, try to disable it and see if the same thing still happens. You could run `zsh -f` to start zsh without reading the zshrc file and see if you can still reproduce it. If not, try commenting out lines from the zshrc file one by one until you find the most minimal zshrc file with which this happens.

**Comment by mcornella** [comment] 2020-09-30 16:54
Did you manage to find the source of the bug?

**Comment by d33tah** [comment] 2020-09-30 20:22
Nope

śr., 30 wrz 2020 o 18:54 Marc Cornellà <notifications@github.com>
napisał(a):

**Comment by mcornella** [comment] 2020-09-30 20:30
Well I can't do it for you since I can't reproduce it. Try asking in the zsh mailing list: https://www.zsh.org/mla/.

**Comment by mcornella** [comment] 2020-09-30 21:39
Also if the same happens after commenting out the `source $ZSH/oh-my-zsh.sh` line?

**Closed** 2020-10-10 18:52 UTC
