### ISSUE TITLE
Pipenv issue after merging #12813 - auto-shell not working properly

### ISSUE THREAD

**Issue by MHM5000** [ohmyzsh/ohmyzsh#12834] opened 2024-12-01 13:11 UTC
### Describe the bug

Creating a new tab doesn't activate the Pipenv environment properly.
first mentioned it here: https://github.com/ohmyzsh/ohmyzsh/pull/12813#issuecomment-2497983972

### Steps to reproduce

after upgrading, if I create a new tab, in macos , iterm2, it doesn't source properly.
I have to do a `cd ..`, then create a new tab, then move back to the project

### Expected behavior

the shell and env should be accessible. (not sure about the terms)

### Screenshots and recordings

https://app.usebubbles.com/rPnndb9JZE9UxeS5PY1xXS/omz-issue

### OS / Linux distribution

MacOS Darwin 24.1.0 arm64

### Zsh version

5.9

### Oh My Zsh version

master (366d254)

### Terminal emulator

iTerm2

### If using WSL on Windows, which version of WSL

None

### Additional context

shared the logs in an email.
thanks in advance for checking
great product.

**Comment by mcornella** [comment] 2024-12-03 15:35
Thanks for the report, Mohammad.

We ended up using these steps to gather the zsh logs:

> 1. Enter pipenv directory in a tab, see that everything works well
> 2. While the tab is open, edit .zshrc file, and add these lines (at the top of the file and at the bottom of the file):
> ```sh
> # at the top
> debugfile=~/omz-debug.$$.log; exec 3>&2 2>$debugfile; set -xv
> 
> # at the bottom
> set +xv; exec 2>&3 3>&-; echo "Log in $debugfile..."
> ```
> 3. Open a new tab. This will trigger the issue (confirm please) and log results. The resulting log file will be displayed.
> 4. Now you can close the tab and remove the lines in step 2.

With these logs, I was able to confirm that indeed, the pipenv plugin is activating the environment:

```sh
+/Users/<user>/.oh-my-zsh/plugins/pipenv/pipenv.plugin.zsh:39> _togglePipenvShell
+_togglePipenvShell:2> [[ ! -f /Users/<user>/<project>/Pipfile ]]
+_togglePipenvShell:12> [[ '' != 1 ]]
+_togglePipenvShell:13> [[ -f /Users/<user>/<project>/Pipfile ]]
+_togglePipenvShell:14> export pipfile_dir=/Users/<user>/<project>
+_togglePipenvShell:15> pipenv --venv
Loading .env environment variables...
+_togglePipenvShell:15> source /Users/<user>/.local/share/virtualenvs/<project>-dB3i4FDK/bin/activate
+/Users/<user>/.local/share/virtualenvs/<project>-dB3i4FDK/bin/activate:5> [ '' '=' /Users/<user>/.local/share/virtualenvs/<project>-dB3i4FDK/bin/activate ']'
+/Users/<user>/.local/share/virtualenvs/<project>-dB3i4FDK/bin/activate:46> deactivate nondestructive
+deactivate:1> unset -f pydoc
+deactivate:1> true
+deactivate:5> [ -z '' ']'
+deactivate:10> [ -z '' ']'
+deactivate:19> hash -r
+deactivate:21> [ -z '' ']'
+deactivate:27> unset VIRTUAL_ENV
+deactivate:28> unset VIRTUAL_ENV_PROMPT
+deactivate:29> [ '!' nondestructive '=' nondestructive ']'
VIRTUAL_ENV='/Users/<user>/.local/share/virtualenvs/<project>-dB3i4FDK'
+/Users/<user>/.local/share/virtualenvs/<project>-dB3i4FDK/bin/activate:48> VIRTUAL_ENV=/Users/<user>/.local/share/virtualenvs/<project>-dB3i4FDK 
+/Users/<user>/.local/share/virtualenvs/<project>-dB3i4FDK/bin/activate:49> [ darwin24.0 '=' cygwin ']'
+/Users/<user>/.local/share/virtualenvs/<project>-dB3i4FDK/bin/activate:49> [ darwin24.0 '=' msys ']'
+/Users/<user>/.local/share/virtualenvs/<project>-dB3i4FDK/bin/activate:52> export VIRTUAL_ENV
+/Users/<user>/.local/share/virtualenvs/<project>-dB3i4FDK/bin/activate:54> _OLD_VIRTUAL_PATH='...' 
+/Users/<user>/.local/share/virtualenvs/<project>-dB3i4FDK/bin/activate:55> PATH='/Users/<user>/.local/share/virtualenvs/<project>-dB3i4FDK/bin:...' 
+/Users/<user>/.local/share/virtualenvs/<project>-dB3i4FDK/bin/activate:56> export PATH
+/Users/<user>/.local/share/virtualenvs/<project>-dB3i4FDK/bin/activate:58> [ x<project> '!=' x ']'
+/Users/<user>/.local/share/virtualenvs/<project>-dB3i4FDK/bin/activate:59> VIRTUAL_ENV_PROMPT=<project> 
+/Users/<user>/.local/share/virtualenvs/<project>-dB3i4FDK/bin/activate:63> export VIRTUAL_ENV_PROMPT
+/Users/<user>/.local/share/virtualenvs/<project>-dB3i4FDK/bin/activate:66> [ -z '' ']'
+/Users/<user>/.local/share/virtualenvs/<project>-dB3i4FDK/bin/activate:71> [ -z '' ']'
+/Users/<user>/.local/share/virtualenvs/<project>-dB3i4FDK/bin/activate:72> _OLD_VIRTUAL_PS1='%n@%m %1~ %# ' 
+/Users/<user>/.local/share/virtualenvs/<project>-dB3i4FDK/bin/activate:73> PS1='(<project>) %n@%m %1~ %# ' 
+/Users/<user>/.local/share/virtualenvs/<project>-dB3i4FDK/bin/activate:74> export PS1
+/Users/<user>/.local/share/virtualenvs/<project>-dB3i4FDK/bin/activate:78> alias pydoc
+/Users/<user>/.local/share/virtualenvs/<project>-dB3i4FDK/bin/activate:78> true
+/Users/<user>/.local/share/virtualenvs/<project>-dB3i4FDK/bin/activate:87> hash -r
+_togglePipenvShell:16> export PIPENV_ACTIVE=1
```

What's happening is that the `PS1` is defined, but then the theme is loaded, which resets this value. You should still see that `$VIRTUAL_ENV` has the expected value, and then you can check that the virtual environment libraries are loaded correctly.

To work around this issue, you can use a theme that has virtualenv support, or add the `virtualenv_prompt_info` somewhere in your prompt. For example, I have this in my .zshrc file, after OMZ is loaded, to put it on the right side:

```sh
RPROMPT='$(virtualenv_prompt_info)'" $RPROMPT"
```

Please confirm that the libraries are loaded correctly. If not, there may be a second issue, maybe caused by pyenv not loaded?:

```sh
+_omz_source:23> source /Users/<user>/.oh-my-zsh/plugins/pyenv/pyenv.plugin.zsh
# if there is a virtualenv already loaded pyenv should not be loaded
# see https://github.com/ohmyzsh/ohmyzsh/issues/12589
[[ -n ${VIRTUAL_ENV:-} ]] && return
+/Users/<user>/.oh-my-zsh/plugins/pyenv/pyenv.plugin.zsh:3> [[ -n /Users/<user>/.local/share/virtualenvs/<project>-dB3i4FDK ]]
+/Users/<user>/.oh-my-zsh/plugins/pyenv/pyenv.plugin.zsh:3> return
```

**Comment by MHM5000** [comment] 2024-12-15 08:33
I Itried several things. nothing worked.
I disabled `pipenv` plugin and stopped being lazy 😂 . I'll manually do a `pipenv shell` for each new tab.

**Comment by mcornella** [comment] 2024-12-16 09:59
OK, closing as not reproducible. Thanks for the report.

**Closed by mcornella** 2024-12-16 09:59 UTC
Labels: Area: plugin, Resolution: not our issue
