### ISSUE TITLE
Update 'master' to 'main'

### ISSUE THREAD

**Issue by sabahzero** [ohmyzsh/ohmyzsh#10299] opened 2021-10-14 22:51 UTC
### Describe the proposed feature.

![Screen Shot 2021-10-14 at 3 50 43 PM](https://user-images.githubusercontent.com/16907482/137406051-5234aaf8-5ec3-4b3b-8f4c-d4c9f3cf712f.png)

Reasoning and execution:
https://stevenmortimer.com/5-steps-to-change-github-default-branch-from-master-to-main/

**Comment by mcornella** [comment] 2021-10-15 16:52
Duplicate of #9015

**Closed by mcornella** 2021-10-15 16:52 UTC
Labels: Feature
