### ISSUE TITLE
move ~/.oh-my-zsh to ~/.config/oh-my-zsh

### ISSUE THREAD

**Issue by mikelpr** [ohmyzsh/ohmyzsh#12485] opened 2024-06-08 23:08 UTC
### If the feature solves a problem you have, specify it here.

dotfiles/folders polluting $HOME are extremely annoying

### Describe the proposed feature.

using $HOME/.config/oh-my-zsh instead of $HOME/.oh-my-zsh would be a very welcome move

### Describe alternatives you've considered

I manually changed the ZSH export from "$HOME/.oh-my-zsh" to "$HOME/.config/oh-my-zsh" in my .zshrc. nothing has broken thankfully

### Additional context

I suppose this might only apply to linuxes. It'd be nice if during installation we checked if .config exists and make the oh-my-zsh dir there, and fallback to .oh-my-zsh otherwise.

**Comment by vringar** [comment] 2024-06-15 10:03
Alternatively, you could attempt to follow [the full spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) instead of just special casing `$HOME/.config`

**Comment by Magniquick** [comment] 2024-06-15 18:12
Dupe of #9543.

**Closed** 2024-07-23 18:11 UTC
Labels: Feature, Resolution: duplicate
