### ISSUE TITLE
Zsh shell taking abnormally long time during initial startup

### ISSUE THREAD

**Issue by xd003** [ohmyzsh/ohmyzsh#9055] opened 2020-06-22 06:11 UTC
As i have already stated in question , zsh shell is taking abnormally long time to start up. I would like to clear it again that delay in zsh only happens when opening terminal at start , not during general usage. I have disabled all plugins and using powerlevel10k theme , although i can definitely say it has nothing to do with theme. I noticed this slowdown immediately after i had changed to zsh shell from bash which got worsened even further after installing oh my zsh .To put things in perspective , raw zsh is almost 6 times slower as compared to raw bash in starting up and zsh + ohmyzsh is almost 14 times slower as comapared to raw bash .Posted timings below for each case. 
[Heres's](https://del.dog/cebidexymy.txt) my .zshrc file if that helps

I also checked what functions are being run during initial startup using zsh profiling
Here's the whole list - https://del.dog/cytahuving.txt
handle_completion_insecurities , anon and compinit are the ones taking the top 3 most time , I don't know anything about it , just a normal user 
Hopefully this much info would be enough to debug the cause of problem

Using Raw Bash
```
for i in $(seq 1 10); do /usr/bin/time bash -i -c exit; done
exit
0.02user 0.07system 0:00.19elapsed 45%CPU (0avgtext+0avgdata 1816maxresident)k
136inputs+0outputs (3major+1737minor)pagefaults 0swaps
exit
0.05user 0.04system 0:00.17elapsed 52%CPU (0avgtext+0avgdata 1820maxresident)k
0inputs+0outputs (0major+1737minor)pagefaults 0swaps
exit
0.02user 0.06system 0:00.18elapsed 42%CPU (0avgtext+0avgdata 1824maxresident)k
0inputs+0outputs (0major+1745minor)pagefaults 0swaps
exit
0.08user 0.03system 0:00.21elapsed 51%CPU (0avgtext+0avgdata 1828maxresident)k
0inputs+0outputs (0major+1743minor)pagefaults 0swaps
exit
0.00user 0.06system 0:00.14elapsed 40%CPU (0avgtext+0avgdata 1816maxresident)k
0inputs+0outputs (0major+1736minor)pagefaults 0swaps
exit
0.02user 0.05system 0:00.14elapsed 50%CPU (0avgtext+0avgdata 1820maxresident)k
0inputs+0outputs (0major+1738minor)pagefaults 0swaps
exit
0.00user 0.06system 0:00.13elapsed 46%CPU (0avgtext+0avgdata 1820maxresident)k
0inputs+0outputs (0major+1741minor)pagefaults 0swaps
exit
0.01user 0.05system 0:00.14elapsed 40%CPU (0avgtext+0avgdata 1816maxresident)k
0inputs+0outputs (0major+1738minor)pagefaults 0swaps
exit
0.00user 0.07system 0:00.14elapsed 48%CPU (0avgtext+0avgdata 1816maxresident)k
0inputs+0outputs (0major+1738minor)pagefaults 0swaps
exit
0.01user 0.06system 0:00.13elapsed 50%CPU (0avgtext+0avgdata 1816maxresident)k
0inputs+0outputs (0major+1737minor)pagefaults 0swaps
```
 Using raw zsh ( without oh my zsh )
```
0.27user 0.35system 0:01.05elapsed 58%CPU (0avgtext+0avgdata 3256maxresident)k
0inputs+0outputs (0major+1823minor)pagefaults 0swaps
0.25user 0.41system 0:01.17elapsed 56%CPU (0avgtext+0avgdata 3252maxresident)k
0inputs+0outputs (0major+1824minor)pagefaults 0swaps
0.41user 0.27system 0:01.06elapsed 63%CPU (0avgtext+0avgdata 3256maxresident)k
0inputs+0outputs (0major+1824minor)pagefaults 0swaps
0.52user 0.20system 0:01.20elapsed 59%CPU (0avgtext+0avgdata 3252maxresident)k
0inputs+0outputs (0major+1823minor)pagefaults 0swaps
0.32user 0.36system 0:01.19elapsed 57%CPU (0avgtext+0avgdata 3256maxresident)k
0inputs+0outputs (0major+1824minor)pagefaults 0swaps
0.21user 0.48system 0:01.22elapsed 56%CPU (0avgtext+0avgdata 3256maxresident)k
0inputs+0outputs (0major+1825minor)pagefaults 0swaps
0.27user 0.36system 0:01.12elapsed 56%CPU (0avgtext+0avgdata 3256maxresident)k
0inputs+0outputs (0major+1823minor)pagefaults 0swaps
0.24user 0.45system 0:01.18elapsed 58%CPU (0avgtext+0avgdata 3252maxresident)k
0inputs+0outputs (0major+1823minor)pagefaults 0swaps
0.24user 0.47system 0:01.22elapsed 58%CPU (0avgtext+0avgdata 3256maxresident)k
0inputs+0outputs (0major+1825minor)pagefaults 0swaps
0.38user 0.32system 0:01.16elapsed 60%CPU (0avgtext+0avgdata 3256maxresident)k
0inputs+0outputs (0major+1825minor)pagefaults 0swaps
```

Using Zsh + Ohmyzsh
```
for i in $(seq 1 10); do /usr/bin/time zsh -i -c exit; done
0.67user 0.82system 0:02.54elapsed 58%CPU (0avgtext+0avgdata 4676maxresident)k
0inputs+0outputs (0major+8337minor)pagefaults 0swaps
0.66user 1.01system 0:02.88elapsed 57%CPU (0avgtext+0avgdata 4676maxresident)k
0inputs+0outputs (0major+8329minor)pagefaults 0swaps
0.51user 1.11system 0:03.17elapsed 50%CPU (0avgtext+0avgdata 4676maxresident)k
0inputs+0outputs (0major+8345minor)pagefaults 0swaps
0.74user 0.76system 0:02.78elapsed 53%CPU (0avgtext+0avgdata 4676maxresident)k
0inputs+0outputs (0major+8339minor)pagefaults 0swaps
0.59user 0.99system 0:02.74elapsed 57%CPU (0avgtext+0avgdata 4676maxresident)k
0inputs+0outputs (0major+8326minor)pagefaults 0swaps
0.80user 0.86system 0:02.88elapsed 57%CPU (0avgtext+0avgdata 4676maxresident)k
0inputs+0outputs (0major+8339minor)pagefaults 0swaps
0.63user 1.02system 0:02.78elapsed 59%CPU (0avgtext+0avgdata 4676maxresident)k
0inputs+0outputs (0major+8330minor)pagefaults 0swaps
0.87user 0.89system 0:03.08elapsed 57%CPU (0avgtext+0avgdata 4676maxresident)k
0inputs+0outputs (0major+8325minor)pagefaults 0swaps
0.68user 0.98system 0:02.89elapsed 57%CPU (0avgtext+0avgdata 4676maxresident)k
0inputs+0outputs (0major+8323minor)pagefaults 0swaps
0.71user 0.88system 0:02.81elapsed 56%CPU (0avgtext+0avgdata 4676maxresident)k
0inputs+0outputs (0major+8338minor)pagefaults 0swaps
```

**Desktop (please complete the following information):**
 - OS / Distro: Ubuntu 20
 - Latest ohmyzsh Update?: Yes
 - ZSH Version: 5.8

**Comment by xd003** [comment] 2020-06-22 11:08
Update - I also checked what functions are being run during initial startup 
Here's the whole list - https://del.dog/cytahuving.txt

Hopefully it will now be easy to debug the cause of this issue

**Comment by romkatv** [comment] 2020-12-15 21:07
@xd003 Powerlevel10k can remove zsh startup lag even when it's not caused by Powerlevel10k itself. This feature is called *Instant Prompt* and it needs to be explicitly enabled. Run `p10k configure` and when it asks you whether you want to enable instant prompt, choose "quiet" or "verbose" (choose the latter if you don't know the difference). See for details: https://github.com/romkatv/powerlevel10k#instant-prompt

**Comment by Arnie97** [comment] 2021-01-19 14:10
Remove everything in `handle_completion_insecurities()` in`$ZSH/lib/compfix.zsh` does improve the zsh startup time. It took half of my zsh startup time according to `zprof`.

**Comment by sandervalstar** [comment] 2021-05-11 00:45
Thanks, the zprof tip was useful! For me nvm was the culprit. Solved it by replacing the following in my `~/.zshrc`:
`[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"`
with:
`alias nvm="unalias nvm; [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"; nvm $@"`

**Comment by archf** [comment] 2021-10-19 17:55
Noticed something similar as @Arnie97 mentionned. If I `zprof`, `handle_completion_insecurities()` as shown below takes 27% of startup time but I have seen it a couple times in the 40-42% range.

```
num  calls                time                       self            name
-----------------------------------------------------------------------------------
 1)    1          21.94    21.94   31.52%     21.94    21.94   31.52%  (anon)
 2)    1          20.69    20.69   29.72%     20.69    20.69   29.72%  compinit
 3)    1          18.86    18.86   27.09%     18.86    18.86   27.09%  handle_completion_insecurities
 4)    1           3.46     3.46    4.97%      3.46     3.46    4.97%  colors
 5)   12           2.00     0.17    2.87%      2.00     0.17    2.87%  compdef
 6)    1           1.03     1.03    1.48%      1.03     1.03    1.48%  is-at-least
 7)    3           0.96     0.32    1.39%      0.96     0.32    1.39%  add-zsh-hook
 8)   12           0.53     0.04    0.77%      0.53     0.04    0.77%  is_plugin
 9)    2           0.07     0.03    0.09%      0.07     0.03    0.09%  env_default
10)    1           0.05     0.05    0.07%      0.05     0.05    0.07%  detect-clipboard
11)    1           0.03     0.03    0.04%      0.03     0.03    0.04%  bashcompinit

-----------------------------------------------------------------------------------

 1)    1          21.94    21.94   31.52%     21.94    21.94   31.52%  (anon)

-----------------------------------------------------------------------------------

 2)    1          20.69    20.69   29.72%     20.69    20.69   29.72%  compinit

-----------------------------------------------------------------------------------

 3)    1          18.86    18.86   27.09%     18.86    18.86   27.09%  handle_completion_insecurities

-----------------------------------------------------------------------------------

 4)    1           3.46     3.46    4.97%      3.46     3.46    4.97%  colors

-----------------------------------------------------------------------------------

 5)   12           2.00     0.17    2.87%      2.00     0.17    2.87%  compdef

-----------------------------------------------------------------------------------

 6)    1           1.03     1.03    1.48%      1.03     1.03    1.48%  is-at-least

-----------------------------------------------------------------------------------

 7)    3           0.96     0.32    1.39%      0.96     0.32    1.39%  add-zsh-hook

-----------------------------------------------------------------------------------

 8)   12           0.53     0.04    0.77%      0.53     0.04    0.77%  is_plugin

-----------------------------------------------------------------------------------

 9)    2           0.07     0.03    0.09%      0.07     0.03    0.09%  env_default

-----------------------------------------------------------------------------------

10)    1           0.05     0.05    0.07%      0.05     0.05    0.07%  detect-clipboard

-----------------------------------------------------------------------------------

11)    1           0.03     0.03    0.04%      0.03     0.03    0.04%  bashcompinit
```
An opt-out does exist as per script code/output fwiw

> [oh-my-zsh] If the above didn't help or you want to skip the verification of
[oh-my-zsh] insecure directories you can set the variable ZSH_DISABLE_COMPFIX to
[oh-my-zsh] "true" before oh-my-zsh is sourced in your zshrc file.

**Comment by BuonOmo** [comment] 2022-02-24 09:03
To add more data, (Mac M1 Max, latest oh-my-zsh):

```
num  calls                time                       self            name
-----------------------------------------------------------------------------------
 1)    1          16.02    16.02   48.44%     16.02    16.02   48.44%  handle_completion_insecurities
 2)    1           9.74     9.74   29.46%      9.74     9.74   29.46%  compinit
 3)    2           4.93     2.47   14.92%      4.93     2.47   14.92%  (anon)
 4)    1           0.74     0.74    2.25%      0.74     0.74    2.25%  regexp-replace
...
```

And @sandervalstar for your issue, I've had the same before, and there may be other culprits (rbenv, emscripten, autojump):

https://github.com/BuonOmo/dotfiles/blob/9ce8a95372ef0e5a3e6034ef9a336fc3c652e90f/.zshrc#L123-L149

**Comment by carlosala** [comment] 2022-02-24 12:31
There is a PR (#10672) that's going to solve that by executing `handle_completion_insecurities` as an async command (what basically means that's not blocking the execution of other config). By the way, you can also disable it setting `ZSH_DISABLE_COMPFIX=true` in your `zshrc` before sourcing `oh-my-zsh.sh` script.

**Comment by manuel-arguelles** [comment] 2022-05-09 22:22
I'm experiencing a similar issue but using `zprof` the problem seems to be in the `is_update_available` function:
```
num  calls                time                       self            name
-----------------------------------------------------------------------------------
 1)    1         309.90   309.90   89.63%    309.90   309.90   89.63%  is_update_available
 2)    1          22.34    22.34    6.46%     12.30    12.30    3.56%  compinit
 3)    2          10.04     5.02    2.90%     10.04     5.02    2.90%  compaudit
```

if I disable the automatic updates `zstyle ':omz:update' mode disabled` it starts up super fast
```
num  calls                time                       self            name
-----------------------------------------------------------------------------------
 1)    1          22.66    22.66   72.15%     12.02    12.02   38.27%  compinit
 2)    2          10.64     5.32   33.88%     10.64     5.32   33.88%  compaudit
 3)    6           3.95     0.66   12.57%      3.95     0.66   12.57%  url-quote-magic
```

I have the default update frequency configured, could there be a problem with the check frequency lock? I don't have anything in `~/.oh-my-zsh/log/` nor `~/.oh-my-zsh/cache` related to update...

**Comment by manuel-arguelles** [comment] 2022-05-09 22:31
Update, in my case running `omz update` manually seems to solved the problem, now I have a `~/.oh-my-zsh/cache/.zsh-update`

**Comment by carlosala** [comment] 2022-12-15 11:52
Closing this, it looks like performance really improved after #10672 🎉

**Closed by carlosala** 2022-12-15 11:52 UTC
Labels: Support
