### ISSUE TITLE
high cpu usage when enable ZSH_THEME="robbyrussell"

### ISSUE THREAD

**Issue by jsrdzhk** [ohmyzsh/ohmyzsh#12456] opened 2024-05-28 01:24 UTC
### Describe the bug

os:CentOS Linux release 7.9.2009 (Core)
high cpu usage when enable ZSH_THEME="robbyrussell"

### Steps to reproduce

1. uncomment line `ZSH_THEME="robbyrussell"` in ~/.zshrc
2. source ~/.zshrc
3. use top to see zsh process cpu usage

### Expected behavior

no high cpu usage

### OS / Linux distribution

CentOS Linux release 7.9.2009 (Core)

### Zsh version

5.0.2

### Terminal emulator

mobaxterm

### If using WSL on Windows, which version of WSL

None

**Comment by carlosala** [comment] 2024-05-28 08:50
Duplicate of #12360. Let's move the discussion over there 👍🏻

**Closed by carlosala** 2024-05-28 08:50 UTC
