### ISSUE TITLE
No working at all

### ISSUE THREAD

**Issue by lucascamara-drk** [ohmyzsh/ohmyzsh#9297] opened 2020-09-29 23:58 UTC
For any reason, it doesn't work at all. I've installed it some hours ago and it does work, although I use zsh for weeks. I failed both on the normal user and root user. I also tried to reinstall zsh and download it through both github and using the command specified on the oh-my-zsh website.

That is what it returns:
```
/root/.oh-my-zsh/tools/check_for_upgrade.sh: line 31: syntax error near unexpected token `)'
/root/.oh-my-zsh/tools/check_for_upgrade.sh: line 31: `() {'
./oh-my-zsh.sh: line 21: autoload: command not found
./oh-my-zsh.sh: line 39: syntax error near unexpected token `('
./oh-my-zsh.sh: line 39: `for plugin ($plugins); do'
```
At last, I tried to open the codes and see what's wrong but, again, I failed. There are some other mistakes in the upgrade script (according to my system, Arch, I can't read it properly)

**Comment by mcornella** [comment] 2020-09-30 06:52
It looks like you're using bash. Make sure you're running `zsh` and set it as the default shell with `chsh -s $(which zsh)` (you have to restart your login session for the change to take effect).

**Comment by mcornella** [comment] 2020-09-30 14:14
Duplicate of https://github.com/ohmyzsh/ohmyzsh/issues/8038.

**Closed by mcornella** 2020-09-30 14:14 UTC
Labels: Status: duplicate, support

**Comment by ImAvinashSharma** [comment] 2021-05-08 18:01
Same issue, 

.oh-my-zsh/tools/check_for_upgrade.sh: line 32: syntax error near unexpected token `)'`
.oh-my-zsh/tools/check_for_upgrade.sh: line 32: `() {'
.oh-my-zsh/oh-my-zsh.sh: line 21: autoload: command not found
.oh-my-zsh/oh-my-zsh.sh: line 39: syntax error near unexpected token `('
.oh-my-zsh/oh-my-zsh.sh: line 39: `for plugin ($plugins); do'
.fzf/shell/key-bindings.zsh: line 22: syntax error near unexpected token `)'
.fzf/shell/key-bindings.zsh: line 22:  () {

**Comment by rwmitchell** [comment] 2021-05-08 18:49
how did you initiate the upgrade?
has this been working and stopped?

**Comment by ImAvinashSharma** [comment] 2021-05-09 07:15
I just ran the /.zshrc file and got this issue.

**Comment by rwmitchell** [comment] 2021-05-09 14:13
what was your current shell?
did you mistype or are really running out of the root directory?

If you want to reload your .zshrc file, the best way is to run: ```exec zsh```

**Comment by ImAvinashSharma** [comment] 2021-05-13 09:56
I did it from my root level, I just ran this command `./zshrc` 
Thank man, it worked `exec zsh`😃

**Comment by indcoder** [comment] 2021-06-23 18:20
I am getting error just after the latest ohmyzsh update was run..

My current shell is zsh.
echo $ZSH_VERSION
5.8

I have run exec zsh but the error is consistent whenever I run git commit:

/home/usr/.oh-my-zsh/tools/check_for_upgrade.sh: line 32: syntax error near unexpected token `)'
