### ISSUE TITLE
oh my zsh breaks open file manager option on Konsole context menu

### ISSUE THREAD

**Issue by hrzhu** [ohmyzsh/ohmyzsh#11683] opened 2023-05-09 09:49 UTC
### Describe the bug

oh my zsh breaks open file manager option on Konsole context menu. I did a git bisect. commit 25c2c3a4 by @ntninja introduced this issue. Last working commit is the previous one.
I don't know what does that commit exactly do but comment out `add-zsh-hook precmd omz_termsupport_cwd` fixes the konsole problem.

### Steps to reproduce

1 Open Konsole. Right click on it, choose Open File Manager.
2 File Manager doesn't open. For older version of konsole, like 21.12.3, an error message will pop up saying file or folder `file://{host_name}/{PATH}` doesn't exist. For newer vresion of Knosole, like 22.04.3, nothing just happens.

### Expected behavior

File Manager opens in Konsole's working directory.

### OS / Linux distribution

Ubuntu 22.04

### Zsh version

5.8.1-1

### Oh My Zsh version

25c2c3a4

### Terminal emulator

Konsole

### If using WSL on Windows, which version of WSL

None

**Comment by ntninja** [comment] 2023-05-09 19:49
Yes, I can reproduce this as well (never used that context menu option before, I think). I think it is a bug in Konsole to not handle the situation better though, as it appears that it just uses the directory URL reported using the OSC 7 message as-is here. While ZSH can guess whether it is executing on local system or not based on environment variables, Konsole is in a much better position to judge this based on the provided hostname.

As for what Konsole should probably do here: If the hostname of the reported URL matches the local’s system hostname it should instead open `file:///{PATH}` (dropping the hostname part), if the hostname is something else it should probably just hide the menu option since there is no reliable way for it to know how the connection to the shell reporting the OSC 7 message came to be – alternatively I guess to assume that is always happened using a direct SSH connection and open `sftp://{host_name}/{PATH}` instead.

This could be worked around in OMZ though (at least for the SSH vs local case by examining the environment variables). Should it be addressed this way by special-casing it and sending a differently structured directory URL just for Konsole? Or should this just be deferred to Konsole upstream? Finally Konsole could also be dropped from the whitelist again, but then “open new tab in same directory“ would also break.

**Comment by ntninja** [comment] 2023-05-10 22:26
@carlosala: Ok, too bad that we need a workaround here, but I suppose it’s going to be a while until it’s fixed in Konsole either way… Does OMZ have any predefined way to find out whether ZSH is running on a local or a remote system that I can/should use for this?

@hrzhu: May I ask you to report this issue to Konsole? It’d be nice to remove that Konsole-specific workaround at some point again…

**Comment by hrzhu** [comment] 2023-05-11 03:22
@ntninja Hmm, I'd like to but I'm not familiar with shell internals, like I don't know what OSC 7 is. So I don't know how to describe the issue to Konsole.

**Comment by carlosala** [comment] 2023-05-11 13:20
I'm not expert at all about all of this. Could you check it @mcornella?

**Comment by mcornella** [comment] 2023-10-19 21:27
Should have been fixed in 50c6786 but the test variable was not set in Konsole. Now it should finally be fixed, try it out with `omz update`.

**Closed** 2023-10-19 21:26 UTC
Labels: Bug
