### ISSUE TITLE
Docker plugin not workin

### ISSUE THREAD

**Issue by sitilge** [ohmyzsh/ohmyzsh#8547] opened 2020-01-17 10:44 UTC
**Describe the bug**
Docker autocomplete plugin not working.

**To Reproduce**
1. Enable plugin 'docker'.
2. Start typing on your terminal emulator, hit the autocomplete button (Tab).
3. Nothing happens.

**Expected behavior**
Autocomplete suggests the relevant options.

**System:**
 - OS: arch 5.4.10
 - Zsh version: 5.7.1
 - Terminal emulator: Termite

**Comment by mcornella** [comment] 2020-01-19 17:00
This is a duplicate of https://github.com/ohmyzsh/ohmyzsh/issues/7642. Run `rm $ZSH_COMPDUMP` and restart the zsh session with `exec zsh`.

**Closed by mcornella** 2020-01-19 17:00 UTC
