### ISSUE TITLE
no such file or directory: /ohmyzsh/oh-my-zsh.sh

### ISSUE THREAD

**Issue by banditFox** [ohmyzsh/ohmyzsh#11471] opened 2023-02-01 14:30 UTC
I have been hunting for a solution to this.
/Users/"ME"/ .zshrc:source:75: no such file or directory: /ohmyzsh/oh-my-zsh.sh
occurs when running iTerm2 on Mac.

HOWEVER, 
it runs fine when I open Visual Studio Code on my mac:

<img width="484" alt="Screenshot 2023-02-01 at 08 28 09" src="https://user-images.githubusercontent.com/89707695/216070490-5b7486d4-3079-4d2d-8fd6-3186455cd7cf.png">

**Comment by carlosala** [comment] 2023-02-01 15:01
Where do you have OMZ installed?

**Comment by banditFox** [comment] 2023-02-01 15:18
Users/Robertmullins/ohmyzsh/oh-my-zsh.sh
<img width="981" alt="Screenshot 2023-02-01 at 09 18 29" src="https://user-images.githubusercontent.com/89707695/216083416-20099219-53c8-4f76-a41b-f9d6e549acec.png">

**Comment by banditFox** [comment] 2023-02-01 15:27
<img width="1302" alt="Screenshot 2023-02-01 at 09 26 58" src="https://user-images.githubusercontent.com/89707695/216085938-c4ed6a0f-5b2b-4b26-8836-22fdc8dfba71.png">

**Comment by banditFox** [comment] 2023-02-01 15:32
<img width="405" alt="Screenshot 2023-02-01 at 09 31 52" src="https://user-images.githubusercontent.com/89707695/216087489-51b6a555-0e5e-4aac-bb2f-f88a2c79579d.png">

**Comment by carlosala** [comment] 2023-02-01 16:36
It looks like $ZDOTDIR is not defined when running zsh. Where are you defining it?

**Comment by mcornella** [comment] 2023-02-01 16:38
It's probably defined in `.zlogin` such that only login sessions have this value defined. Instead, define it on `.zshenv` which is loaded for all zsh sessions.

**Comment by banditFox** [comment] 2023-02-01 17:20
If it works in visual studio code, shouldn't it work in iTerm2?

**Comment by carlosala** [comment] 2023-02-01 17:22
It depends on how vscode starts the terminal, I'm not sure. Even though, it's really recommended to move your zdotdir variable to `zshenv`.

**Comment by banditFox** [comment] 2023-02-01 17:33
where would i find zshenv.  I ran a search for it, but it's not found.

**Comment by mcornella** [comment] 2023-02-01 17:37
In your home directory, `~/.zshenv`. When a shell session is started as login the `.zlogin` file is read (for example with `zsh -l`). Otherwise it isn't sourced, which would explain the difference in one or the other.

**Comment by banditFox** [comment] 2023-02-01 17:39
<img width="732" alt="Screenshot 2023-02-01 at 11 39 24" src="https://user-images.githubusercontent.com/89707695/216120416-32a5536e-f449-41dc-a29a-abd8428d7177.png">

**Comment by banditFox** [comment] 2023-02-01 17:40
not seing zshenv in my home directory.

**Comment by banditFox** [comment] 2023-02-01 17:42
Interestingly enough I DO see ohmyzsh/oh-my-zsh.sh which terminal2 says does not exist.

**Comment by mcornella** [comment] 2023-02-01 17:45
I don't see a .zlogin file either. Where did you define the `ZDOTDIR` variable?

In any case, you can create the `.zshenv` file yourself, but I don't see much point in doing that if it is the same as the home directory, as that's already the default.

Instead of `$ZDOTDIR` you can use `$HOME` if that's the case.

**Comment by mcornella** [comment] 2023-02-01 17:46
Disregard that, I believe this is a bug in the installer. Let me reproduce that and get back to you with a fix.

**Comment by banditFox** [comment] 2023-02-01 18:00
I have to run an errand, I'll be back online in about an hour or so.

**Comment by banditFox** [comment] 2023-02-01 19:59
You know, I installed all this using the console/terminal in Visual Studio Code.
If I attempted a 're-install' from zsh, think that would fix it, or would I tear it up even more?

**Comment by mcornella** [comment] 2023-02-01 20:18
It looks like VS Code sets `$ZDOTDIR` for some reason: https://github.com/microsoft/vscode/issues/157128.

As it sets it to `$HOME` judging by your experience, I will add a case on the installer so that it is ignored (i.e. not used in the .zshrc) if `ZDOTDIR=$HOME`.

**Comment by mcornella** [comment] 2023-02-01 20:45
In the meantime you can remove the .zshrc file and ohmyzsh folder and
reinstall from within iTerm2 to get this set up correctly.

**Comment by banditFox** [comment] 2023-02-01 20:54
yup...  running on iTerm2 now.

**Comment by mcornella** [comment] 2023-02-02 07:54
This should be fixed now. Thank you for reporting!

**Closed** 2023-02-02 07:53 UTC

**Comment by banditFox** [comment] 2023-02-02 13:56
Thanks, everyone for the help.  Everything is running right now.
