### ISSUE TITLE
error iconv: iconv_open(, -t): Invalid argument

### ISSUE THREAD

**Issue by felipeska** [ohmyzsh/ohmyzsh#12479] opened 2024-06-05 16:51 UTC
### Describe the bug

after install Oh My Zsh the next error is rendering in the terminal.

```bash
iconv: iconv_open(, -t): Invalid argument
Error converting string from  to UTF-8
```

### Steps to reproduce

1) run the installer 
`sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"`
2) open the terminal.

### Expected behavior

open the terminal without errors.

### Screenshots and recordings

<img width="647" alt="Screenshot 2024-06-05 at 11 49 55 AM" src="https://github.com/ohmyzsh/ohmyzsh/assets/613443/cc7bead8-51ad-41ac-b09e-7dae56822f12">

### OS / Linux distribution

macOS Sonoma 14.5

### Zsh version

5.9

### Oh My Zsh version

master (efdfe2f)

### Terminal emulator

iTerm2

### If using WSL on Windows, which version of WSL

None

**Comment by carlosala** [comment] 2024-06-05 17:09
Duplicate of #11645

**Closed by carlosala** 2024-06-05 17:09 UTC
Labels: Bug

**Comment by felipeska** [comment] 2024-06-05 17:12
Thank you @carlosala !
