### ISSUE TITLE
omz with Angular 9 using nvm and breezy falsely believes the git repo is a bzr repo

### ISSUE THREAD

**Issue by dalu** [ohmyzsh/ohmyzsh#8644] opened 2020-02-18 17:47 UTC
**Describe the bug**

I'm using nvm to manage node. I have updated angular cli to v9. I'm using archlinux. There has been a rename in the packages from bzr to breezy recently.
I created a new angular project.
```
ng new --prefix dalu --routing --style scss phan
cd phan
```
it took a very long time where I couldn't ctrl+c abort or do anything in the terminal.
I thought it was a terminal issue but the same result was also in other terminals (xterm aterm etc)

When it finally got through the prompt showed:
`darko@dev  ~/WebProjects/phan   master bzr@1 `

So zsh believes that this directory is a bazaar directory, altough git is used.

Once I uninstalled breezy from the system along with packages that require it, the prompt shows

`darko@dev  ~/WebProjects/phan   master `
and doesn't take ages to show.

here's the directory list. There's nothing to suggest that this directory is a bazaar directory.

```
drwxr-xr-x   6 darko darko 1.0K Feb 18 18:29 .
drwxr-xr-x 149 darko darko 5.0K Feb 18 18:28 ..
-rw-r--r--   1 darko darko 3.6K Feb 18 18:28 angular.json
-rw-r--r--   1 darko darko  429 Feb 18 18:28 browserslist
drwxr-xr-x   3 darko darko 1.0K Feb 18 18:28 e2e
-rw-r--r--   1 darko darko  246 Feb 18 18:28 .editorconfig
drwxr-xr-x   8 darko darko 1.0K Feb 18 18:43 .git
-rw-r--r--   1 darko darko  631 Feb 18 18:28 .gitignore
-rw-r--r--   1 darko darko 1016 Feb 18 18:28 karma.conf.js
drwxr-xr-x 865 darko darko  30K Feb 18 18:29 node_modules
-rw-r--r--   1 darko darko 1.3K Feb 18 18:28 package.json
-rw-r--r--   1 darko darko 484K Feb 18 18:29 package-lock.json
-rw-r--r--   1 darko darko 1021 Feb 18 18:28 README.md
drwxr-xr-x   5 darko darko 1.0K Feb 18 18:28 src
-rw-r--r--   1 darko darko  210 Feb 18 18:28 tsconfig.app.json
-rw-r--r--   1 darko darko  543 Feb 18 18:28 tsconfig.json
-rw-r--r--   1 darko darko  270 Feb 18 18:28 tsconfig.spec.json
-rw-r--r--   1 darko darko 2.0K Feb 18 18:28 tslint.json
```

.zshrc
```
plugins=(
  archlinux
  git
  github  
  go
  gnu-utils
  history
  node
  npm
  nvm
)
```

**Desktop (please complete the following information):**
 - OS / Distro: Arch
 - Latest ohmyzsh Update?: yes
 - ZSH Version: 5.8
 - Terminal emulator gnome-terminal xterm aterm

**Comment by mcornella** [comment] 2020-02-18 18:19
You're using the agnoster theme. This is a duplicate of #8237. Please [test this patch](https://github.com/ohmyzsh/ohmyzsh/issues/8237#issuecomment-587064259) and comment there if it works.

**Closed by mcornella** 2020-02-18 18:19 UTC
Labels: Type: support
