### ISSUE TITLE
colorize plugin is not working with the cless command (Using Chroma in iTerm2 on MacOS)

### ISSUE THREAD

**Issue by lhoupert** [ohmyzsh/ohmyzsh#11354] opened 2022-11-24 18:04 UTC
### Describe the bug

Running `cless` command on iTerm (MacOS v12.1) is not returning a colorized output while `ccat <filename> | less ` is returning the expected output. See example below

```shell
cless test_script.py
```
![Screenshot 2022-11-24 at 17 50 15](https://user-images.githubusercontent.com/10154151/203843445-da3d8e46-f8d6-4f4a-a920-c66298267cc7.png)

while 
```shell
 ccat test_script.py | less
```
is returning :
![Screenshot 2022-11-24 at 17 52 50](https://user-images.githubusercontent.com/10154151/203843881-e2a7273d-c98a-4277-a682-0599acb0eba2.png)

### Steps to reproduce

1. Enable the plugin `colorize` in `.zshrc`, activate `CHROMA`:

```text
plugins=(
	colorize
	...
)

ZSH_COLORIZE_TOOL=chroma
ZSH_COLORIZE_STYLE="catppuccin-mocha"
#ZSH_COLORIZE_CHROMA_FORMATTER=terminal256

source $ZSH/oh-my-zsh.sh

```

3. Create a file named `test_script.py` and copy the content below: 
```python
# Generate Strong Random Passwords
import random
import string

import django

# This script will generate an 18 character password
word_length = 18
# Generate a list of letters, digits, and some punctuation
components = [string.ascii_letters, string.digits, "!@#$%&"]
# flatten the components into a list of characters
chars = []
for clist in components:
    for item in clist:
        chars.append(item)


def generate_password():
    # Store the generated password
    password = []
    # Choose a random item from 'chars' and add it to 'password'
    for i in range(word_length):
        rchar = random.choice(chars)
        password.append(rchar)
    # Return the composed password as a string
    return "".join(password)


# Output generated password
print(generate_password())

```

6. Run the command 
```shell
 cless test_script.py
```

### Expected behavior

The expected behavior should be an output similar to :
```shell
 ccat test_script.py | less
```

![Screenshot 2022-11-24 at 17 52 50](https://user-images.githubusercontent.com/10154151/203843881-e2a7273d-c98a-4277-a682-0599acb0eba2.png)

### OS / Linux distribution

macOS 12.6.1

### Zsh version

5.8.1

### Terminal emulator

iTerm2

**Comment by monoxygen** [comment] 2022-12-18 16:11
One problem I see is that `colorize_less` needs to forward `ZSH_COLORIZE_CHROMA_FORMATTER` (added by #8824) when invoking `colorize_cat`. That said, the issue description has `ZSH_COLORIZE_CHROMA_FORMATTER` commented out so perhaps there's something else going on too.
At least locally on my machine (macOS, Terminal.app), I do use `ZSH_COLORIZE_CHROMA_FORMATTER=terminal256` and my `cless` output is not correct unless I fix it to forward `ZSH_COLORIZE_CHROMA_FORMATTER`.

**Comment by mcornella** [comment] 2024-08-11 18:38
I'm not able to reproduce this at all on iTerm2, macOS and chroma. I know this is very old, but if you are still having this issue, having the trace of the `colorize_less` function would show exactly where the issue is. You can enable a trace with `functions -t colorize_less`, and then running `cless <file>`. After exiting less, you'll see the trace.

With this said, I don't think the `chroma` and `pygmentize` tools are worth supporting anymore in this plugin. Installing [bat](https://github.com/sharkdp/bat) which is bundled in all major package managers, we can substitute both functions like so:

```sh
alias ccat='bat -P'
alias cless='bat'
```

I'm going to close this issue, mainly because it's old and I presume you're either not interested or not having the issue anymore. If that's not the case, please go ahead and reopen it with a trace of the function as shared above.

Thanks!

**Closed by mcornella** 2024-08-11 18:38 UTC
