### ISSUE TITLE
Slow to type commands

### ISSUE THREAD

**Issue by EricMzky** [ohmyzsh/ohmyzsh#10850] opened 2022-04-13 07:11 UTC
### Describe the bug

In normal Linux terminal, the response speed of tapping command is ok, but for example, when entering a very large project, it is git project, this repository may have hundreds of branches, we only download one branch, and then CD into the project, the input command will be very slow. How can I solve this problem, it affects the use; What command can I use to do a warehouse synchronization and never be sluggish again, thank you

### Steps to reproduce

In normal Linux terminal, the response speed of tapping command is ok, but for example, when entering a very large project, it is git project, this repository may have hundreds of branches, we only download one branch, and then CD into the project, the input command will be very slow. How can I solve this problem, it affects the use; What command can I use to do a warehouse synchronization and never be sluggish again, thank you

### Expected behavior

In normal Linux terminal, the response speed of tapping command is ok, but for example, when entering a very large project, it is git project, this repository may have hundreds of branches, we only download one branch, and then CD into the project, the input command will be very slow. How can I solve this problem, it affects the use; What command can I use to do a warehouse synchronization and never be sluggish again, thank you

### OS / Linux distribution

ubunt20.04

### Zsh version

The latest version

### Terminal emulator

Tabby

**Comment by mcornella** [comment] 2022-04-13 11:18
Duplicate of #10175

**Closed by mcornella** 2022-04-13 11:18 UTC
