### ISSUE TITLE
Agnoster theme prompt extremly slow in mercurial

### ISSUE THREAD

**Issue by MerliX** [ohmyzsh/ohmyzsh#4116] opened 2015-07-02 10:11 UTC
Code here https://github.com/robbyrussell/oh-my-zsh/blob/3d2bf227ea2b37d351ac3846627f28151e0a4480/themes/agnoster.zsh-theme#L111 runs very slow (mac yosemite)

**Comment by apjanke** [comment] 2015-07-02 23:30
FYI, if you're going to link to lines of code (or files for that matter) in a bug report, you should link to a specific commit, instead of "master" or another branch name. Otherwise, later commits may shift around line numbers and your link will be pointing at a different piece of code. (For example, we're about to merge a commit to `agnoster` that will probably shift everything down a few lines, and your link will be pointing in to the `zstyle` commands inside `prompt_git`.)

https://github.com/robbyrussell/oh-my-zsh/blob/3d2bf227ea2b37d351ac3846627f28151e0a4480/themes/agnoster.zsh-theme#L111

**Comment by MerliX** [comment] 2015-07-03 08:01
@apjanke thanks for advice

**Comment by apjanke** [comment] 2015-07-03 15:33
How slow is "extremely slow" for you? This stuff is all relative. :)

I'm trying it out on OS X 10.9.5 Mavericks, on an SSD MacBook Pro. In a newly created Hg repo, it feels like it takes between half a second and a second to issue the prompt. That feels pretty slow to me. But is also not a huge surprise: this is not a very fast theme, and it's doing `hg` shellouts.

This could maybe be improved by consolidating the `hg` calls and doing parsing with native `zsh` string stuff afterwards.

**Comment by apjanke** [comment] 2015-07-03 15:40
Oh, yeah, we can totally speed this up. Half those `hg` calls are unnecessary. I'll give it a try when I have some free time, maybe later today.

**Comment by MerliX** [comment] 2015-07-03 15:54
I did a quick fix for this, but it is not so functional. However, probably it will help

```
prompt_hg() {
  local rev_branch st hg_status
  rev_branch=$(hg id -n -b 2>/dev/null)

  if [ ! -z "$rev_branch" ] ; then
    st=""
    hg_status=`hg st`
    if `echo $hg_status | grep -q "^\?"`; then
      prompt_segment red black
      st='±'
    elif `echo $hg_status | grep -q "^[MA]"`; then
      prompt_segment yellow black
      st='±'
    else
      prompt_segment green black
    fi
    echo -n "☿ $rev_branch" $st
  fi
}
```

By the way, I switched my console to https://github.com/bhilburn/powerlevel9k witch is way more fast from-the-box

**Comment by apjanke** [comment] 2015-07-03 16:05
Thanks!

Interesting. PowerLevel9K is relying entirely on `zsh`'s own `vcs_info` for the Hg stuff, instead of rolling its own. I'll look in to that and see if it's an option for us, too.

**Comment by dritter** [comment] 2015-07-10 18:07
@apjanke Jep. `vcs_info` uses mostly `hexdump` to get the information from the repository and invokes mercurial only once.

**Comment by apjanke** [comment] 2015-07-11 19:05
Oh, nice. I see some `vcs_info` in my future, in that case.

**Comment by apjanke** [comment] 2015-11-06 22:33
Agnoster now has its own repo, https://github.com/agnoster/agnoster-zsh-theme, and is using Zsh `vcs_info`. Can you give the upstream theme a try and see if it's still slow for you?

**Comment by MerliX** [comment] 2015-11-09 13:35
Well, its not slow anymore, but it neither shows hg info in zsh prompt =) Built-in agnoster theme is still slow in hg repo. I am happy with powerlevel9k theme by the way

**Comment by apjanke** [comment] 2015-11-09 15:10
Oh yeah, the `hg` support was an OMZ addition. Nevermind about asking upstream. :)

**Comment by Cypher1** [comment] 2017-01-24 01:08
Will this improve anytime soon? I'm having similar issues with bullettrain (which is based on agnoster).
I'm having multiple seconds of waiting time between prompt renders in a largish hg repo.

**Comment by caugner** [comment] 2017-09-14 18:13
Steps to reproduce:

```
hg clone https://hg.mozilla.org/mozilla-central
cd mozilla-central
```

**Comment by caugner** [comment] 2017-09-14 18:54
The lag actually stems from the three calls to `hg id` on lines [155](https://github.com/robbyrussell/oh-my-zsh/blob/d848c94804918138375041a9f800f401bec12068/themes/agnoster.zsh-theme#L155) and [172/173](https://github.com/robbyrussell/oh-my-zsh/blob/d848c94804918138375041a9f800f401bec12068/themes/agnoster.zsh-theme#L172-L173) or more accurately the first two calls:

```sh
hg clone https://hg.mozilla.org/mozilla-central
cd mozilla-central

time hg id
# hg id  0.66s user 0.35s system 99% cpu 1.020 total

time hg id -n
# hg id -n  0.65s user 0.38s system 99% cpu 1.032 total

time hg id -b
# hg id -b  0.08s user 0.03s system 99% cpu 0.117 total
```

**Comment by caugner** [comment] 2017-09-14 20:59
In theory, there is some potential:

```
hg clone https://hg.mozilla.org/mozilla-central
cd mozilla-central
```

1. Replace `hg id` with `hg root`:

```
# hg id  0.70s user 0.40s system 99% cpu 1.103 total
# hg root  0.10s user 0.04s system 99% cpu 0.137 total
```

2. Replace double `hg st` with single `( hg st -uma | cut -c -1 | sort | uniq | paste -d, -s; )`

```
# hg st  1.29s user 0.43s system 16% cpu 10.316 total
# ( hg st -uma | cut -c -1 | sort | uniq | paste -d, -s; )  1.36s user 0.42s system 101% cpu 1.758 total
```

3. Replace `hg id -n` and `hg id -b` with single `hg id -nb`

```
# hg id -n  0.69s user 0.39s system 99% cpu 1.076 total
# hg id -b  0.10s user 0.03s system 99% cpu 0.124 total
# hg id -nb  0.66s user 0.39s system 99% cpu 1.057 total
```

In practice, this does improve the situation only slightly:

```
# Before
# ( prompt_hg > /dev/null; )  2.86s user 1.27s system 99% cpu 4.138 total
# After
# ( prompt_hg > /dev/null; )  2.17s user 0.87s system 100% cpu 3.024 total
```

**Comment by maelvalais** [comment] 2018-01-04 11:24
Wow, using `chg` instead of hg (just put `alias hg=chg` in your `.zshrc`) seems to make `prompt_hg` as fast as the git prompt!

**Comment by caugner** [comment] 2018-04-25 19:32
> I guess it is only available on the latest hg versions?

What version of `hg` do you run? Unfortunately, `chg` is not available for me in Mercurial 4.3.2.

**Comment by sylvestre** [comment] 2018-09-05 07:01
Looks like it is https://www.mercurial-scm.org/wiki/CHg (afaik, not shipped with mercurial)
And indeed, the mercurial extension isn't usable on large repo like Firefox...

**Comment by maelvalais** [comment] 2018-09-05 07:27
Ahh... I just noticed that this `chg` is in `contrib/` and thus probably not compiled/installed by default by standard package managers. The reason I have it is that Homebrew installs `chg` by default (see [formula](https://github.com/Homebrew/homebrew-core/blob/b17b51701ebd8d62e55d9a1d68617c385a5ac26a/Formula/mercurial.rb#L23-L28)).

Unfortunate that it is not shipped by default...

**Comment by caugner** [comment] 2018-09-06 23:01
I have disabled the status in mercurial repositories now by adding `functions[prompt_hg]=""` to my `.zshrc`.

**Comment by Ilphrin** [comment] 2018-11-07 15:54
Hi!

Is there any news about this issue? I have the exact same problem with firefox repository with agnoster theme prompt.

**Comment by nagyf** [comment] 2018-11-22 18:10
Just checking in, I'm experiencing the same problem with agnoster theme and the mozilla unified repository...
caugner's solution is a great workaround

**Comment by yagehu** [comment] 2020-08-08 03:01
> I have disabled the status in mercurial repositories now by adding `functions[prompt_hg]=""` to my `.zshrc`.

Is there a way to disable mercurial prompt just for a repository? Similar to `git config oh-my-zsh.hide-status 1`.

**Comment by robbyrussell** [comment] 2023-10-13 21:30
Going to close this and assume any edgecases can be sorted with a per-project workaround

**Closed by robbyrussell** 2023-10-13 21:30 UTC
Labels: Area: theme, Enhancement
