### ISSUE TITLE
kubectl plugin: autocompletions no long work out of the box

### ISSUE THREAD

**Issue by djfinnoy** [ohmyzsh/ohmyzsh#10585] opened 2022-01-13 12:26 UTC
### Describe the bug

After installing my setup on a new laptop, I noticed that `kubectl` completions were not working.

In the past, the following line was sufficient for getting autocompletions:
```
plugins=(kubectl)
```

Now, I need to add another line at the bottom of .zshrc:
```
source <(kubectl completion zsh)
```

### Steps to reproduce

Install zsh, kubectl, and kubectl plugin.

### Expected behavior

`plugin=(kubectl)` should give autocompletions.

### OS / Linux distribution

Regolith 1.6

### Zsh version

5.8

### Terminal emulator

GNOME terminal

### Additional context

kubectl is installed via `asdf`, but I get she same problem with the official installtion instructions.

**Comment by mcornella** [comment] 2022-01-13 12:30
Duplicate of #10581.

**Closed by mcornella** 2022-01-13 12:30 UTC

**Comment by mcornella** [comment] 2022-01-13 15:12
Subscribe to the other issue for updates.
