### ISSUE TITLE
Issues with midnight commander (mc)

### ISSUE THREAD

**Issue by jjmarcos** [ohmyzsh/ohmyzsh#11752] opened 2023-06-14 18:22 UTC
### Describe the bug

Midnight Commander (mc) is not working properly with ohmyzsh.
I'm using an Apple iMac with Ventura 13.4. "mc" has been installed using MacPorts, its version is 4.8.29.

### Steps to reproduce

It's kind of weird. Basically, if I open "mc" on my home folder, it works just fine.
However, if I change directory to something else like "Downloads" and run "mc" from there, it takes around 10 seconds or so to actually show the mc interface. Then when I press F10 to exit, a message appears indicating "The shell is still active. Quit anyway?"

I have created a new user on my Mac so ohmyzsh is not configured for this new guy. Using this new account "mc" works perfectly fine no matter from which folder I launch it.

I'm attaching the logs: _REDACTED_

### Expected behavior

mc should work no matter from where directory you launch it

### OS / Linux distribution

MacOS ventura 13.4

### Zsh version

5.9

### Terminal emulator

Terminal.app

### If using WSL on Windows, which version of WSL

None

**Comment by robbyrussell** [comment] 2023-10-08 12:19
@jjmarcos

Could you confirm that you see a similar issue without Oh My Zsh? via Bash or perhaps by temporarily disabling Oh My Zsh?

To do that, you could:

```shell

  % mv ~/.zshrc ~/.zshrc-disabled
  % zsh
```

after your testing, just reverse that

```sh
  % mv ~/.zshrc-disabled ~/.zshrc
  % zsh
```

**Comment by mcornella** [comment] 2023-10-23 11:34
Can you check whether adding the following at the end of your `.zshrc` file (with OMZ enabled) has any impact?
```sh
omz_termsupport_cwd(){}
add-zsh-hook -d precmd omz_termsupport_cwd
```

**Comment by gasull** [comment] 2023-11-12 00:51
A workaround:

```bash
alias mc='SHELL=/usr/bin/bash /usr/bin/mc'
```

So you'll use bash when within Midnight Commander and zsh the rest of the time.

**Comment by mcornella** [comment] 2023-11-30 16:38
Going to close this as duplicate of #11353. Please see my latest comment for instructions on helping debug the issue further.

**Closed by mcornella** 2023-11-30 16:38 UTC
Labels: Status: needs repro

**Comment by lastsky** [comment] 2024-06-06 11:57
another solution for me: alias at `.zshrc`:

```shell
alias mc="SHELL=/bin/bash mc"
```

**Comment by HaleTom** [comment] 2024-07-01 15:54
In my function to set the prompt strings, and *before* setting `$RPS1`, I have:

```
# No RHS prompt running inside of Midnight Commander
if [[ $MC_SID ]]; then unset RPS1; return; fi
```

**Comment by JSouthGB** [comment] 2024-07-04 12:27
I've had this same issue since some time last year. I use p10k rather than omz. And I've encountered the issue on arch and debian (I don't have a mac to test with). As @BigBobDalton mentioned, when using `sudo` I don't get the message or slow start up.

I finally decided to search a solution after setting up a fresh Truenas Scale installation and experiencing the same problem. @lastsky's solution worked for me. With a minor change for Truenas since they don't let you install anything from the repositories. I created a `~/.bin` directory in my home folder and copied the mc binary into it. Below is my alias.

```
alias mc="SHELL=/usr/bin/bash ~/.bin/mc"
```

That works for Truenas and `alias mc="SHELL=/usr/bin/bash mc"` works for my arch and debian installations.
