### ISSUE TITLE
Recent yarn plugin changes add a significant amount to shell startup time

### ISSUE THREAD

**Issue by bjulian5** [ohmyzsh/ohmyzsh#10396] opened 2021-11-07 18:21 UTC
### Describe the bug

Shell start up time has significantly increased due to a recent change to the Yarn plugin. I ran a `git bisect` and narrowed down the culprit to this commit https://github.com/ohmyzsh/ohmyzsh/commit/f0bbef1a070b7b00a36010c44af3c88807c73e6f .

### With yarn enabled
```
$for i in $(seq 1 10); do /usr/bin/time zsh -i -c exit; done
        0.36 real         0.22 user         0.10 sys
        0.29 real         0.19 user         0.08 sys
        0.29 real         0.19 user         0.08 sys
        0.32 real         0.21 user         0.09 sys
        0.29 real         0.19 user         0.08 sys
        0.30 real         0.19 user         0.08 sys
        0.30 real         0.19 user         0.08 sys
        0.29 real         0.19 user         0.08 sys
        0.30 real         0.19 user         0.08 sys
        0.29 real         0.19 user         0.08 sys
```

### With Yarn disabled
```
$ for i in $(seq 1 10); do /usr/bin/time zsh -i -c exit; done
        0.39 real         0.22 user         0.14 sys
        0.12 real         0.07 user         0.04 sys
        0.12 real         0.07 user         0.04 sys
        0.12 real         0.07 user         0.04 sys
        0.12 real         0.07 user         0.04 sys
        0.12 real         0.07 user         0.04 sys
        0.12 real         0.07 user         0.04 sys
        0.12 real         0.07 user         0.04 sys
        0.12 real         0.07 user         0.04 sys
        0.12 real         0.07 user         0.04 sys
```

### Expected behavior

The startup time for the yarn plugin should not take this long to load. I suspect the culprit is the command `yarn global bin` which was introduced the commit I outlined earlier
```
$for i in $(seq 1 10); do /usr/bin/time yarn global bin; done
/usr/local/bin
        0.37 real         0.12 user         0.08 sys
/usr/local/bin
        0.16 real         0.11 user         0.04 sys
/usr/local/bin
        0.17 real         0.11 user         0.04 sys
/usr/local/bin
        0.17 real         0.11 user         0.04 sys
/usr/local/bin
        0.17 real         0.11 user         0.04 sys
/usr/local/bin
        0.17 real         0.11 user         0.04 sys
/usr/local/bin
        0.17 real         0.11 user         0.04 sys
/usr/local/bin
        0.17 real         0.11 user         0.04 sys
/usr/local/bin
        0.17 real         0.11 user         0.04 sys
/usr/local/bin
        0.17 real         0.11 user         0.04 sys

```

### OS / Distro

macOS Montery

### Zsh version

5.8

### Terminal emulator

alacritty

**Comment by mcornella** [comment] 2021-11-07 21:31
Duplicate of #10290.

**Closed by mcornella** 2021-11-07 21:31 UTC
Labels: Bug
