### ISSUE TITLE
parameter autocomplete working in one instance but not the other one

### ISSUE THREAD

**Issue by thomasd3** [ohmyzsh/ohmyzsh#9088] opened 2020-07-06 16:34 UTC
I have two ohmyzsh installs:

- One of MacOS / iTerm2
- The other on CentOS

To take docker as an example, on the CentOS shell, I can do this:

> docker cont[tab]

and it autocompletes to 'docker container'

but on the MacOS install, it tries to auto complete the local file names and not the parameters.

how can I get it to auto complete the parameters in priority?

**Comment by voldemortensen** [comment] 2020-07-06 16:50
This used to work for me on MacOS, but recently stopped working. I've been trying to figure it out but haven't been able to find the culprit.

**Comment by thomasd3** [comment] 2020-07-06 16:53
are you using iTerm2 as well?

**Comment by voldemortensen** [comment] 2020-07-06 16:56
I am using Alacritty, but I just checked in iTerm2 and the issue is the same.

**Comment by thomasd3** [comment] 2020-07-06 17:01
so I guess this falls more into the bug category than support :)

**Comment by voldemortensen** [comment] 2020-07-06 23:02
Just ran across this: I've been hitting this issue using the `kubectl` plugin. When I'm in one k8s context I can do `k get po<tab><tab>` and get tab completion of `poddisruptionbudgets.policy`, `pods`, `podsecuritypolicies.policy`, and `podtemplates`, as I should. If I switch to a different k8s context, `k get po<tab><tab>` shows results from the filesystem.

**Comment by thomasd3** [comment] 2020-07-07 13:06
so just different context but same os, shell, everything?

**Comment by mcornella** [comment] 2020-07-09 08:43
@thomasd3 in macOS the installer must not be installing the completion file. You can enable the docker plugin, or install the completion file manually following the instructions in their docs: https://docs.docker.com/compose/completion/#zsh.

@voldemortensen can you capture a trace of the completion both when it works and when it doesn't? To do that, write the command to be completed and press `CTRL`+`X` followed by `?`.

**Comment by thomasd3** [comment] 2020-07-09 20:58
I've had this in my .zshrc file: plugins=(docker docker-compose)
for a long time, it never worked and I completely forgot about.
Is there a log I can check to make sure these get loaded properly?

**Comment by voldemortensen** [comment] 2020-07-11 01:34
@mcornella That key combination isn't doing anything for me. I've tried in Alacritty, iTerm2, and Mac Terminal.

**Comment by mcornella** [comment] 2020-07-11 07:04
It should be two key presses: first CTRL+X, then ?.

>

**Comment by voldemortensen** [comment] 2020-07-16 18:50
I know, and that's what I've been doing.

**Comment by thomasd3** [comment] 2020-07-16 19:39
on my end, with docker, I get this:
<img width="735" alt="image" src="https://user-images.githubusercontent.com/14313218/87714904-c87a9300-c7ac-11ea-8e19-2e5d493cf2ca.png">

**Comment by mcornella** [comment] 2021-04-07 19:49
Reviving this. Enabling the `docker` plugin should be enough to get this to work. Reopen if it doesn't and you're running the latest OMZ version (`omz update`).

**Closed by mcornella** 2021-04-07 19:49 UTC
Labels: Support, Topic: completion
