### ISSUE TITLE
Oh My Zsh hangs because of slow `git status` calls

### ISSUE THREAD

**Issue by JulianFerry** [ohmyzsh/ohmyzsh#9046] opened 2020-06-18 17:26 UTC
**Describe the bug**

Oh My Zsh makes my terminal hang after a command completes in Linux. I also found [this Linux forum post](https://bbs.archlinux.org/viewtopic.php?id=228939) which helped me confirm that Oh My Zsh is the culprit.

This happens to me on a Ubuntu VM inside Virtualbox, but it may generalise to non-VM setups. In my VM I have a `project/` folder, in which I have mounted a very large `data/` folder (34GB). This problem only happens when the folder is mounted.

Whenever I `cd` to the project folder / any of its subfolders (not necessarily the `data` folder), or run a command (eg `ls`), the command completes but my terminal hangs for a very long time *(around the same amount of time it took for the directory to mount...)*. If I hit Ctrl + C then the terminal stops hanging and the command has completed, but the zsh prompt is just `->`.

When I uninstall Oh My Zsh, the issue dissappears. Experimentation shows that I get the issue when I mount my directory with `vboxsf` or via my network with `SMB`, but not when the data exists directly inside my VM. Oh My Zsh must be doing something with those mounts after each command...

**To Reproduce**

- Run Ubuntu VM (e.g. Virtualbox)
- `mount` a large volume to the VM (E.g. with `vboxsf` or `SMB` via a network share)
- `cd` to the parent directory of that volume
- Wait a long time for the command to finish

**Expected behavior**

Shell becomes responsive after commands finish, like in normal zsh.

**Desktop (please complete the following information):**

 - OS / Distro: Ubuntu VM inside Virtualbox
 - Latest ohmyzsh Update?: Yes
 - ZSH Version: Latest
 - Terminal emulator: Any

**Comment by JulianFerry** [comment] 2020-06-18 17:28
This is meant to be a Bug report, I'm not sure what happened with the label there...

**Comment by nylar357** [comment] 2020-06-18 17:35
I've been running into this in my oscp class VMware and have been wondering about it for a while.  Can confirm it.

**Comment by mcornella** [comment] 2020-06-18 19:57
Try setting trace mode before doing the cd: `set -xv; cd directory; set +xv`, then post the trace to see what the shell is doing.

**Comment by JulianFerry** [comment] 2020-06-19 08:29
> Try setting trace mode before doing the cd: `set -xv; cd directory; set +xv`, then post the trace to see what the shell is doing.

Thanks for the suggestion. This only returns the following:
```
> set -xv; cd directory; set +xv
+zsh:10> cd directory
+zsh:10> set +xv
```

The same for `ls`. Previously I tried a live profiling command which returned a much more in-depth trace, but I don't remember what command that was. The result of it was that the whole trace ran, then the shell hanged as usual, and then the prompt reappeared with no further trace. So maybe OMZ is doing something silently?

**Comment by JulianFerry** [comment] 2020-06-19 09:03
Ah interesting... so it seems like **git** is the culprit here. I just ran `git status` and it printed this:
```
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:

[...]

It took 13.57 seconds to enumerate untracked files. 'status -uno'
may speed it up, but you have to be careful not to forget to add
new files yourself (see 'git help status').
```

In my `.gitignore` I have the following ([copied from this stackoverflow Q&A](https://stackoverflow.com/questions/46301811/gitignore-all-files-in-folders-but-keep-folder-structure)):
```
# Ignore data/ files and folders recursively
# Exclude subfolders from the ignore rules
# Now we can whitelist .gitkeep in those subfolders
data/**
!data/**/
!data/**/.gitkeep
```

Changing this to:
```
data/**
# !data/**/
!data/**/.gitkeep
```
fixes the issue. Which is strange, since my files were not being commited, but `git` may be reading the `.gitignore` differently when it makes it status checks...

I'm going to add a comment on the stackoverflow answer to highlight this, as well as raise an issue for git. @nylar357 can you confirm whether git is the culprit for you here as well?

**For Oh My Zsh**: it might be a good idea to report this line from the `git` command which it uses to display the branch: "*It took 13.57 seconds to enumerate untracked files. 'status -uno'*"

**Comment by mcornella** [comment] 2020-06-19 09:50
Your data folder is a git repository? The trace you posted doesn't show anything happening, if there was a git command being run, it'll show up there. Can you post your zshrc file?

**Comment by JulianFerry** [comment] 2020-06-19 10:03
No my data folder is inside my `project` folder which is a git repository.

**Comment by nylar357** [comment] 2020-06-20 15:11
Confirmed on VM Player!  : )

It's such a relief to have that fixed.  Thanks

**Comment by JulianFerry** [comment] 2020-07-19 14:11
Just to bump this thread:
Do the `ohmyzsh` developers think this is worth addressing? Perhaps by including the `git` message:
```
It took 13.57 seconds to enumerate untracked files. 'status -uno'
```

**Comment by davidhcefx** [comment] 2020-08-03 19:50
@JulianFerry 
Instead of disabling git status entirely via `git status -uno`, I suggest another workaround however.
In [git.zsh](https://github.com/ohmyzsh/ohmyzsh/blob/master/lib/git.zsh#L41) line 41, add a `timeout [duration]` prefix, like the following:

```diff
- STATUS=$(__git_prompt_git status ${FLAGS} 2> /dev/null | tail -n1)
+ STATUS=$(timeout 1s __git_prompt_git status ${FLAGS} 2> /dev/null | tail -n1)
```

**Comment by JulianFerry** [comment] 2020-08-05 11:22
@davidhcefx 
> Instead of hiding untracked files _entirely_ via `git status -uno`, I suggest another workaround.

That's a good idea, I'm all for it. Although if it times out it would still be good for the user to know that it's **git** that caused it

**Comment by mcornella** [comment] 2020-10-10 19:46
This is a duplicate of https://github.com/ohmyzsh/ohmyzsh/issues/5066.

**Closed by mcornella** 2020-10-10 19:46 UTC
Labels: support

**Comment by Crazy-Ginger** [comment] 2021-07-17 02:07
> @JulianFerry
> Instead of hiding untracked files _entirely_ via `git status -uno`, I suggest another workaround.
> In [git.zsh](https://github.com/ohmyzsh/ohmyzsh/blob/master/lib/git.zsh#L9) line 9, add a `timeout [duration]` prefix, like the following:
> 
> ```diff
> - GIT_OPTIONAL_LOCKS=0 command git "$@"
> + GIT_OPTIONAL_LOCKS=0 command timeout 1s git "$@"
> ```
> 
> This way, dirty git folders can be [highlighted](https://cloud.githubusercontent.com/assets/2618447/6316862/70f58fb6-ba03-11e4-82c9-c083bf9a6574.png) properly, as long as it doesn't hang the terminal. 😃

Is there any way to do this in a zshrc or does git.zsh itself need to be modified?

**Comment by mcornella** [comment] 2021-09-10 11:22
> > @JulianFerry
> > Instead of hiding untracked files _entirely_ via `git status -uno`, I suggest another workaround.
> > In [git.zsh](https://github.com/ohmyzsh/ohmyzsh/blob/master/lib/git.zsh?rgh-link-date=2021-07-17T02%3A07%3A15Z#L9) line 9, add a `timeout [duration]` prefix, like the following:
> > ```diff
> > - GIT_OPTIONAL_LOCKS=0 command git "$@"
> > + GIT_OPTIONAL_LOCKS=0 command timeout 1s git "$@"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This way, dirty git folders can be [highlighted](https://cloud.githubusercontent.com/assets/2618447/6316862/70f58fb6-ba03-11e4-82c9-c083bf9a6574.png) properly, as long as it doesn't hang the terminal. smiley
> 
> Is there any way to do this in a zshrc or does git.zsh itself need to be modified?

You can modify the `__git_prompt_git` function in your zshrc file:
```zsh
__git_prompt_git () {
	GIT_OPTIONAL_LOCKS=0 command timeout 1s git "$@"
}
```

**Comment by carusd** [comment] 2021-10-12 06:38
This was killing me forever, hide dirty didnt fix a thing, git gc didnt fix a thing either.

Until I remove all the files but the .git directory, then run `git checkout . ` to recover everything.

Suddenly everything went very quickly. It's silly, but worked.

**Comment by emrecio** [comment] 2022-07-07 12:43
> status -uno

Wow, I ran "git status -uno" and it fixed the slowness. Note, what changed, probably unrelated but reporting in case it helps someone out there, I consolidated user data "/home", "/usr/local" etc. from disparate drives to a new one, and upgraded the OS.

**Comment by Asxcvbn** [comment] 2024-12-30 13:47
> > > [@JulianFerry](https://github.com/JulianFerry)
> > > Instead of hiding untracked files _entirely_ via `git status -uno`, I suggest another workaround.
> > > In [git.zsh](https://github.com/ohmyzsh/ohmyzsh/blob/master/lib/git.zsh?rgh-link-date=2021-07-17T02%3A07%3A15Z#L9) line 9, add a `timeout [duration]` prefix, like the following:
> > > - GIT_OPTIONAL_LOCKS=0 command git "$@"
> > > + GIT_OPTIONAL_LOCKS=0 command timeout 1s git "$@"
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > This way, dirty git folders can be [highlighted](https://cloud.githubusercontent.com/assets/2618447/6316862/70f58fb6-ba03-11e4-82c9-c083bf9a6574.png) properly, as long as it doesn't hang the terminal. smiley
> > 
> > 
> > Is there any way to do this in a zshrc or does git.zsh itself need to be modified?
> 
> You can modify the `__git_prompt_git` function in your zshrc file:
> 
> __git_prompt_git () {
> 	GIT_OPTIONAL_LOCKS=0 command timeout 1s git "$@"
> }

i noticed sometime git status doesnot care about the sigterm sent by timeout. thus we might want to send sigkill

__git_prompt_git () {
    GIT_OPTIONAL_LOCKS=0 command timeout --signal=9 1s git "$@"
}
