### ISSUE TITLE
Getting string conversion error when I open terminal after installing oh-my-zsh

### ISSUE THREAD

**Issue by ranefattesingh** [ohmyzsh/ohmyzsh#12445] opened 2024-05-23 05:06 UTC
### Describe the bug

getting string conversion error when I open my shell on macOs, these errors were not coming before
<img width="764" alt="Screenshot 2024-05-23 at 10 28 51 AM" src="https://github.com/ohmyzsh/ohmyzsh/assets/41385129/0d960c8d-19be-48b6-889e-88994ac6467d">

### Steps to reproduce

install oh-my-zsh or update to the latest version

### Expected behavior

string conversion errors should not come

### OS / Linux distribution

macOs 14.4.1

### Zsh version

zsh 5.9 (x86_64-apple-darwin23.0)

### Terminal emulator

iTerm2

### If using WSL on Windows, which version of WSL

None

**Comment by carlosala** [comment] 2024-05-23 07:53
Duplicate of #11645
See https://github.com/ohmyzsh/ohmyzsh/issues/11645#issuecomment-1884685602

**Closed by carlosala** 2024-05-23 07:53 UTC
