### ISSUE TITLE
Always have an arrow in the front

### ISSUE THREAD

**Issue by kerthcet** [ohmyzsh/ohmyzsh#12603] opened 2024-08-07 11:21 UTC
### Describe the bug

Install `robbyrussell` with default config:
```
PROMPT="%(?:%{$fg_bold[green]%}%1{➜%} :%{$fg_bold[red]%}%1{➜%} ) %{$fg[cyan]%}%c%{$reset_color%}"
PROMPT+=' $(git_prompt_info)'

ZSH_THEME_GIT_PROMPT_PREFIX="%{$fg_bold[blue]%}git:(%{$fg[red]%}"
ZSH_THEME_GIT_PROMPT_SUFFIX="%{$reset_color%} "
ZSH_THEME_GIT_PROMPT_DIRTY="%{$fg[blue]%}) %{$fg[yellow]%}%1{✗%}"
ZSH_THEME_GIT_PROMPT_CLEAN="%{$fg[blue]%})"
```
but display not as expected, there's an arrow in the beginning, I mean the blue one, have no idea how to solve this, anyone meet this before?

![image](https://github.com/user-attachments/assets/aadccb3a-0cfe-4384-8754-ab55bd32f435)

### Steps to reproduce

I think the image is clear enough, have no idea how to make it normal. 

### Expected behavior

Not arrow disappear in the front

### OS / Linux distribution

14.4 (23E214)

### Zsh version

5.9

### Terminal emulator

iTerm2

### If using WSL on Windows, which version of WSL

None

**Comment by carlosala** [comment] 2024-08-07 12:28
Not our issue! Duplicate of #11637.
Thanks for the report!

**Closed** 2024-08-07 12:28 UTC

**Comment by kerthcet** [comment] 2024-08-07 14:09
Thanks @carlosala !
