### ISSUE TITLE
Mysterious  `←[?1h` character appears when typing on Windows

### ISSUE THREAD

**Issue by edmundito** [ohmyzsh/ohmyzsh#12376] opened 2024-04-22 15:47 UTC
### Describe the bug

The characters `←[?1h` appears whenever I type in my Windows terminal. It does not impact entering commands but it's annoying. This only started in recent weeks without many changes other than Windows update, OMZ updates.

 Similarly described in https://github.com/zsh-users/zsh-autosuggestions/issues/614 but I do not have the zsh-autosuggestions plugin installed (unless it's been integrated into omz directly?)

### Steps to reproduce

1. Setup git bash with zsh and omz
2. Open git bash
3. Type

### Expected behavior

Nothing should appear

### Screenshots and recordings

![image](https://github.com/ohmyzsh/ohmyzsh/assets/168664/984de2c2-3ab5-4e43-87e9-6e071affc6db)

### OS / Linux distribution

Windows 10

### Zsh version

5.9

### Terminal emulator

Windows Terminal, Cmd, Git Bash

### If using WSL on Windows, which version of WSL

None

**Comment by Jouramie** [comment] 2024-04-23 01:25
I have the same issue, it started just after updating omz. Running `zsh -df` as suggested in the issue you linked does stop the `←[?1h` from appearing on my side. I suspect this is indeed related to the zsh-autosuggestions plugin.

**Comment by carlosala** [comment] 2024-04-23 07:29
If you follow the steps mentioned here https://github.com/ohmyzsh/ohmyzsh/issues/12328#issuecomment-2043492331, does it fix the issues for you?

**Comment by edmundito** [comment] 2024-04-23 16:55
> If you follow the steps mentioned here [#12328 (comment)](https://github.com/ohmyzsh/ohmyzsh/issues/12328#issuecomment-2043492331), does it fix the issues for you?

@carlosala It does not.

> Running zsh -df as suggested in the issue you linked does stop the ←[?1h from appearing on my side. However, I doubt zsh-autosuggestions is the issue, since disabling it does not solve anything.

@Jouramie running zsh without the rcs is fine.

I found a workaround:

1. Comment out `source ./...ohmzsh.sh` script in `.zshrc`
2. Open new termina
3.  Remove the comment and re-run `source ./.zshrc`

The prompt now works with omz correctly and does not show the issue. 🤔

**Comment by carlosala** [comment] 2024-04-23 19:09
You shouldn't source zshrc. @mcornella do you know why it could appear?

**Comment by mcornella** [comment] 2024-04-27 18:42
If this is fixed by loading OMZ last it must be that some bad setting is getting overriden. Perhaps it might be related to `stty` settings backed up in `check_for_upgrade.sh` [1]? Try disabling the auto update with
```sh
zstyle ':omz:update' mode disabled
```
to see if that bypasses the issue (which would confirm that [1] is related) and also please post your `.zshrc` file that reproduces this.

[1]: https://github.com/ohmyzsh/ohmyzsh/blob/803e1a784cd520f101d126b47deea3297e6a82fc/tools/check_for_upgrade.sh#L131

**Comment by edmundito** [comment] 2024-05-01 13:25
@mcornella This did not make any difference.

Here's my .zshrc, nothing too interesting. I was trying to also disable the git autosuggest to see if that was the problem:
```
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="simple"
plugins=(git)

source $ZSH/oh-my-zsh.sh

unset ZSH_AUTOSUGGEST_USE_ASYNC
zstyle ':omz:alpha:lib:git' async-prompt no
zstyle ':omz:update' mode disabled
```

**Comment by edmundito** [comment] 2024-05-01 13:39
Hmm, I just found something that may have fixed the issue. I have an a lazy setup because I seldom use Windows and I'm running zsh through Git Bash and followed this setup: https://dominikrys.com/posts/zsh-in-git-bash-on-windows/

I just updated git for Windows and the problem is gone.

**Comment by carlosala** [comment] 2024-05-01 13:44
That makes it a `not-our-issue` situation! Thanks for the debugging!

**Closed by carlosala** 2024-05-01 13:44 UTC
Labels: Platform: Windows, Status: not reproducible

**Comment by mcornella** [comment] 2024-05-02 15:06
Thanks for posting the solution Edmundo!

**Comment by fxcosta** [comment] 2024-06-27 14:17
@edmundito thaaaaaaanks!!!!!

**Comment by Contentsearch** [comment] 2024-08-10 08:38
> Hmm, I just found something that may have fixed the issue. I have an a lazy setup because I seldom use Windows and I'm running zsh through Git Bash and followed this setup: https://dominikrys.com/posts/zsh-in-git-bash-on-windows/
> 
> I just updated git for Windows and the problem is gone.

tanks for your solution! its work for my windows.
-- updated git for Windows and the problem is gone.

**Comment by lucian-lutas** [comment] 2024-09-10 09:50
> Hmm, I just found something that may have fixed the issue. I have an a lazy setup because I seldom use Windows and I'm running zsh through Git Bash and followed this setup: https://dominikrys.com/posts/zsh-in-git-bash-on-windows/
> 
> I just updated git for Windows and the problem is gone.

thanks! working perfectly again
