### ISSUE TITLE
.oh-my-zsh dir keeps moving

### ISSUE THREAD

**Issue by churnd** [ohmyzsh/ohmyzsh#9524] opened 2020-12-16 16:46 UTC
I'm not sure if this is a bug or something wrong with my setup/environment, but it keeps happening and I don't know what causes it.  I am using a default oh-my-zsh install & the default .zshrc.  What I'm noticing that after blowing away all the zsh settings, at some point this happens:

```
➜  ~ pwd
pwd
/Users/chris
➜  ~ ls -al ./\~/
ls -al ./\~/
total 0
drwxr-xr-x    3 chris  staff    96 Dec 15 13:17 .
drwxr-xr-x@ 132 chris  staff  4224 Dec 16 11:20 ..
drwxr-xr-x   21 chris  staff   672 Dec 15 13:17 .oh-my-zsh
➜  ~ ls -al .oh-my-zsh
ls -al .oh-my-zsh
ls: .oh-my-zsh: No such file or directory
➜  ~ which zsh
which zsh
/usr/local/bin/zsh
➜  ~ zsh --version
zsh --version
zsh 5.8 (x86_64-apple-darwin20.1.0)
```

Basically, something at some point is creating /Users/chris/~ & putting .oh-my-zsh in there and I kinda suspected the automatic update process.  Anyone seen anything like this?

**Comment by mcornella** [comment] 2020-12-17 22:40
Have a look at your zshrc file. This sounds like somewhere there's a quoted `"~/.oh-my-zsh"` (the tilde character should never be quoted).

**Comment by churnd** [comment] 2020-12-17 23:06
i'm using the default .zshrc generated by oh-my-zsh:  https://gist.github.com/churnd/672ed517f8b9599e524dbdf79b1c9072

**Comment by mcornella** [comment] 2020-12-19 20:29
I assume you ran the installer multiple times. How did you run it the first time?

**Comment by mcornella** [comment] 2020-12-19 20:42
To fix it, remove the .zshrc file and `~` folder, and rerun the installer making sure to `unset ZSH` before calling it.

**Comment by churnd** [comment] 2020-12-28 16:36
Yes I have run it a few times to "fix" it, but each time I recursively removed .oh-my-zsh & the `~` folder being created in my home dir.  I followed your instructions now and I see the .zshrc was generated like so this time:

```
# Path to your oh-my-zsh installation.
export ZSH="/Users/chris/.oh-my-zsh"
```

Is there a way to make that not an absolute path, but a relative one?  I use a few different computers & the homedir isn't always /Users/chris.

**Comment by mcornella** [comment] 2020-12-28 18:41
You can manually set it to `$HOME/.oh-my-zsh`, in this case.

**Comment by churnd** [comment] 2021-01-04 15:01
I think using `$HOME` instead of `~` in .zshrc resolved the issue.  Haven't seen it come up since.  Does the tilde not work well with ZSH?

**Comment by mcornella** [comment] 2021-01-04 15:04
> Does the tilde not work well with ZSH?

The tilde needs to not be quoted:
```
ZSH=~/.oh-my-zsh <-- this expands to means $HOME/.oh-my-zsh
ZSH="~/.oh-my-zsh" <-- this expands to <current_directory>/~/.oh-my-zsh
```

Closing this as non-reproducible.

**Closed by mcornella** 2021-01-04 15:04 UTC
Labels: Support

**Comment by datavistics** [comment] 2021-03-21 06:53
Looks like my next child will be named mcornella. Not to be confused with "mcornella".
