### ISSUE TITLE
Prompt not showing up

### ISSUE THREAD

**Issue by zilton7** [ohmyzsh/ohmyzsh#10491] opened 2021-12-08 14:48 UTC
### Describe the bug

I am using zsh on my Macbook, but sometimes out of nowhere the terminal prompt just doesn't show up when I launch it, and only restarting the computer fixes that. Any ideas about what could be causing this behavior? Is there a way for me to reload zsh w/o needing to restart the computer?

Zsh config file: https://gist.github.com/zilton7/e5feb4993a9b334aacc5279603ff7cd9

PS I can run bash with no problem whatsoever.

### Steps to reproduce

Install using official guide

### Expected behavior

to load up

### OS / Linux distribution

MacOS Mojave 10.14.6

### Zsh version

5.3

### Terminal emulator

Iterm2/Terminal/VSCode

**Comment by mcornella** [comment] 2021-12-10 11:04
Have you checked if you can still run commands even without a prompt? You could try for example running `ls`.

> Is there a way for me to reload zsh w/o needing to restart the computer?

You can run `exec zsh` or `omz reload` (OMZ specific). **Do NOT use `source ~/.zshrc`**, that can have unintended side effects.

**Comment by zilton7** [comment] 2021-12-11 09:50
Yes, I couldn't run any commands, but I was able to solve it by running this on bash terminal `pkill -9 -f zsh `, but have no idea why zsh get stuck like that in the first place.

**Comment by mcornella** [comment] 2021-12-13 10:30
You could add `set -xv` to the top of your zshrc file so that all zsh instructions are logged in the terminal every time you start zsh. This way you can see in which instruction the shell is stuck. To turn it off, run `set +xv`.

**Comment by mcornella** [comment] 2021-12-21 16:07
I'm going to close this issues since we can't reproduce this. Feel free to reopen if you still experience this and can follow the instructions above (https://github.com/ohmyzsh/ohmyzsh/issues/10491#issuecomment-992322890).

**Closed by mcornella** 2021-12-21 16:07 UTC
Labels: Support
