### ISSUE TITLE
Alt-Left-Arrow and Alt-Right-Arrow broken on urxvt in openSUSE

### ISSUE THREAD

**Issue by michaeltraxler** [ohmyzsh/ohmyzsh#2750] opened 2014-04-25 10:57 UTC
since a recent "git pull" the always working bound-keys
```
^[^[[D (Alt-Cursor-Left)
^[^[[C (Alt-Cursor-Right)
```
are not resulting anymore in a backward-word (or forward-word), even though the correct bind keys are set.
```
"^[^[[D" backward-word
"^[B" backward-word
"^[[1;5D" backward-word
"^[b" backward-word
```
Alt-B and Alt-F are still working.
I'm puzzled.
Thanks for any help as these keys are really in my muscle-memory and I can't live without them...

**Comment by apjanke** [comment] 2015-06-25 22:09
Probably caused by #1355, which switched to using terminfo for key bindings.

Yeah, if that's absent, I think it might mess up some of your key bindings, because zsh might not be set up to switch in to the right terminal mode when it starts editing a line.

Is this still happening for you? If so, what platform/OS, terminal program, and `$TERM` value are you using?

**Comment by michaeltraxler** [comment] 2015-06-28 01:27
Hello,

yes, the problem is still happening on my systems (not all of them).

I use OpenSuSE13.2, urxvt and the TERM value is TERM=rxvt-unicode.
With xterm it works.
xterm sends "^[[1;3D" instead of ^[^[[D

On my notebook I have the same OS, same version of urxvt, same .oh-my-zsh
config and it is working here.

If I use ssh from the notebook (working ALT-Left) to the non working system,
it is still not working.
If I use the non working via vncviewer: still not working.

I don't see the difference....

Michael

**Comment by apjanke** [comment] 2015-06-28 05:29
Okay. I can reproduce this. when I run zsh in urxvt on OpenSuSE 13.2, normally, alt-left and alt-right do forward and backward word. When I have OMZ loaded, though, they insert "D" and "C" characters. If I comment out the `zle-line-init` function like you do, they start working again.

I think the problem might be that the `terminfo` entry for `rxvt-unicode` that ships with OpenSuSE 13.2 is incorrect. It has the wrong sequences defined for the left and right arrows, and for `smkx` and `rmkx`. That means the `echoti` commands in those `zle-line-init` and `zle-line-end` functions are outputting the wrong characters, which I think is messing up the interpretation of your arrow keystrokes. (To see this, compare the output of `infocmp -1 rxvt-unicode | grep '[rs]mkx\|kcu[bf]1` with the codes documented in `man 7 urxvt`.)

As a workaround, yeah, comment out those functions – as long as nothing else changes your terminal out of application keypad mode, you'll be okay. (You can do this in your `.zshrc` or custom code by just redefining those functions to do nothing, if you don't want to modify your main OMZ source code.)

The long term fix is probably to install a correct `terminfo` entry for `rxvt-unicode` on your OpenSuSE system. And report it to upstream so they can fix it for everyone. (Their `/etc/zshrc` key bindings work despite the bad entry because they're using hardcoded sequences instead of `terminfo`; it's kind of a hack.)

**Comment by michaeltraxler** [comment] 2015-06-28 15:40
Yes, you hit the spot! 
I found that systems where OMZ works in urxvt have a different date and content of the file
/usr/share/terminfo/r/rxvt-unicode.
For some reason this file was different on two "identical" systems even though the corresponding package was the same: terminfo-base-5.9-52.2.3.x86_64
But anyhow, the file /usr/share/terminfo/r/rxvt-unicode in this package is faulty.
By the way: one more workaround is:
<code>
cd /usr/share/terminfo/r;
cp rxvt rxvt-unicode
</code>
I will try to report this to OpenSuse.
Thanks again for finding the source of the problem.

**Comment by michaeltraxler** [comment] 2015-06-28 16:11
One more solution for the problem, as it is hard to get it through the whole procedure of upstream correction:
mkdir -p ~/.terminfo; tic -o .terminfo  /usr/share/doc/packages/rxvt-unicode/etc/rxvt-unicode.terminfo
This fixes the problem for me and I learned some stuff about terminfo.

**Comment by apjanke** [comment] 2015-06-28 17:04
Excellent.

I think you could make that last fix survive updates to the terminfo-base package by defining a terminfo search path that puts your `~/.terminfo` ahead of the system one. In your `.zshrc` or something similar, do this.

```
export TERMINFO_DIRS=~/.terminfo:$TERMINFO
unset TERMINFO
```

If I understand the terminfo man page right (in the section "Fetching Compiled Descriptions"), that will have your ~/.terminfo mask corresponding entries in the system terminfo dir. (Unsetting `$TERMINFO` is necessary because it takes precedence over `$TERMINFO_DIRS`.)

**Comment by apjanke** [comment] 2015-06-28 18:29
I've submitted an upstream bug report to openSUSE: https://bugzilla.opensuse.org/show_bug.cgi?id=936330

**Comment by apjanke** [comment] 2015-06-28 18:44
Interesting side note: the root cause of this may be that the official GNU terminfo distribution does not include an rxvt-unicode entry because [its maintainer and urxvt's author don't get along](https://lists.gnu.org/archive/html/bug-ncurses/2009-10/msg00032.html). So downstream packagers have to add it in, and are more likely to get it wrong and introduce inconsistencies between distributions.

**Comment by michaeltraxler** [comment] 2015-06-28 19:06
Thank you so much for doing all this!
And it is a pity that they don't get along, as most likely many users suffer from this...
More subtle. They will just be frustrated and think that urxvt is bad, as the keys they are used to don't work anymore.
To the TERMINFO_DIRS workaround:
This works great (keeping the /usr/share/terminfo/r/rxvt-unicode and using as priority the terminfo in the home directory) if I call zsh in the command line.
But if I start urxvt the started zsh behaves differently and uses the /usr/share/terminfo/r/rxvt-unicode as default. 
I can also see this in the strace output of starting zsh (only local terminfo is used) and starting a new urxvt (only usr/share/terminfo/r/rxvt-unicode is used).
Any hint to that?

**Comment by apjanke** [comment] 2015-06-28 20:37
Okay, I get the same behavior. Don't really know why it's happening.

The `man 1 urxvt` page says this.

```
ENVIRONMENT
       urxvt sets and/or uses the following environment variables:
[...]
       TERMINFO
           Set to the terminfo directory iff urxvt was configured with
           "--with-terminfo=PATH".
```

So I think part of it is that `urxvt`, as built for openSUSE, is setting `TERMINFO` when it's being launched, and this is overriding your unsetting of it. And then something in the `zsh` startup sequence is seeing and respecting that before you get a chance to change it in your `~/.zshrc`.

When I use `urxvt -e strace zsh -l` to see tracing, I can see that it looks at both `/usr/share/terminfo` and `~/.terminfo`, but does the system one first, and that's where it finds the entry. Maybe that's enough to stick you with the system definition: maybe `zsh` sees that once and then caches the entry, so `$terminfo` is loaded from there, even if you later change `$TERMINFO` and `$TERMINFO_DIRS`.

I suspect that's because `zsh` uses the curses library, and the curses library gets invoked during startup before `.zshrc` is run, and it remembers the value of `$TERMINFO` it saw on startup.

...yep: the openSUSE rxvt-unicode-9.15-4.1.2.src.rpm has `--with-terminfo=%{_terminfo}` defined in the build options.

As a workaround, you can invoke `urxvt` as `urxvt -e env TERMINFO="" zsh -l` which will have the effect of unsetting `$TERMINFO` early enough in the process that everything respects it. Works for me. You could set up an alias for it, and find somewhere to tweak the definition of desktop items that you're launching it from.

You could also rebuild your urxvt from the source RPM, removing the `--with-terminfo` option.

**Comment by michaeltraxler** [comment] 2015-06-28 22:11
Thanks again! You are very helpful! 
It is good that I now can run OMZ on the many machines which I administer without tweaking the OMZ config.

**Comment by apjanke** [comment] 2015-07-07 03:11
Would you mind changing this issue's title to "Alt-Left-Arrow and Alt-Right-Arrow broken on urxvt in openSUSE" to clarify the specific problem? There's a lot of OMZ issues around arrows and key bindings and it's getting hard to tell them apart.

**Comment by michaeltraxler** [comment] 2015-07-07 08:23
Hi,

done!

Michael

**Comment by apjanke** [comment] 2015-07-07 08:50
Looks good. Thanks!

**Comment by mcornella** [comment] 2015-12-02 01:58
Hi @michaeltraxler and @apjanke, what's the status on this? Should we maybe try to fix it in oh-my-zsh (or at least dig further)? It wasn't clear to me if this was due only to wrong terminfo entries...

The follow up at bugzilla [suggests that this may be happening due to the wrong mode being set](https://bugzilla.opensuse.org/show_bug.cgi?id=936330#c2) (perhaps this ties to those `[rs]mkx` sequences being sent?). I don't know, let me know how you think we should proceed with this issue.

**Comment by apjanke** [comment] 2015-12-02 09:08
In my opinion, this is a bug in OpenSUSE's terminal setup, and Dr. Fink's response is incorrect; I just haven't found time to follow it up.

The way I read it, their `rxvt-unicode` terminfo entry is wrong, but it happens to be wrong in a way such that bindings using it work when our `[sr]mkx` stuff is not working (though they shouldn't). Now that we're using `[sr]mkx`, those terminfo-based bindings will no longer work (though they should).

If I'm right about the cause, fixing it in OMZ effectively means tracking and working around issues in the terminfo database shipped with OpenSUSE or other Linux distributions, which sounds like a bit of a mess and the wrong place to put responsibility for that data. I'm inclined to treat it as an upstream bug and pursue that bug report with OpenSUSE, and advise users to fix it at the system level, maybe by installing a fixed terminfo definition. Or just using a different terminal or Linux distro.

On the other hand, I think it's pretty unlikely that this will get fixed at the distro level, given how complicated this stuff is and how difficult it is to convince people they might be wrong about it. And it's limited in scope, so it wouldn't be that hard to fix in OMZ: we could create a plugin that redistributes the `rxvt-*` terminfo entries and has code to load them in front of the system terminfo. ... Oh, wait, that won't quite work, because it would have to be loaded before the `lib/*.zsh` stuff which uses terminfo to do its key bindings. Well, hmm. We'd have to hack in a special hook for it, I think. It'd be adding a new mechanism to OMZ, with potential to get messy.

**Comment by michaeltraxler** [comment] 2015-12-02 10:11
Hi, as the terminfo-maintainer and the urxvt-developper can't agree on a way to communicate to solve the problem we are kind of stuck....
Maybe an entry in the README of OMZ is the way to go, mentioning that for OpenSuSE (and others?) you need to run every time you update the system the following command:
<code>
$ tic -o /usr/share/terminfo/ /usr/share/doc/packages/rxvt-unicode/etc/rxvt-unicode.terminfo
</code>
At least that is what I have to do on all my systems to get it working. It is annoying (as I always forget it) but a "price" I'm willing to pay to be able to use OMZ (great! can't live without it anymore) and urxvt (also great!).
Maybe mentioning the problem in more places (README) will push the two persons to talk to each other again and solve the issue for all users?

**Comment by apjanke** [comment] 2015-12-15 08:02
After doing some more reading, I think the OpenSUSE terminfo entry might be correct, or at least not the only issue, and I got things backwards.

It looks like urxvt uses different mode control sequences for the cursor keypad and numeric keypad. And even though the urxvt man page refers to the numeric keypad application mode as "SMKX", the terminfo usage of `smkx` expects it to usually switch both keypads. The OS X terminfo entry for `rxvt-unicode` defines `smkx` to only switch the numeric keypad into application mode. The OpenSUSE one defines `smkx` to switch both the numeric keypad and cursor keypad into application mode. Both appear to define the cursor keys to be consistent with their entry's mode switching.

The problem might just be that these hardcoded key bindings:
```
"^[^[[D" backward-word
"^[^[[C" forward-word
```
use the sequences that correspond to cursor local mode. Now that OMZ is switching into cursor application mode inside ZLE, the keys are emitting a different character sequence.

The fix here might be just to switch to terminfo-based key bindings.
```
bindkey "\e$terminfo[kcub1]" backward-word
bindkey "\e$terminfo[kcuf1]" forward-word
```
This should work with both variants of the `rxvt-unicode` terminfo entries, and whether or not OMZ is using `smkx` and application mode or not. But it won't be portable across different terminals: different terminals don't treat Alt+whatever in the same way.

This worked for me on OpenSUSE. (Didn't work on OS X; it doesn't seem like `urxvt` running under XQuartz is treating the Alt modifier as "prefix with escape", so it just emits the normal cursor arrow key sequences.)

**Comment by michaeltraxler** [comment] 2015-12-16 12:29
Thank you so much. Works like a charm! For me the problem is now solved. I'm surprised how complicated all this mapping is....

**Comment by stephen304** [comment] 2016-01-11 02:09
I'm having this same problem with omz+zsh on arch with rxvt-unicode, which has TERM=rxvt-unicode-256color. 

I tried to null out the aforementioned functions in my .zshrc, but it doesn't seem to have made any difference.

    function zle-line-init() {}
    function zle-line-finish() {}

Any ideas?

**Comment by apjanke** [comment] 2016-02-07 04:06
> I tried to null out the aforementioned functions in my .zshrc, but it doesn't seem to have made any difference.
>
> function zle-line-init() {}
> function zle-line-finish() {}

Other way around. Leave those functions as OMZ defines them, and add these key bindings to your `~/.zshrc`. See if that works.

```
bindkey "\e$terminfo[kcub1]" backward-word
bindkey "\e$terminfo[kcuf1]" forward-word
```

**Comment by stephen304** [comment] 2016-02-08 16:38
@apjanke Thanks that worked! I saw that fix above, but since everybody was talking about terminfo files, I thought it was some fix for a terminfo file and I wasn't sure where to put it.

**Comment by Quadrocube** [comment] 2016-04-20 12:34
Any ideas on why 

    bindkey "\e$terminfo[kcub1]" backward-word
    bindkey "\e$terminfo[kcuf1]" forward-word

works if plugged directly into zsh session but doesn't persist for newly-created sessions even if copied into .zshrc? Might the problem be in 

    source $ZSH/oh-my-zsh.sh

as last line?

**Comment by mcornella** [comment] 2016-04-20 12:57
@Quadrocube that's probably it. Any user modifications should go _after_ sourcing OMZ.

**Comment by apjanke** [comment] 2016-04-20 19:56
Yeah. Especially if you have your `$EDITOR` set to `vi`. `bindkey` operates on the current default keymap, which OMZ switches to be `emacs`, but before that, `zsh` may have defaulted it to `vi` based on your editor setting, so it may have gone in the wrong keymap.

**Comment by robbyrussell** [comment] 2021-06-13 18:23
⌛️ Given how long this has been lingering, it sounds like the best approach (for now) is for users to account for the ordering and/or sourcing after OMZ. Closing this for the time being.

**Closed by robbyrussell** 2021-06-13 18:23 UTC
Labels: Bug, Platform: Linux, Topic: bindkey
