### ISSUE TITLE
self-update on macOS aborts on case-different filename

### ISSUE THREAD

**Issue by zao** [ohmyzsh/ohmyzsh#7259] opened 2018-10-09 07:31 UTC
When running the built-in auto-updater, it bails out on trying to change the case of `plugins/ubuntu/README.md`. Case changes in git is very dangerous around filesystems with interesting case-insensitive semantics.
The effect on my APFS volume when doing a `rm readme.md` in a directory containing both `README.md` and `readme.md` is to delete both, for example.
This is completely blocking forward progress in my checkout.
```
 create mode 100644 plugins/ubuntu/README.md
 delete mode 100644 plugins/ubuntu/readme.md
 create mode 100644 plugins/vagrant/README.md
 create mode 100644 plugins/vundle/README.md
 create mode 100644 plugins/web-search/README.md
 create mode 100644 plugins/yum/README.md
First, rewinding head to replay your work on top of it...
error: The following untracked working tree files would be overwritten by checkout:
	plugins/ubuntu/README.md
Please move or remove them before you switch branches.
Aborting
could not detach HEAD
There was an error updating. Try again later?
```

**Comment by zao** [comment] 2018-10-09 07:35
I could mitigate this problem by checking out a fresh clone of the repository, but wanted to file this issue for anyone searching for these problems.

**Comment by mcornella** [comment] 2018-10-09 14:29
Can you try a hard reset to the most recent commit? (provided you don't have any changes in the working directory to be lost)

**Comment by zao** [comment] 2018-10-09 19:35
The tree was clean before this attempt to pull.
I didn't try to do anything with the FETCH_HEAD yet, I'll see what I can do when I get back into the office tomorrow.
It's a bit icky as the create/delete operations happen as git tries to wrangle the working copy into what it thinks the working copy should be, so one might need to tip-toe around the offending create+delete.

**Comment by ssbarnea** [comment] 2018-10-18 09:06
What makes this even worse is that this bug will break oh-my-zsh on 99% of MacOS computers which by default have case-insensitive filesystems. One would have to go a really long way to make the filesystem case-sensitive on MacOS and after doing this he would discover that LOTs of apps are broken because their developers were not careful enough to test them on case-sensitive filesystems.

I think we need an `--force` option for upgrade script that would do "whatever it takes" to upgrade it.

**Comment by ssbarnea** [comment] 2018-10-18 09:15
Temporary hack that worked for me:
```
cd ~/.oh-my-zsh
git config core.ignorecase true
```
Now git rebase will succeed.

**Comment by Neberheim** [comment] 2020-09-28 01:03
I attempted the above workaround, without success. I installed ohmyzsh about three weeks ago and I'm fairly new to git, so are there any other workarounds available? Is it simply to `rm` the offending file?

```
39 files changed, 875 insertions(+), 591 deletions(-)
 create mode 100644 .github/FUNDING.yml
 create mode 100644 plugins/scd/_scd
 mode change 100644 => 100755 plugins/scd/scd
First, rewinding head to replay your work on top of it...
error: The following untracked working tree files would be overwritten by checkout:
	.github/FUNDING.yml
Please move or remove them before you switch branches.
Aborting
fatal: Could not detach HEAD
There was an error updating. Try again later?
```

**Comment by mcornella** [comment] 2020-09-28 11:39
@Neberheim can you run `git log -- .github` inside the `$ZSH` folder? Also `cat .github/FUNDING.yml`. I don't see ever being a `.github/funding.yml` file. (?)

**Comment by Neberheim** [comment] 2020-11-19 06:03
@mcornella Apologies, I thought I had notifications for this thread on; I completely forgot about it. Here's the log output: https://pastebin.com/raw/rLMiwArD

And
```
$ cat .github/FUNDING.yml
github: [robbyrussell, mcornella, larson-carter]
open_collective: ohmyzsh

**Comment by Neberheim** [comment] 2020-11-19 06:12
Actually, this might have been all you were looking for:
```
...skipping...
commit 079e7bb5e0a79171f3356d55d3f6302a82645a39 (grafted, HEAD -> master)
Author: Marc Cornellà <marc.cornella@live.com>
Date:   Thu Aug 6 08:55:29 2020 +0200

    lib: remove CTRL-Backspace key binding altogether

    It conflicts with normal Backspace behavior. Fixes #9155
```

**Comment by mcornella** [comment] 2020-11-20 19:14
> error: The following untracked working tree files would be overwritten by checkout:

I don't know, it looks like there's something going on that I'm not aware of. If the problem is really `.github/funding.yml` the git reflog should have it (try `git reflog -- .github/funding.yml` inside the `$ZSH` folder). In any case, if you haven't made any changes to the `$ZSH` folder (no files modified or added, and no local commits), you should be able to `rm .github/funding.yml` and then `git reset --hard origin/master`).

**Comment by Neberheim** [comment] 2020-11-21 21:29
`rm` was enough to allow `omz update`to run successfully. The update did create another `.github/funding.yml` so it will be interesting to see if it gets hung again.

**Comment by mcornella** [comment] 2020-11-22 14:03
Alright thanks for reporting back.

**Closed by mcornella** 2020-11-22 14:03 UTC
Labels: Area: updater, Platform: macOS, Support
