### ISSUE TITLE
Visual/copy mode indicator in vi-mode plugin

### ISSUE THREAD

**Issue by ajaydwarkani** [ohmyzsh/ohmyzsh#11549] opened 2023-03-08 17:09 UTC
Currently I can only show indicators for "Insert" and "normal" mode. Can you please also add "Visual/Copy" mode indicator?

**Comment by mcornella** [comment] 2023-03-31 06:29
Duplicate of #11586. See https://github.com/ohmyzsh/ohmyzsh/issues/11586#issuecomment-1491356516.

**Comment by mcornella** [comment] 2023-03-31 06:36
Disregard that. This is for an indicator and not a cursor. 

I'd like to know what is the purpose behind that. Do you not get a highlight of the text when entering visual mode?

**Comment by mcornella** [comment] 2023-04-05 20:22
I'll close this because I don't really see a use for this feature, feel free to reopen with a clear use case.

**Closed by mcornella** 2023-04-05 20:22 UTC
Labels: Feature, Area: plugin, Topic: bindkey

**Comment by rwmitchell** [comment] 2023-04-05 20:58
Using p10k, I have these settings, which changes my prompt based on the the current vi mode:

```  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIINS_CONTENT_EXPANSION='❯'
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VICMD_CONTENT_EXPANSION='' # ❮'
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIVIS_CONTENT_EXPANSION='V'
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIOWR_CONTENT_EXPANSION='▶'```

The glyphs don't render here, but otherwise it indicates the method.  For visual mode, a rather boring 'V' is displayed.  But yes, I'm not sure how much attention I pay to it given the text being marked has the background highlighted.
