### ISSUE TITLE
ctrl + c not respond

### ISSUE THREAD

**Issue by fengxuway** [ohmyzsh/ohmyzsh#12448] opened 2024-05-24 02:29 UTC
### Describe the bug

press down `ctrl + c` not working, then press any key will clear terminal

I trace back to this commit https://github.com/ohmyzsh/ohmyzsh/commit/ec1afe9dd683c36e6384db25fc1e95acbb0cbc7a ,
problem occured after this commit

### Steps to reproduce

1. update oh my zsh to last version
2. press `ctrl + c`
3. press any key then clear terminal

### Expected behavior

step 2 press `ctrl+c` will clear terminal

### OS / Linux distribution

Centos 7.5

### Zsh version

5.0.2

### Oh My Zsh version

5.0.2

### Terminal emulator

master (1b29fd3)

### If using WSL on Windows, which version of WSL

None

**Comment by migs35323** [comment] 2024-05-24 10:57
i am facing  a similar issue since recent updates or changes
when i press ctrl + c it seems the terminal gets stuck when returning

**Comment by carlosala** [comment] 2024-05-24 11:04
It's a duplicate of #12360. Let's move the discussion there!

**Closed by carlosala** 2024-05-24 11:04 UTC
Labels: Bug
