### ISSUE TITLE
autocompletion of directories not complete 

### ISSUE THREAD

**Issue by levinpat** [ohmyzsh/ohmyzsh#11274] opened 2022-10-19 15:24 UTC
### Describe the bug

if you want to cd into a directory, that contains two sub-directories with names that start with two neighboring letters in the alphabet, the auto completion (tab-key) will only suggest the "higher" letter  (e.g  b over a). 

### Steps to reproduce

1. create this directory structure: 
`.
└── test
    ├── a2
    └── b1`
2. move into directory "test"
3. type "cd" and use tab-key to auto-complete directory 
4. auto completion suggests "B" instead of listing both directories

### Expected behavior

show both directory names "a2" and "b1". 

### OS / Linux distribution

manjaro/ arch 

### Zsh version

5.9

### Terminal emulator

Gnome Terminal 

### Additional context

works on debian with same version number, but not arch and manjaro. newest oh-my-zsh was installed

**Comment by dflaxx** [comment] 2022-10-19 16:10
I can reproduce this on 5.15.74-3-MANJARO, zsh version 5.9, current oh-my-zsh:
https://asciinema.org/a/6iP6zfKubbMmGeuyLl6ah5iWY

The problem occurs in the `test` directory. I typed `cd test/` and then tabbed to get auto-completions, which produced `test/B` as the unexpected result. In the `expected` directory, all is well and I get a listing of sub-directories `a`, `b`, and `c` to tab through.

The problem also occurs if `test` contains directories

- `a` and `b` (without the numbers), or
- `u_123` and `v_456` (which auto-completes to `V_`).

It does not occur if `test` contains directories `a` and `c` (non-neighboring letters).

**Comment by carlosala** [comment] 2022-10-19 18:18
Duplicate of https://github.com/ohmyzsh/ohmyzsh/issues/10972. See https://github.com/ohmyzsh/ohmyzsh/issues/10972#issuecomment-1146806099.

**Closed by carlosala** 2022-10-19 18:18 UTC

**Comment by mcornella** [comment] 2023-02-26 19:38
Fixed in https://github.com/ohmyzsh/ohmyzsh/pull/11526. Get the fix with `omz update`.
