### ISSUE TITLE
Minimal theme: prompt does not display information about git status

### ISSUE THREAD

**Issue by faciledictu** [ohmyzsh/ohmyzsh#12402] opened 2024-05-07 21:41 UTC
### Describe the bug

When using the Minimal theme, there is no git status indication at the command line prompt when you are in the valid repo directory.

### Steps to reproduce

1. Activate 'minimal' theme
2. Enter to any git repo

### Expected behavior

There is information including the name and status (dirty or clean) of the current branch in the prompt

### Actual
<img width="594" alt="current" src="https://github.com/ohmyzsh/ohmyzsh/assets/104712148/c8520f24-80c3-442c-9740-25e7d1fcf391">

### Some tests
<img width="598" alt="test" src="https://github.com/ohmyzsh/ohmyzsh/assets/104712148/c61ed7f4-aa29-424d-aee7-a4f4b5e641f1">

### OS / Linux distribution

macOS 13.6.6

### Zsh version

5.9

### Terminal emulator

Terminal.app, iTerm2

### If using WSL on Windows, which version of WSL

None

### Additional context

If you hardcode `$(git_prompt_info)` in $PROMPT, it will works. Currently, there is a function `$(vcs_status)` there. See the screenshots for more details.

Note that in the current case, the command `git_prompt_info` itself does not produce any output to the console.

**Comment by carlosala** [comment] 2024-05-08 10:04
That's expected, we're working on a fix. Duplicate of #12328.
See https://github.com/ohmyzsh/ohmyzsh/issues/12328#issuecomment-2043492331

**Closed by carlosala** 2024-05-08 10:04 UTC
