### ISSUE TITLE
Installing zsh via macports: "compinit:503: no such file or directory"

### ISSUE THREAD

**Issue by nbelakovski** [ohmyzsh/ohmyzsh#9931] opened 2021-05-25 18:08 UTC
**Describe the bug**
Whenever I start a new shell, I see the following 2 error messages:
```
compinit:503: no such file or directory: /usr/local/share/zsh/site-functions/_brew
compinit:503: no such file or directory: /usr/local/share/zsh/site-functions/_brew_cask
```

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Install zsh on OS X via macports
2. Install oh-my-zsh
3. Open a new shell

**Expected behavior**
Obviously I should get no error messages when opening a new shell

**Self Check**

- Have you tried reaching out on the [Discord server](https://discord.gg/ohmyzsh)? 
  Yes

- Also searching existing [GitHub Issues](https://github.com/ohmyzsh/ohmyzsh/issues?q=) might help you get quicker support
There's a similar issue, but the resolution is to run `brew cleanup` which doesn't work for me as I neither installed zsh via brew nor do I even have brew on my system (https://github.com/ohmyzsh/ohmyzsh/issues/9602)

**Desktop (please complete the following information):**

 - OS / Distro: macOS
 - Latest ohmyzsh update?: Yes
 - ZSH Version: 5.8
 - Terminal emulator: iTerm2

**Comment by nbelakovski** [comment] 2021-05-25 19:18
I did some digging and just decided to delete the two offending files. It might cause issues if I install brew later on, but I don't plan to. Leaving this open in case someone has a better solution.

**Comment by mcornella** [comment] 2021-06-14 08:38
Duplicate of https://github.com/ohmyzsh/ohmyzsh/issues/9602

**Closed by mcornella** 2021-06-14 08:38 UTC
Labels: Bug
