### ISSUE TITLE
cd for zoxide

### ISSUE THREAD

**Issue by MuadJOmar** [ohmyzsh/ohmyzsh#12667] opened 2024-09-12 22:13 UTC
### If the feature request is for a plugin or theme, specify it here.

zoxide pplugin

### If the feature solves a problem you have, specify it here.

Add a Way to Use cd for zoxide in The Plugin.

### Describe the proposed feature.

Add a Way to Use cd for zoxide in The Plugin.

### Describe alternatives you've considered

Add This Line in The zoxide.plugin.zsh File

eval "$(zoxide init --cmd ${ZOXIDE_CMD_OVERRIDE:-cd} zsh)"

**Comment by carlosala** [comment] 2024-09-18 18:32
Hi! If you want to use `cd` for `zoxide` you can enable the plugin and set `export ZOXIDE_CMD_OVERRIDE=cd` before sourcing `oh-my-zsh.sh`.
Closing, thanks!

**Closed by carlosala** 2024-09-18 18:32 UTC
Labels: Feature

**Comment by miracuruzrh** [comment] 2024-09-29 19:41
> Hi! If you want to use `cd` for `zoxide` you can enable the plugin and set `export ZOXIDE_CMD_OVERRIDE=cd` before sourcing `oh-my-zsh.sh`. Closing, thanks!

Hi, I have a question to this.

I too want to replace my cd commad with the command from zoxide. I'm using debian bookworm, ZSH is installed and omz is up to date as well. I load the following plugins: `plugins=(git zoxide)`
When I follow your advise to set `export ZOXIDE_CMD_OVERRIDE=cd` before before sourcing `oh-my-zsh.sh`, then I get the error message: `cd:1: maximum nested function level reached; increase FUNCNEST?`.

Only help would be to increase FUNCNEST to 1000, but this would make the `cd` command very slow.
I think, the issue is, because the `cd` command is invoked recursively. But I wasn't able to find out, why exactly.

I use `omz version` master (a72a264)

p.s.
I have also tried to load zoxide not as plugin but with this line in my `.zshrc` configuration: `eval "$(zoxide init --cmd cd zsh)"`.
But this leads to the same error.

I have also included my `.zshrc` file. Just renamed it to .txt to be able to upload it.
[zshrc.txt](https://github.com/user-attachments/files/17180933/zshrc.txt)

May I ask, if there is a solution to this problem?
