### ISSUE TITLE
running `gcm` shows `Already on 'develop`

### ISSUE THREAD

**Issue by iamhaseebiqbal** [ohmyzsh/ohmyzsh#9114] opened 2020-07-15 07:55 UTC
**Describe the bug**
Running `gcm` shows 
```
Already on 'develop'
Your branch is up to date with 'origin/develop'.
```

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Enable this plugin 'git'
2. Run command 'gcm'

**Expected behavior**
Current branch should switch to `master`

**Screenshots and/or Recordings**
https://ibb.co/RGXyCnb

**Desktop (please complete the following information):**

 - OS / Distro: MAC OS Catalina 10.15.4 (19E287)
 - Latest ohmyzsh update?: YES
 - ZSH Version: 5.7.1 (x86_64-apple-darwin19.0)
 - Terminal emulator: iTerm2 Build 3.3.12

**Comment by bartekpacia** [comment] 2020-07-15 11:38
Hi @iamhaseebiqbal! What's the output of `$ which gcm` at your machine?

**Comment by iamhaseebiqbal** [comment] 2020-07-15 11:54
Hi @bartekpacia! the output is 
```
gcm: aliased to git checkout $(git_main_branch)
```

**Comment by bartekpacia** [comment] 2020-07-15 12:11
My output is `gcm: aliased to git checkout master`

You probably have `git_main_branch` set to `develop` or `origin/develop`. You can test this by running `$ echo $git_main_branch`.

**Comment by iamhaseebiqbal** [comment] 2020-07-15 12:40
That's a possibility. It was working fine until few days ago. At-least I didn't update it intentionally.  

How do I override it? I saw some references that i can set it in `.zshrc` but i am not sure exactly how. Do you know the exact command may be?

**Comment by dotomaz** [comment] 2020-07-15 14:01
Same here. We have `develop` as our main branch. But are still using `master`. So `gcm` no longer works. Looks like [this](https://github.com/ohmyzsh/ohmyzsh/commit/55a98fc06d9ea9d003683dec5aae6cb6b0130ab0#diff-4ad2773a26526d0e361e66139c283099) is the cause.

**Comment by bartekpacia** [comment] 2020-07-15 14:05
> That's a possibility. It was working fine until few days ago. I didn't update it intentionally.
> 
> How do I override it? I saw some references that i can set it in `.zshrc` but i am not sure exactly how. Do you know the exact command may be?

That's strange, but don't worry, you can definitely override this in (as you said) `.zshrc`. First, open that file (it should be located in your root directory) and at the end of it add this line

`export git_main_branch=master`.

This is kind of a dirty hack but if you just want `gcm` to work, this should be enough. Let me know if this worked!

**Comment by dotomaz** [comment] 2020-07-15 14:11
@bartekpacia This didn't work for me. I needed to do my own alias `alias gcm="git checkout master"` in `~/.zsh_aliases`.

**Comment by iamhaseebiqbal** [comment] 2020-07-15 14:38
`export git_main_branch=master` didn't work for me unfortunately.
However adding `alias gcm="git checkout master` at the end of `.zshrc` did the trick.

thanks @bartekpacia , @dotomaz :-)

**Comment by mcornella** [comment] 2020-07-15 15:05
The `git_main_branch` function was recently changed, now it should be fixed. Please manually update with `upgrade_oh_my_zsh`.

**Closed** 2020-07-15 15:15 UTC
Labels: Type: support
